#!/usr/bin/env bash
set -o nounset -o pipefail -o errexit
IFS=$'\t\n' # Stricter IFS settings
rc=0

docker run \
  -v ~/.ssh:/home/devops/.ssh \
  -v /tmp/.ssh:/tmp/.ssh \
  -v ~/.oh-my-zsh/custom:/home/devops/.oh-my-zsh-custom \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -e SSH_AUTH_SOCK=/tmp/.ssh/ssh_auth_sock \
  --dns 8.8.8.8 \
  -it jugglebot-dev:focal-native

