#!/usr/bin/env bash
set -o nounset -o pipefail -o errexit
IFS=$'\t\n' # Stricter IFS settings
rc=0

AUTH_SOCK_DIR="$(dirname "${SSH_AUTH_SOCK}")"

docker run \
  -v "${AUTH_SOCK_DIR}":"${AUTH_SOCK_DIR}" \
  -e SSH_AUTH_SOCK="${SSH_AUTH_SOCK}" \
  -v /var/run/docker.sock:/var/run/docker.sock \
  -v ~/.oh-my-zsh/custom:/home/devops/.oh-my-zsh/custom \
  --dns 8.8.8.8 \
  -it jugglebot-native-dev:focal

