---
- name: Provision the Ubuntu 20.04 docker native platform host
  hosts: localhost
  connection: local

  tasks:

  - name: Disable the sudo welcome message
    copy:
      content: ''
      dest: "{{ home_dir }}/.sudo_as_admin_successful"
  
  - name: Provision the Ubuntu environment
    import_tasks:
      file: "{{ playbook_dir }}/../ubuntu-common/dev_env_tasks.yml" 

