# For sending the ball butler command


# Note that these input ranges are enforced by can_interface
float32 yaw_angle_rad   # The yaw angle in radians (-π to π)
float32 pitch_angle_rad # The pitch angle in radians (0 to π/2)
float32 throw_speed     # Throw speed in m/s (0 to 6.5 m/s)
float32 throw_time      # The time to throw in seconds (0 to 65.5 seconds)
---
bool success   # Was this command received and processed without issue?
string message # Any relevant message to be sent back to the sender