/**
 * geometry-config.js -- AUTO-GENERATED by generate_config.py -- DO NOT EDIT
 *
 * GUI constants from config/hardware_config.yaml and config/protocol_config.yaml.
 * To regenerate: python config/generate_config.py
 */

// ---- CAN bus (protocol_config.yaml -> can_bus) ----

export const CAN_BAUD_RATE = 1000000;
export const CAN_BITS_PER_FRAME_APPROX = 111;

// ---- Stewart platform geometry (hardware_config.yaml -> jugglebot_geometry) ----

export const INITIAL_HEIGHT_MM = 574.3;
export const BASE_RADIUS_MM = 410.0;
export const PLAT_RADIUS_MM = 219.075;
export const LEG_STROKE_MM = 280.0;
export const BALL_JOINT_OFFSET_MM = 0.0;

// Arm / hand structure
export const ARM_RADIUS_MM = 70.0;
export const ARM_HEIGHT_FROM_PLATFORM_MM = 210.25;
export const HAND_STROKE_MM = 355.0;
export const HAND_RADIUS_MM = 35.0;

// Base node positions in the base frame (mm)
export const BASE_NODES_MM = [
    [-385.274, -140.228, 0.0],
    [-314.078, -263.543, 0.0],
    [314.078, -263.543, 0.0],
    [385.274, -140.228, 0.0],
    [71.196, 403.771, 0.0],
    [-71.196, 403.771, 0.0],
];

// Initial platform node positions in the platform frame (mm)
export const INIT_PLAT_NODES_MM = [
    [-197.405, 95.0, 0.0],
    [-16.431, -218.458, 0.0],
    [16.431, -218.458, 0.0],
    [197.405, 95.0, 0.0],
    [180.975, 123.458, 0.0],
    [-180.975, 123.458, 0.0],
];

// Initial leg lengths (mm) — geometry-derived joint-centre-to-joint-centre at STOW
export const INIT_LEG_LENGTHS_MM = [648.419, 648.419, 648.419, 648.419, 648.419, 648.419];

// Init leg lengths WITH ball joint offset added (legacy: offset=0, so equals INIT_LEG_LENGTHS_MM)
export const INIT_LEG_LENGTHS_WITH_OFFSET_MM = [648.419, 648.419, 648.419, 648.419, 648.419, 648.419];

// Per-leg mm-to-revolutions conversion factors
export const MM_TO_REV = [0.01418332, 0.01419076, 0.01408956, 0.01418684, 0.01426801, 0.01424951];

// Motor position limits
export const LEG_MOTOR_MAX_POS_REVS = 4.2;
export const HAND_MOTOR_MAX_POS_REVS = 11.1;

// Ball Butler position relative to base centre (mm).
// Placeholder -- updated dynamically via bb/calibration_result topic.
export const BB_POSITION_MM = [0, -500, 0];

// Hand axis: offset from platform centre along platform normal (mm)
export const HAND_DEPTH_OFFSET_MM = 100.0;

// ---- Jugglebot operational (hardware_config.yaml -> jugglebot_operational) ----

export const DEFAULT_ACTIVE_Z_MM = 170.0;

// ---- Ball Butler geometry (hardware_config.yaml -> ball_butler_geometry) ----

export const BB_YAW_S_OFFSET_MM = -105.65;
export const BB_PITCH_D_OFFSET_MM = 41.0;
export const BB_RELEASE_L_POSITION_MM = 150.0;
export const BB_PITCH_Z_OFFSET_MM = 17.5;

// Ball Butler trajectory
export const BB_HAND_STROKE_MM = 280.0;

// ---- Catching cone (hardware_config.yaml -> catching_cone) ----

export const CC_DELTA_OK_MS = 5.0;
export const CC_DELTA_WARN_MS = 15.0;
export const CC_OFFSET_DISPLAY_LIMIT_MS = 50.0;
export const CC_OFFSET_HISTORY_LEN = 12;

// ---- ODrive state enum (protocol_config.yaml -> odrive.states) ----

export const ODRIVE_STATE = {
    UNDEFINED: 0,
    IDLE: 1,
    STARTUP_SEQUENCE: 2,
    FULL_CALIBRATION: 3,
    MOTOR_CALIBRATION: 4,
    ENCODER_INDEX_SEARCH: 6,
    ENCODER_OFFSET_CALIBRATION: 7,
    CLOSED_LOOP: 8,
    LOCKIN_SPIN: 9,
    ENCODER_DIR_FIND: 10,
    HOMING: 11,
    ENCODER_HALL_POLARITY: 12,
    ENCODER_HALL_PHASE: 13,
};

// ---- Ball Butler states (protocol_config.yaml -> ball_butler.states) ----

export const BB_STATE = {
    BOOT: 0,
    IDLE: 1,
    TRACKING: 2,
    THROWING: 3,
    RELOADING: 4,
    CALIBRATING: 5,
    CHECKING_BALL: 6,
    ERROR: 127,
};

export const BB_STATE_NAMES = {
    0: 'BOOT',
    1: 'IDLE',
    2: 'TRACKING',
    3: 'THROWING',
    4: 'RELOADING',
    5: 'CALIBRATING',
    6: 'CHECKING BALL',
    127: 'ERROR',
};

// ---- Mocap alignment (protocol_config.yaml -> mocap_alignment) ----

export const MOCAP_ALIGNMENT_POS_THRESH_MM = 2000.0;
export const MOCAP_ALIGNMENT_ROT_THRESH_DEG = 180.0;
