# -*- coding: utf-8 -*-
"""Drift test for the generated topic-choreography map.

``ros_ws/docs/choreography.md`` is generated by
``tools/gen_choreography_map.py``.  This test regenerates it into ``tmp_path``
and diffs against the committed copy, so a node that gains, loses or renames a
publisher/subscriber/service/action reddens the suite until the doc is
regenerated.

It also pins the *honesty* properties the map depends on: every name is either
resolved or explicitly marked ``UNRESOLVED(...)``, the "Python-node graph only"
banner is present, and the hand-ownership latch / multi-publisher wires still
carry their contract notes.

The generator is pure ``ast`` — it never imports rclpy — so this file is safe
under the mocked-ROS conftest.
"""

from __future__ import annotations

import ast
import difflib
import functools
import os
import textwrap

import pytest

from tools.gen_choreography_map import (
    HAND_OWNERSHIP_LATCH_TOPICS,
    MULTI_PUBLISHER_TOPICS,
    NOT_LAUNCHED_NODES,
    _CONTRACT_NOTES,
    _NODE_DIR,
    _DEFAULT_OUT,
    generate,
    main,
    scan_nodes,
    scan_file,
)

#: ``_NODE_DIR`` is ``ros_ws/src/jugglebot/jugglebot``; the launch file lives one
#: level up, in the package root.
_LAUNCH_FILE = os.path.join(
    os.path.dirname(_NODE_DIR), 'launch', 'jugglebot_launch.py')


@functools.lru_cache(maxsize=1)
def _scan():
    """Memoised package scan — several tests need it and the walk is ~0.6 s."""
    return tuple(scan_nodes())


def _committed_text():
    with open(_DEFAULT_OUT, 'r', encoding='utf-8') as handle:
        return handle.read()


# ---------------------------------------------------------------------------
# Drift
# ---------------------------------------------------------------------------

def test_committed_doc_matches_regeneration(tmp_path):
    """The committed map equals a fresh generation from the node sources."""
    out = tmp_path / 'choreography.md'
    assert main(['--out', str(out)]) == 0
    fresh = out.read_text(encoding='utf-8')
    committed = _committed_text()

    if fresh != committed:
        diff = '\n'.join(difflib.unified_diff(
            committed.splitlines(), fresh.splitlines(),
            fromfile='committed ros_ws/docs/choreography.md',
            tofile='regenerated', lineterm=''))
        pytest.fail(
            'ros_ws/docs/choreography.md is stale — the node graph changed.\n'
            'Regenerate with: python tools/gen_choreography_map.py\n\n' + diff)


def test_generation_is_deterministic():
    """Two runs produce byte-identical text (stable sort order)."""
    assert generate() == generate()


def test_check_flag_detects_drift(tmp_path):
    stale = tmp_path / 'choreography.md'
    stale.write_text('# not the map\n', encoding='utf-8')
    assert main(['--out', str(stale), '--check']) == 1
    assert main(['--out', str(_DEFAULT_OUT), '--check']) == 0


def test_check_flag_reports_missing_file(tmp_path):
    assert main(['--out', str(tmp_path / 'nope.md'), '--check']) == 1


# ---------------------------------------------------------------------------
# Honesty properties
# ---------------------------------------------------------------------------

def test_banner_present():
    text = _committed_text()
    assert 'Python-node graph only' in text
    assert 'GUI/rosbridge consumers are NOT included' in text


def test_no_endpoint_name_is_silently_guessed():
    """Every unresolved name carries the UNRESOLVED marker and is listed."""
    text = _committed_text()
    unresolved = [e for e in _scan() if e.provenance == 'unresolved']
    for endpoint in unresolved:
        assert endpoint.name.startswith('UNRESOLVED('), endpoint.name
        assert endpoint.name in text
    section = text.split('## Unresolved names', 1)[1]
    if not unresolved:
        assert 'every endpoint name resolved to a literal' in section


def test_parameter_derived_names_are_tagged():
    """A name that came from a ROS-parameter default is marked as such.

    ``trajectory_node`` subscribes to ``str(self.get_parameter('control_mode_topic')
    .value)``.  The map resolves it to the declared default but must say so —
    a launch override would change the real wire.
    """
    endpoints = [e for e in _scan() if e.provenance.startswith('param:')]
    assert endpoints, 'expected at least the control_mode_topic parameter wire'
    text = _committed_text()
    for endpoint in endpoints:
        assert '`' + endpoint.provenance + '`' in text


# ---------------------------------------------------------------------------
# Contract annotations
# ---------------------------------------------------------------------------

def test_multi_publisher_topics_are_annotated():
    """The two by-design multi-publisher topics really have >1 publisher, and say so."""
    text = _committed_text()
    publishers = {}
    for endpoint in _scan():
        if endpoint.kind == 'publisher':
            publishers.setdefault(endpoint.name, set()).add(endpoint.node)

    for name in MULTI_PUBLISHER_TOPICS:
        assert len(publishers.get(name, ())) >= 2, (
            name + ' no longer has multiple publishers — update the contract note')
        assert name in _CONTRACT_NOTES
        assert 'MULTI-PUBLISHER by design' in _CONTRACT_NOTES[name]
        assert '### `' + name + '`' in text


def test_hand_ownership_latch_topics_are_annotated():
    text = _committed_text()
    assert len(HAND_OWNERSHIP_LATCH_TOPICS) == 5
    for index, name in enumerate(HAND_OWNERSHIP_LATCH_TOPICS, start=1):
        note = _CONTRACT_NOTES.get(name)
        assert note is not None, name + ' lost its contract note'
        assert 'HAND-OWNERSHIP LATCH (%d/5)' % index in note
        assert '### `' + name + '`' in text


def _launched_jugglebot_executables():
    """Executables the launch file starts from the ``jugglebot`` package.

    Parsed with ``ast`` rather than imported: importing the launch file pulls
    ``launch``/``launch_ros``, which are not available under the mocked-ROS
    conftest.
    """
    with open(_LAUNCH_FILE, 'r', encoding='utf-8') as handle:
        tree = ast.parse(handle.read(), filename=_LAUNCH_FILE)
    out = set()
    for node in ast.walk(tree):
        if not (isinstance(node, ast.Call)
                and isinstance(node.func, ast.Name) and node.func.id == 'Node'):
            continue
        kwargs = {}
        for keyword in node.keywords:
            if isinstance(keyword.value, ast.Constant):
                kwargs[keyword.arg] = keyword.value.value
        if kwargs.get('package') == 'jugglebot' and kwargs.get('executable'):
            out.add(kwargs['executable'])
    return out


def test_not_launched_nodes_match_launch_file():
    """The ``(not launched)`` tag set is exactly the scanned-minus-launched set.

    Both directions matter and both have bitten this repo's docs before:
    a node that gets re-enabled in the launch file must lose its tag (else the
    map understates the live graph), and a node that gets dropped from the
    launch file must gain one (else the map presents a parked node as a live
    consumer — what Phase 3's dormancy did to eight wires).
    """
    launched = _launched_jugglebot_executables()
    assert launched, 'parsed no jugglebot Node() entries from ' + _LAUNCH_FILE

    scanned = {e.node for e in _scan()}
    assert set(NOT_LAUNCHED_NODES) == scanned - launched, (
        'NOT_LAUNCHED_NODES is stale: scanned=%r launched=%r'
        % (sorted(scanned), sorted(launched)))
    assert not set(NOT_LAUNCHED_NODES) & launched


def test_not_launched_nodes_are_tagged_in_the_doc():
    """Every rendered mention of a parked node carries the marker."""
    text = _committed_text()
    for name in NOT_LAUNCHED_NODES:
        occurrences = text.count('`' + name + '`')
        tagged = text.count('`' + name + '` (not launched)')
        assert occurrences, name + ' does not appear in the map at all'
        # The preamble names both nodes in prose; every graph-line mention is tagged.
        assert tagged >= occurrences - 1, (
            '%s appears untagged in the map (%d mentions, %d tagged)'
            % (name, occurrences, tagged))
    assert 'not launched' in text.split('## Topics', 1)[0], (
        'the preamble must explain the (not launched) tag')


def test_annotated_topics_all_exist_in_the_graph():
    """No contract note points at a wire that no longer exists."""
    names = {e.name for e in _scan()}
    missing = sorted(set(_CONTRACT_NOTES) - names)
    assert not missing, 'contract notes for non-existent endpoints: %r' % (missing,)


# ---------------------------------------------------------------------------
# Resolver behaviour (synthetic sources)
# ---------------------------------------------------------------------------

def _write_node(tmp_path, body, name='fake_node.py'):
    path = tmp_path / name
    path.write_text(textwrap.dedent(body), encoding='utf-8')
    return str(path)


def test_resolves_string_literal(tmp_path):
    path = _write_node(tmp_path, """
        class N:
            def __init__(self):
                self.create_publisher(Bool, 'a/b', 10)
    """)
    (endpoint,) = scan_file(path)
    assert (endpoint.name, endpoint.kind, endpoint.provenance) == ('a/b', 'publisher', 'literal')


def test_resolves_module_constant(tmp_path):
    path = _write_node(tmp_path, """
        TOPIC = 'from/const'
        class N:
            def __init__(self):
                self.create_subscription(Bool, TOPIC, self.cb, 10)
    """)
    (endpoint,) = scan_file(path)
    assert endpoint.name == 'from/const'
    assert endpoint.provenance == 'constant'


def test_attribute_expression_is_refused_not_guessed(tmp_path):
    """``self.X`` must NOT be answered from a same-named module/class constant.

    The index keys constants by BARE name, so looking up ``node.attr`` conflated
    an *instance* attribute with an unrelated module-level constant and reported
    provenance ``constant`` — a confident wrong wire, which is precisely the
    failure the honesty rule exists to prevent.  Resolving this shape correctly
    needs real instance-attribute tracking; until someone does that work the
    resolver refuses, and the hole is visible in the "Unresolved names" section.

    Both sub-cases below silently mis-resolved before 2026-08-01.
    """
    shadowed = _write_node(tmp_path, """
        TOPIC = 'module/level'
        class N:
            def __init__(self):
                self.TOPIC = 'instance/level'
                self.create_publisher(Bool, self.TOPIC, 10)
    """, name='shadowed.py')
    (endpoint,) = scan_file(shadowed)
    assert endpoint.provenance == 'unresolved', endpoint.name
    assert endpoint.name == 'UNRESOLVED(self.TOPIC)'

    classvar = _write_node(tmp_path, """
        class N:
            TOPIC = 'from/classvar'
            def __init__(self):
                self.create_publisher(Bool, self.TOPIC, 10)
    """, name='classvar.py')
    (endpoint,) = scan_file(classvar)
    assert endpoint.provenance == 'unresolved', endpoint.name


def test_nested_function_binding_does_not_leak_to_enclosing_scope(tmp_path):
    """A literal bound only inside a nested ``def`` must not resolve an outer call.

    The local index used to be built with ``ast.walk``, which descends into
    nested functions, so a helper's binding leaked upward and answered a call
    site it never reaches — with provenance ``literal``, i.e. maximum confidence.
    """
    path = _write_node(tmp_path, """
        class N:
            def __init__(self):
                self.create_publisher(Bool, topic, 10)

                def helper():
                    topic = 'inner/only'
                    return topic
    """)
    (endpoint,) = scan_file(path)
    assert endpoint.provenance == 'unresolved', endpoint.name
    assert endpoint.name == 'UNRESOLVED(topic)'


def test_nested_function_keeps_its_own_bindings(tmp_path):
    """The fix must not blind a nested function to its OWN locals."""
    path = _write_node(tmp_path, """
        class N:
            def __init__(self):
                def helper(self):
                    topic = 'inner/own'
                    self.create_publisher(Bool, topic, 10)
    """)
    (endpoint,) = scan_file(path)
    assert (endpoint.name, endpoint.provenance) == ('inner/own', 'literal')


def test_resolves_parameter_default(tmp_path):
    path = _write_node(tmp_path, """
        class N:
            def __init__(self):
                self.declare_parameter('mode_topic', 'control_mode_topic')
                topic = str(self.get_parameter('mode_topic').value)
                self.create_subscription(String, topic, self.cb, 10)
    """)
    (endpoint,) = scan_file(path)
    assert endpoint.name == 'control_mode_topic'
    assert endpoint.provenance == 'param:mode_topic'


def test_rebound_local_is_refused_not_guessed(tmp_path):
    """A local bound to two different literals must not resolve to either.

    The index is flow-INsensitive: it cannot tell which binding reaches the call
    site.  Picking the last one would print a confident, wrong wire — the exact
    failure mode this map is supposed to make impossible.
    """
    path = _write_node(tmp_path, """
        class N:
            def __init__(self):
                topic = 'first/name'
                self.create_publisher(Bool, topic, 10)
                topic = 'second/name'
                self.create_publisher(Bool, topic, 10)
    """)
    endpoints = scan_file(path)
    assert len(endpoints) == 2
    for endpoint in endpoints:
        assert endpoint.provenance == 'unresolved', endpoint.name
        assert endpoint.name.startswith('UNRESOLVED(')


def test_rebound_module_constant_is_refused(tmp_path):
    path = _write_node(tmp_path, """
        TOPIC = 'one'
        TOPIC = 'two'
        class N:
            def __init__(self):
                self.create_publisher(Bool, TOPIC, 10)
    """)
    (endpoint,) = scan_file(path)
    assert endpoint.provenance == 'unresolved'


def test_repeated_identical_binding_still_resolves(tmp_path):
    """Poisoning triggers on DIFFERENT values, not on a harmless repeat."""
    path = _write_node(tmp_path, """
        class N:
            def __init__(self):
                topic = 'same/name'
                self.create_publisher(Bool, topic, 10)
                topic = 'same/name'
                self.create_subscription(Bool, topic, self.cb, 10)
    """)
    endpoints = scan_file(path)
    assert {e.name for e in endpoints} == {'same/name'}
    assert {e.provenance for e in endpoints} == {'literal'}


def test_unresolvable_name_is_marked_not_guessed(tmp_path):
    path = _write_node(tmp_path, """
        class N:
            def __init__(self, cfg):
                self.create_publisher(Bool, cfg.topic_for(self.index), 10)
    """)
    (endpoint,) = scan_file(path)
    assert endpoint.provenance == 'unresolved'
    assert endpoint.name.startswith('UNRESOLVED(')
    assert 'cfg.topic_for' in endpoint.name


def test_action_server_and_client_argument_offsets(tmp_path):
    path = _write_node(tmp_path, """
        class N:
            def __init__(self):
                self._a = ActionServer(self, Reload, 'jugglebot/reload',
                                       execute_callback=self.go)
                self._c = ActionClient(self, Reload, 'jugglebot/reload')
    """)
    endpoints = sorted(scan_file(path), key=lambda e: e.kind)
    assert [(e.kind, e.name, e.msg_type) for e in endpoints] == [
        ('action_client', 'jugglebot/reload', 'Reload'),
        ('action_server', 'jugglebot/reload', 'Reload'),
    ]


def test_scan_covers_modules_without_the_node_suffix(tmp_path):
    """A launched node whose filename lacks ``_node`` must still be mapped.

    ``spacemouse_handler.py`` is exactly that case in the real package, and it
    is the ONLY publisher of ``platform_pose_topic`` — a filename-convention
    scan would have printed that topic as publisher-less.
    """
    _write_node(tmp_path, """
        class N:
            def __init__(self):
                self.create_publisher(Bool, 'from/helper', 10)
    """, name='helper.py')
    (tmp_path / 'notes.md').write_text('not python\n', encoding='utf-8')
    (tmp_path / 'quiet.py').write_text('X = 1\n', encoding='utf-8')

    endpoints = scan_nodes(str(tmp_path))
    assert [(e.node, e.name) for e in endpoints] == [('helper', 'from/helper')]


def test_real_package_includes_spacemouse_handler():
    publishers = {e.node for e in _scan()
                  if e.kind == 'publisher' and e.name == 'platform_pose_topic'}
    assert 'spacemouse_handler' in publishers, (
        'platform_pose_topic lost its publisher — the scan must not be '
        'restricted to *_node.py')


def test_scan_skips_test_and_cache_directories(tmp_path):
    pkg_tests = tmp_path / 'tests'
    pkg_tests.mkdir()
    _write_node(pkg_tests, """
        class N:
            def __init__(self):
                self.create_publisher(Bool, 'from/tests', 10)
    """, name='test_thing.py')
    cache = tmp_path / '__pycache__'
    cache.mkdir()
    (cache / 'stale.py').write_text("x.create_publisher(B, 'from/cache', 1)\n",
                                    encoding='utf-8')
    assert scan_nodes(str(tmp_path)) == []


def test_msg_type_is_resolved_through_imports(tmp_path):
    path = _write_node(tmp_path, """
        from std_msgs.msg import Bool
        class N:
            def __init__(self):
                self.create_publisher(Bool, 'a/b', 10)
    """)
    (endpoint,) = scan_file(path)
    assert endpoint.msg_type == 'std_msgs.msg.Bool'


def test_node_dir_default_points_at_the_package():
    assert os.path.isdir(_NODE_DIR)
    assert any(f.endswith('_node.py') for f in os.listdir(_NODE_DIR))
