#pragma once
// AUTO-GENERATED by generate_config.py — DO NOT EDIT
// Source: config/hardware_config.yaml
//
// Centralised hardware & geometry constants for the Jugglebot system.
// Consumed by: Ball Butler firmware, Platform Teensy firmware, ROS2 (via Python).
// To regenerate: python config/generate_config.py

#include <cstdint>
#include <cmath>

#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif

// ==========================================================================
// Shared Physics
// ==========================================================================

namespace Physics {
  constexpr float GRAVITY_MPS2 = 9.806f;
}

// ==========================================================================
// Platform Dynamics
// ==========================================================================

namespace Dynamics {
  constexpr float PLATFORM_MASS_KG = 1.2f;
  constexpr float PLATFORM_COM_OFFSET_MM[3] = {-9.68f, -68.64f, 52.73f};
  constexpr float PLATFORM_INERTIA_TENSOR_KGMM2_IXX = 16349.8f;
  constexpr float PLATFORM_INERTIA_TENSOR_KGMM2_IXY = -402.572f;
  constexpr float PLATFORM_INERTIA_TENSOR_KGMM2_IXZ = 191.094f;
  constexpr float PLATFORM_INERTIA_TENSOR_KGMM2_IYY = 14987.903f;
  constexpr float PLATFORM_INERTIA_TENSOR_KGMM2_IYZ = 979.411f;
  constexpr float PLATFORM_INERTIA_TENSOR_KGMM2_IZZ = 9298.383f;
  constexpr float MOTOR_ROTOR_INERTIA_KGM2 = 0.000275f;
}

// ==========================================================================
// Jugglebot Stewart Platform Geometry
// ==========================================================================

namespace Geometry {
  constexpr float INITIAL_HEIGHT_MM = 574.3f;
  constexpr float BASE_RADIUS_MM = 410.0f;
  constexpr float PLAT_RADIUS_MM = 219.075f;
  constexpr float BASE_SMALL_ANGLE_DEG = 20.0f;
  constexpr float PLAT_SMALL_ANGLE_DEG = 8.6024446f;
  constexpr float PLAT_X_AXIS_OFFSET_DEG = 154.3012223f;
  constexpr float LEG_STROKE_MM = 280.0f;
  constexpr float ARM_RADIUS_MM = 70.0f;
  constexpr float ARM_HEIGHT_FROM_PLATFORM_MM = 210.25f;
  constexpr float HAND_STROKE_MM = 355.0f;
  constexpr float HAND_RADIUS_MM = 35.0f;
  constexpr float HAND_AXIS_BOTTOM_OFFSET_MM = -129.0f;
  constexpr float BALL_JOINT_OFFSET_MM = 25.5f;
  constexpr float BASE_NODES_MM[6][3] = {
    {-385.274f, -140.228f, 0.0f},
    {-314.078f, -263.543f, 0.0f},
    {314.078f, -263.543f, 0.0f},
    {385.274f, -140.228f, 0.0f},
    {71.196f, 403.771f, 0.0f},
    {-71.196f, 403.771f, 0.0f},
  };
  constexpr float INIT_PLAT_NODES_MM[6][3] = {
    {-197.405f, 95.0f, 0.0f},
    {-16.431f, -218.458f, 0.0f},
    {16.431f, -218.458f, 0.0f},
    {197.405f, 95.0f, 0.0f},
    {180.975f, 123.458f, 0.0f},
    {-180.975f, 123.458f, 0.0f},
  };
  constexpr float INIT_LEG_LENGTHS_MM[6] = {621.389f, 618.16f, 622.074f, 620.653f, 620.652f, 620.091f};
  constexpr float MM_TO_REV[6] = {0.01418332f, 0.01419076f, 0.01408956f, 0.01418684f, 0.01426801f, 0.01424951f};
  constexpr float LEG_MOTOR_MAX_POSITION_REVS = 4.2f;
  constexpr float HAND_MOTOR_MAX_POSITION_REVS = 11.1f;
}

// ==========================================================================
// Jugglebot Homing
// ==========================================================================

namespace Homing {
  constexpr float LEG_SPEED_RPS = 1.5f;
  constexpr float LEG_CURRENT_LIMIT_A = 5.0f;
  constexpr float LEG_CURRENT_HEADROOM_A = 3.0f;
  constexpr float LEG_ABS_POS_REV = 0.1f;
  constexpr float HAND_SPEED_RPS = -3.0f;
  constexpr float HAND_CURRENT_LIMIT_A = 8.0f;
  constexpr float HAND_CURRENT_HEADROOM_A = 3.0f;
  constexpr float HAND_ABS_POS_REV = -0.1f;
  constexpr float EMA_WEIGHT = 0.7f;
  constexpr float MOTOR_TIMEOUT_S = 30.0f;
}

// ==========================================================================
// ODrive Expected Versions
// ==========================================================================

namespace ODriveVer {
  constexpr uint32_t AXIS_0[3] = {4, 4, 58};
  constexpr uint32_t AXIS_1[3] = {4, 4, 58};
  constexpr uint32_t AXIS_2[3] = {4, 4, 58};
  constexpr uint32_t AXIS_3[3] = {4, 4, 58};
  constexpr uint32_t AXIS_4[3] = {4, 4, 58};
  constexpr uint32_t AXIS_5[3] = {4, 4, 58};
  constexpr uint32_t AXIS_6[3] = {4, 4, 58};
  constexpr uint32_t AXIS_7[3] = {6, 2, 0};
  constexpr uint32_t AXIS_8[3] = {5, 2, 0};
}

// ==========================================================================
// Jugglebot ODrive Defaults
// ==========================================================================

namespace ODriveDefaults {
  constexpr float TRAP_VEL_LIMIT_RPS = 15.0f;
  constexpr float TRAP_ACC_LIMIT_RPS2 = 30.0f;
  constexpr float TRAP_DEC_LIMIT_RPS2 = 30.0f;
  constexpr float LEG_VEL_LIMIT_RPS = 4.0f;
  constexpr float LEG_CURR_LIMIT_A = 10.0f;
  constexpr float HAND_VEL_LIMIT_RPS = 1000.0f;
  constexpr float HAND_CURR_LIMIT_A = 50.0f;
  constexpr float HAND_POS_GAIN = 35.0f;
  constexpr float HAND_VEL_GAIN = 0.007f;
  constexpr float HAND_VEL_INT_GAIN = 0.07f;
}

// ==========================================================================
// Jugglebot Operational
// ==========================================================================

namespace JBOp {
  constexpr float DEFAULT_ACTIVE_Z_MM = 170.0f;
  constexpr float HAND_CATCH_PRIME_REV = 9.858f;
  constexpr float TARGET_REACHED_POS_TOL_REV = 0.01f;
  constexpr float TARGET_REACHED_VEL_TOL_RPS = 0.1f;
  constexpr float GENTLE_MOVE_VEL_LIMIT_RPS = 2.5f;
  constexpr float ENCODER_SEARCH_TIMEOUT_S = 3.0f;
  constexpr float GENTLE_MOVE_TIMEOUT_S = 10.0f;
  constexpr float SHUTDOWN_STOW_TIMEOUT_S = 15.0f;
  constexpr float MAX_VALID_TILT_RAD = 0.785f;
  constexpr float INCLINOMETER_OFFSET_DEG[2] = {-0.6f, -0.2f};
  constexpr float LEVELLING_SETTLE_S = 0.5f;
  constexpr float MAX_POSITION_STEP_REV = 0.2f;
  constexpr uint32_t FEASIBILITY_WORKER_MAX_RESTARTS = 3u;
}

// ==========================================================================
// Jugglebot SpaceMouse
// ==========================================================================

namespace Spacemouse {
  constexpr float XY_MULT_MM = 150.0f;
  constexpr float Z_MULT_MM = 140.0f;
  constexpr float PITCH_ROLL_MULT_DEG = 30.0f;
  constexpr float YAW_MULT_DEG = 10.0f;
  constexpr float SMOOTHER_VEL_LIMIT_RPS = 5.0f;
  constexpr float SMOOTHER_ACCEL_LIMIT_RPS2 = 6.0f;
}

// ==========================================================================
// Jugglebot GUI
// ==========================================================================

namespace GUI {
  constexpr float SMOOTHER_VEL_LIMIT_RPS = 5.0f;
  constexpr float SMOOTHER_ACCEL_LIMIT_RPS2 = 6.0f;
}

// ==========================================================================
// Teensy Trajectory
// ==========================================================================

namespace TeensyTraj {
  constexpr float HAND_SPOOL_RADIUS_M = 0.00521f;
  constexpr float LINEAR_GAIN_FACTOR = 1.035f;
  constexpr float INERTIA_HAND_ONLY_KG = 0.281f;
  constexpr float INERTIA_RATIO = 0.747f;
  constexpr float THROW_VEL_HOLD_PCT = 0.05f;
  constexpr float CATCH_VEL_RATIO = 0.6f;
  constexpr float CATCH_VEL_HOLD_PCT = 0.1f;
  constexpr float HAND_STROKE_M = 0.355f;
  constexpr float STROKE_MARGIN_M = 0.02f;
  constexpr float END_PROFILE_HOLD_S = 0.1f;
  constexpr uint32_t SAMPLE_RATE_HZ = 500u;
  constexpr float MAX_SMOOTH_MOVE_HAND_ACCEL_RPS2 = 100.0f;
  constexpr float QUINTIC_S2_MAX = 5.7735027f;
  constexpr float MIN_EVENT_VEL_MPS = 0.3f;
  constexpr float MAX_EVENT_VEL_MPS = 7.0f;
}

// ==========================================================================
// Teensy Operational
// ==========================================================================

namespace TeensyOp {
  constexpr uint32_t REPORT_INTERVAL_MS = 500u;
  constexpr uint32_t SAFETY_GAP_US = 20000u;
  constexpr uint32_t TIME_SYNC_ALPHA_SHIFT = 3u;
}

// ==========================================================================
// Motion Capture
// ==========================================================================

namespace Mocap {
  constexpr const char* QTM_HOST = "192.168.20.16";
  constexpr uint32_t QTM_PORT = 22223u;
}

// ==========================================================================
// Ball Tracking & Prediction
// ==========================================================================

namespace Tracking {
  constexpr float MOCAP_DT_S = 0.005f;
  constexpr float PROCESS_NOISE = 5.0f;
  constexpr float MEASUREMENT_NOISE = 1.0f;
  constexpr float LANDING_THRESHOLD_MM = 20.0f;
  constexpr float IS_PROJECTILE_RESIDUAL_THRESHOLD = 10.0f;
  constexpr float IS_PROJECTILE_A_THRESHOLD_MMPS2 = 400.0f;
  constexpr float BUFFER_DURATION_S = 0.1f;
  constexpr float MATCH_THRESHOLD_BASE_MM = 100.0f;
  constexpr float PENDING_TIMEOUT_S = 5.0f;
  constexpr uint32_t MIN_MATCHES_TO_CONFIRM = 3u;
  constexpr float MIN_HEIGHT_ABOVE_LANDING_MM = 50.0f;
  constexpr uint32_t MAX_FRAMES_WITHOUT_MEASUREMENT = 200u;
}

// ==========================================================================
// Ball Butler Geometry & Kinematics
// ==========================================================================

namespace BBGeom {
  constexpr float YAW_S_OFFSET_MM = -105.65f;
  constexpr float PITCH_D_OFFSET_MM = 41.0f;
  constexpr float RELEASE_L_POSITION_MM = 150.0f;
  constexpr float PITCH_Z_OFFSET_MM = 17.5f;
  constexpr float PITCH_MAX_DEG = 85.0f;
  constexpr float PITCH_MIN_DEG = 12.0f;
  constexpr float YAW_MAX_DEG = 185.0f;
  constexpr float YAW_MIN_DEG = 0.0f;
}

// ==========================================================================
// Ball Butler Trajectory
// ==========================================================================

namespace BBTraj {
  constexpr float HAND_SPOOL_RADIUS_M = 0.0052493f;
  constexpr float LINEAR_GAIN_FACTOR = 1.0f;
  constexpr float INERTIA_HAND_ONLY_KG = 0.281f;
  constexpr float INERTIA_RATIO = 0.747f;
  constexpr float HAND_STROKE_M = 0.28f;
  constexpr float STROKE_MARGIN_M = 0.02f;
  constexpr float THROW_VEL_HOLD_PCT = 0.05f;
  constexpr float CATCH_VEL_RATIO = 0.8f;
  constexpr float CATCH_VEL_HOLD_PCT = 0.1f;
  constexpr float END_PROFILE_HOLD_S = 0.1f;
  constexpr uint32_t SAMPLE_RATE_HZ = 500u;
  constexpr float MAX_SMOOTH_ACCEL_RPS2 = 200.0f;
  constexpr float QUINTIC_S2_MAX = 5.7735027f;
  constexpr float HAND_MAX_SMOOTH_POS_REV = 8.9f;
  constexpr float MAX_THROW_DURATION_S = 2.0f;
  constexpr uint32_t MAX_SMOOTH_SAMPLES = 300u;
  constexpr uint32_t MAX_PAUSE_SAMPLES = 512u;
  constexpr uint32_t TRAJ_ARENA_BYTES = 24576u;
}

// ==========================================================================
// Ball Butler Hardware Pins
// ==========================================================================

namespace BBPins {
  constexpr uint32_t YAW_SPI_CS = 10u;
  constexpr uint32_t YAW_INA1 = 16u;
  constexpr uint32_t YAW_INA2 = 15u;
  constexpr uint32_t YAW_PWM = 14u;
}

// ==========================================================================
// Ball Butler CAN Config
// ==========================================================================

namespace BBCan {
  constexpr uint32_t HEARTBEAT_RATE_MS = 100u;
  constexpr uint32_t AUTO_CLEAR_BRAKE_MS = 500u;
  constexpr uint32_t MAX_NODES = 16u;
  constexpr uint32_t SYNC_STATS_PRINT_MS = 200u;
}

// ==========================================================================
// Ball Butler Yaw Axis
// ==========================================================================

namespace BBYaw {
  constexpr uint32_t ENC_CPR = 60u;
  constexpr float ABS_ENC_CPR = 16384.0f;
  constexpr uint32_t PWM_FREQ_HZ = 20000u;
  constexpr uint32_t PWM_MAX = 255u;
  constexpr uint32_t PWM_DEADZONE_MIN = 60u;
  constexpr float LOOP_HZ = 150.0f;
  constexpr int32_t ENC_DIR = -1;
  constexpr uint32_t MOTOR_DIR = 1u;
  constexpr float KP = 300.0f;
  constexpr float KI = 0.0f;
  constexpr float KD = 0.0f;
  constexpr float FF_PWM = 10.0f;
  constexpr float FF_TAPER_DEG = 5.0f;
  constexpr float POS_TOL_REV = 0.0014f;
  constexpr float ACCEL_PPS = 500.0f;
  constexpr float DECEL_PPS = 450.0f;
  constexpr float LIM_MIN_DEG = 0.0f;
  constexpr float LIM_MAX_DEG = 120.0f;
  constexpr float HARD_LIMIT_OVERSHOOT_DEG = 3.0f;
  constexpr float MAX_SOFT_RANGE_DEG = 355.0f;
  constexpr float VEL_LPF_ALPHA = 0.3f;
  constexpr float MAX_VALID_VEL_RPS = 2.0f;
  constexpr float BOOT_ZERO_OFFSET_DEG = 5.0f;
  constexpr float BOOT_SOFT_LIM_MIN_DEG = -5.0f;
  constexpr float BOOT_SOFT_LIM_MAX_DEG = 190.0f;
  constexpr float BOOT_HARD_LIMIT_OVERSHOOT_DEG = 10.0f;
}

// ==========================================================================
// Ball Butler Pitch Axis
// ==========================================================================

namespace BBPitch {
  constexpr float DEG_MIN = 12.0f;
  constexpr float DEG_MAX = 90.0f;
  constexpr float TRAJ_VEL_RPS = 1.0f;
  constexpr float TRAJ_ACCEL_RPS2 = 0.5f;
  constexpr float TRAJ_DECEL_RPS2 = 0.25f;
}

// ==========================================================================
// Ball Butler Hand Axis
// ==========================================================================

namespace BBHand {
  constexpr int32_t HOMING_DIRECTION = -1;
  constexpr float HOMING_SPEED_RPS = 3.0f;
  constexpr float HOMING_CURRENT_A = 5.0f;
  constexpr float HOMING_HEADROOM_A = 3.0f;
  constexpr float HOMING_ABS_POS_REV = -0.1f;
  constexpr float HOMING_EMA_WEIGHT = 0.7f;
  constexpr uint32_t HOMING_IQ_POLL_MS = 10u;
  constexpr uint32_t HOMING_ATTEMPT_TIMEOUT_MS = 5000u;
  constexpr uint32_t HOMING_MODE_SETTLE_MS = 100u;
  constexpr uint32_t HOMING_STOP_SETTLE_MS = 5u;
  constexpr float OP_VEL_LIMIT_RPS = 1000.0f;
  constexpr float OP_CURRENT_LIMIT_A = 50.0f;
}

// ==========================================================================
// Ball Butler State Machine
// ==========================================================================

namespace BBSM {
  constexpr uint32_t HOMING_TIMEOUT_MS = 20000u;
  constexpr uint32_t HOMING_RETRY_DELAY_MS = 500u;
  constexpr uint32_t RELOAD_TIMEOUT_MS = 20000u;
  constexpr uint32_t POST_THROW_DELAY_MS = 1000u;
  constexpr uint32_t IDLE_NO_CMD_TIMEOUT_MS = 5000u;
  constexpr float RELOAD_HAND_TOP_REV = 8.7f;
  constexpr float RELOAD_PITCH_READY_DEG = 70.0f;
  constexpr float RELOAD_YAW_ANGLE_DEG = 180.0f;
  constexpr float RELOAD_PITCH_GRAB_DEG = 90.0f;
  constexpr float RELOAD_HAND_BOTTOM_REV = 0.0f;
  constexpr float RELOAD_HAND_BOTTOM_TOL_REV = 0.1f;
  constexpr uint32_t RELOAD_HOLD_DELAY_MS = 500u;
  constexpr uint32_t RELOAD_BALL_CHECK_SAMPLES = 5u;
  constexpr uint32_t BALL_CHECK_SAMPLE_INTERVAL_MS = 100u;
  constexpr uint32_t TRACKING_HAND_CHECK_MS = 200u;
  constexpr uint32_t YAW_CMD_INTERVAL_MS = 10u;
  constexpr uint32_t PITCH_CMD_INTERVAL_MS = 50u;
  constexpr uint32_t CHECK_BALL_CONFIRM_SAMPLES = 5u;
  constexpr float CHECK_BALL_DISRUPT_PITCH_DEG = 70.0f;
  constexpr float HAND_REV_HOME = 0.0f;
  constexpr float PITCH_DEG_HOME = 90.0f;
  constexpr float YAW_DEG_HOME = 20.0f;
  constexpr float CALIB_MAX_YAW_DEG = 120.0f;
  constexpr float CALIB_MIN_YAW_DEG = 0.0f;
  constexpr float CALIB_YAW_ACCEL = 50.0f;
  constexpr float CALIB_YAW_DECEL = 50.0f;
  constexpr uint32_t CALIB_PAUSE_MS = 2500u;
  constexpr uint32_t MAX_RELOAD_ATTEMPTS = 3u;
  constexpr uint32_t MAX_HOMING_ATTEMPTS = 3u;
  constexpr uint32_t PITCH_SETTLE_MS = 500u;
  constexpr uint32_t PITCH_GRAB_SETTLE_MS = 1000u;
  constexpr float YAW_ANGLE_THRESHOLD_DEG = 1.0f;
  constexpr uint32_t PITCH_IDLE_DELAY_MS = 500u;
  constexpr uint32_t MIN_MOTION_DURATION_MS = 300u;
  constexpr uint32_t PV_FRESHNESS_US = 20000u;
  constexpr float PITCH_MIN_STOW_DEG = 80.0f;
  constexpr float YAW_MIN_ANGLE_DEG = 5.0f;
  constexpr float YAW_MAX_ANGLE_DEG = 190.0f;
}

// ==========================================================================
// Ball Butler Operational
// ==========================================================================

namespace BBOp {
  constexpr float THROW_VEL_MIN_MPS = 0.05f;
  constexpr float THROW_VEL_MAX_MPS = 6.0f;
  constexpr float SCHEDULE_MARGIN_S = 0.1f;
  constexpr uint32_t YAW_TELEM_MS = 500u;
  constexpr uint32_t SERIAL_BAUD = 115200u;
  constexpr uint32_t SERIAL_WAIT_MS = 2000u;
  constexpr uint32_t ODRIVE_BOOT_MS = 1000u;
  constexpr float MAX_THROW_SPEED_MPS = 5.0f;
  constexpr float MAX_THROW_HEIGHT_M = 0.5f;
  constexpr float THROW_SPEED_MULTIPLIER = 1.0f;
  constexpr float LANDING_TIME_OFFSET_MS = -120.0f;
}

// ==========================================================================
// Ball Butler Heartbeat Encoding
// ==========================================================================

namespace BBHb {
  constexpr float HAND_MAX_MM = 655.36f;
  constexpr float PITCH_CLAMP_MIN_DEG = 0.0f;
  constexpr float PITCH_CLAMP_MAX_DEG = 90.0f;
}

// ==========================================================================
// Ball Butler Ball Detection
// ==========================================================================

namespace BBBallDetect {
  constexpr uint32_t GPIO_PIN = 3u;
  constexpr uint32_t CHECK_INTERVAL_MS = 50u;
  constexpr uint32_t MAX_MISSING_SAMPLES = 5u;
  constexpr uint32_t CHECK_TIMEOUT_MS = 100u;
}
