#!/usr/bin/env python3
"""Score a recorded session's ball-possession verdicts offline — the instrument
behind contract C-POSSESS-1 (``ros_ws/docs/ball_possession_contract.md``).

WHAT IT DOES
------------
Replays every ``/balls`` message in a rosbag through the **production**
possession source (``jugglebot.ball_possession.TrackerArrivalSource``, constructed
exactly as ``reload_coordinator_node`` constructs it) and prints, for every
destination-tagged track that reached ``CAUGHT``:

  * the CAUGHT estimate and the reference point it was judged against;
  * the ARRIVAL error (horizontal) and the REPORT-ONLY plane drop (vertical);
  * the verdict the TRACKER SOURCE alone would return for it.

⚠ **THAT IS NO LONGER THE COORDINATOR'S VERDICT** (owner decision D1,
2026-08-26). Possession is the ball-in-cup sensor's alone; the tracker supplies
report-only ``arrival_err_mm``, and this probe therefore scores the tracker's
CONTRIBUTION, not the machine's answer. For the machine's answer, replay the cup:
``tools/probes/possession_replay.py``. This probe is kept because
``arrival_err_mm`` is still the catch-accuracy number the runbooks score and
because its fixtures (``tests/ros/possession_fixtures.py``) are the corpus the
tracker's split-track behaviour is characterised from.

That turns a capture into the two numbers the hardware runbook's row ``POSS-1``
needs — *how many CAUGHT verdicts the gate minted* and *how many catches the
operator counted by eye* — without re-running the sitting.

WHY IT IS COMMITTED (and not a /tmp one-off)
--------------------------------------------
Three consumers reference it by path, so it must survive a reboot:

  * ``ros_ws/docs/ball_possession_contract.md`` § 6 — the fixture regeneration recipe;
  * ``tests/ros/possession_fixtures.py`` — generated by ``--emit-fixtures``;
  * ``tests/hardware/session_anomaly_fixes.md`` § SECTION POSS, row ``POSS-1`` —
    the analysis command that turns the next sitting's bag into a verdict.

Plan: ``plans/parked/catch-reach-degenerate-overshoot.md`` (follow-on phase B).
Consuming test: ``tests/ros/test_ball_possession.py``.

USAGE
-----
    source ~/Desktop/PDJ_venv/venv/bin/activate

    # score a capture
    python tools/probes/possession_verdict_bag_check.py \
        --bag ~/Desktop/rosbags/2026-07-27_15-39-38

    # regenerate the committed test fixtures from that capture
    python tools/probes/possession_verdict_bag_check.py \
        --bag ~/Desktop/rosbags/2026-07-27_15-39-38 --emit-fixtures

    # instrument acceptance, no bag needed (re-scores the committed fixtures and
    # checks the counts the contract states)
    python tools/probes/possession_verdict_bag_check.py --self-check

Strictly offline and read-only: it opens ``.mcap`` files and nothing else.
Run outputs go to ``temp/probes/`` (timestamped, never clobbering).

THE REFERENCE POINT, and why the probe cannot always know it
------------------------------------------------------------
The coordinator judges a reload against the fixed ACTIVE catch point and a toss
against that goal's NOMINATED landing point. A bag does not carry the live goal,
so ``--ref`` defaults to the ACTIVE catch point for every track. That is exact for
the whole 2026-07-27 CAP-WORK capture — every reload aims at the ACTIVE point by
construction, and all 17 self-tosses were nominated at ``(0, 0)`` (their CAUGHT
estimates all sit within 3.88 mm of it, which a displaced nomination could not
produce). **Pass ``--ref X Y Z`` to score a displaced-catch session** — a
70 mm-displaced 8b catch scored against the default point reads as a 70 mm miss
and would be refused.
"""

from __future__ import annotations

import argparse
import csv
import datetime
import glob
import os
import sys

_HERE = os.path.dirname(os.path.abspath(__file__))
_REPO = os.path.dirname(os.path.dirname(_HERE))
sys.path.insert(0, os.path.join(_REPO, 'ros_ws', 'src', 'jugglebot'))

import jugglebot.hardware_config as hw                      # noqa: E402
from jugglebot.ball_possession import TrackerArrivalSource  # noqa: E402

# The coordinator's own construction, mirrored. Kept as a call rather than a
# copied literal so a geometry change moves both together; --self-check asserts
# the mirror against the node's module constant.
ARRIVAL_TOL_MM = float(hw.GEOM_ARM_RADIUS_MM)
CATCH_POINT_MM = (0.0, 0.0,
                  float(hw.GEOM_INITIAL_HEIGHT_MM)
                  + float(hw.JB_OP_DEFAULT_ACTIVE_Z_MM)
                  + float(hw.HAND_CATCH_OFFSET_MM))

_STATUS_CAUGHT = 2
_FIXTURE_PATH = os.path.join(_REPO, 'tests', 'ros', 'possession_fixtures.py')


def read_caught_tracks(bag_dir, robot_name):
    """-> [(ball_id, t_first_caught, (x, y, z))] for every destination-tagged
    track that reached CAUGHT, in first-seen order.

    ``mcap_ros2`` is imported HERE, not at module scope, so the scoring half can
    be exercised by ``--self-check`` (and by the consuming test) without the bag
    reader installed."""
    try:
        from mcap_ros2.reader import read_ros2_messages
    except ImportError as exc:                                   # pragma: no cover
        sys.exit(f"ERROR: mcap_ros2 not importable ({exc}).\n"
                 "       activate the project venv "
                 "(source ~/Desktop/PDJ_venv/venv/bin/activate)")
    seen = {}
    order = []
    for path in sorted(glob.glob(os.path.join(bag_dir, '*.mcap'))):
        for m in read_ros2_messages(path, topics=['/balls']):
            t = m.log_time_ns * 1e-9
            for b in m.ros_msg.balls:
                if str(b.destination) != robot_name:
                    continue
                if int(b.status) != _STATUS_CAUGHT:
                    continue
                bid = int(b.id)
                if bid in seen:
                    continue
                seen[bid] = (bid, t, (float(b.position.x), float(b.position.y),
                                      float(b.position.z)))
                order.append(bid)
    return [seen[i] for i in order]


def score(tracks, ref_point_mm, tol_mm):
    """-> [(ball_id, xyz, verdict)] using the PRODUCTION source."""
    src = TrackerArrivalSource(arrival_tol_mm=tol_mm)
    return [(bid, xyz, src.judge(ball_xyz_mm=xyz, ref_point_mm=ref_point_mm))
            for bid, _t, xyz in tracks]


def print_table(scored, ref_point_mm, tol_mm):
    print(f'reference point {ref_point_mm} mm; arrival tolerance {tol_mm:.1f} mm')
    print(f'{"id":>5} {"x":>9} {"y":>9} {"z":>9} {"arrival_mm":>11} '
          f'{"plane_drop_mm":>14} {"retention":>10} {"verdict":>10}')
    for bid, xyz, v in scored:
        print(f'{bid:>5} {xyz[0]:9.1f} {xyz[1]:9.1f} {xyz[2]:9.1f} '
              f'{v.arrival_err_mm:11.2f} {v.plane_drop_mm:14.1f} '
              f'{v.retention:>10} '
              f'{"CAUGHT" if v.confirmed else "REFUSED":>10}')
    n_ok = sum(1 for _b, _p, v in scored if v.confirmed)
    print(f'\nCAUGHT {n_ok} / {len(scored)} tagged tracks '
          f'({len(scored) - n_ok} refused)')
    return n_ok


def write_csv(scored, ref_point_mm, tol_mm):
    out_dir = os.path.join(_REPO, 'temp', 'probes')
    os.makedirs(out_dir, exist_ok=True)
    stamp = datetime.datetime.now().strftime('%Y-%m-%d_%H-%M-%S')
    path = os.path.join(out_dir, f'possession_verdicts_{stamp}.csv')
    with open(path, 'w', newline='') as fh:
        w = csv.writer(fh)
        w.writerow(['ball_id', 'x_mm', 'y_mm', 'z_mm', 'arrival_err_mm',
                    'plane_drop_mm', 'retention', 'confirmed',
                    'ref_x', 'ref_y', 'ref_z', 'tol_mm'])
        for bid, xyz, v in scored:
            w.writerow([bid, f'{xyz[0]:.3f}', f'{xyz[1]:.3f}', f'{xyz[2]:.3f}',
                        f'{v.arrival_err_mm:.3f}', f'{v.plane_drop_mm:.3f}',
                        v.retention, int(v.confirmed),
                        *(f'{c:.3f}' for c in ref_point_mm), f'{tol_mm:.3f}'])
    print(f'wrote {path}')
    return path


def emit_fixtures(tracks, bag_dir, split_id):
    """Write ``tests/ros/possession_fixtures.py`` — the measured CAUGHT estimates.

    ``split_id`` separates the two eras in the 2026-07-27 session: ids below it are
    Ball-Butler reload tracks, ids at/above it are self-tosses. The split is a
    property of the capture (the operator ran all reloads, then all tosses), so it
    is passed in rather than inferred."""
    lines = [
        '"""Measured ball-possession fixtures — DO NOT hand-edit.',
        '',
        'Every CAUGHT estimate the ball tracker published for a',
        "``destination='jugglebot'`` track during the 2026-07-27 validation sitting,",
        f'read from ``{bag_dir}``.',
        '',
        'Regenerate with:',
        '    python tools/probes/possession_verdict_bag_check.py \\',
        f'        --bag {bag_dir} --emit-fixtures',
        '',
        'Consumed by tests/ros/test_ball_possession.py. Contract:',
        'ros_ws/docs/ball_possession_contract.md (C-POSSESS-1).',
        '"""',
        '',
        'from __future__ import annotations',
        '',
        '# (ball_id, x_mm, y_mm, z_mm) at the FIRST CAUGHT sample of each track.',
        '',
        '# Ball-Butler reload tracks. Every one is a split track whose Kalman filter is',
        '# fed by the WRONG marker (NOT "got no measurements" — all 18 reach',
        '# tracking=CONFIRMED; corrected 2026-07-28, see the contract\'s section 4), so its',
        '# estimate tracks something that is not the ball. Of the eighteen: THIRTEEN were real catches,',
        '# THREE were eye-confirmed bounce-outs (see BOUNCE_OUT_IDS), and TWO',
        '# (balls 31 and 62) are goals whose BB throw aborted YAW NOT_SETTLED, so no',
        '# ball ever left the Butler. The estimates are indistinguishable across all',
        '# three groups, which is why the honest verdict for all of them is refusal.',
        'RELOAD_CAUGHT = (',
    ]
    for bid, _t, xyz in tracks:
        if bid < split_id:
            lines.append(f'    ({bid}, {xyz[0]:.4f}, {xyz[1]:.4f}, {xyz[2]:.4f}),')
    lines += [
        ')',
        '',
        '# Self-toss tracks. Measurement-driven; every one is a catch the operator',
        '# watched land, and every one was reported MISSED by the pre-2026-07-28 gate.',
        'SELF_TOSS_CAUGHT = (',
    ]
    for bid, _t, xyz in tracks:
        if bid >= split_id:
            lines.append(f'    ({bid}, {xyz[0]:.4f}, {xyz[1]:.4f}, {xyz[2]:.4f}),')
    lines += [
        ')',
        '',
        '# The three eye-confirmed bounce-outs (reload attempts 1-3), operator',
        '# testimony 2026-07-28. They are a SUBSET of RELOAD_CAUGHT: the tracker',
        '# reported CAUGHT for all three.',
        'BOUNCE_OUT_IDS = (6, 9, 11)',
        '',
        '# Where the three bounce-outs actually crossed z = 1050 mm on their way in,',
        '# from the sitting\'s mocap analysis (logbook/2026-07-28-anomaly-fixes-'
        'validation-sitting.md',
        '# "The three drops"). NOT tracker output — this is the ball\'s TRUE arrival,',
        '# i.e. what a FIXED tracker would report, and it is the fixture that pins the',
        '# trap: all three entered the cup region at small xy before departing.',
        'BOUNCE_OUT_TRUE_ARRIVAL_XY_MM = (',
        '    (6, -7.2, 16.1),',
        '    (9, -18.8, 3.6),',
        '    (11, -21.5, 7.4),',
        ')',
        '',
        '# The 2026-07-23 corrupt track quoted in the original gate comment, kept as a',
        '# second-session negative so the fixture set is not single-capture.',
        'CORRUPT_2026_07_23 = (-539.0, -323.0, -532.0)',
        '',
    ]
    with open(_FIXTURE_PATH, 'w') as fh:
        fh.write('\n'.join(lines))
    print(f'wrote {_FIXTURE_PATH} '
          f'({sum(1 for b, _t, _x in tracks if b < split_id)} reload, '
          f'{sum(1 for b, _t, _x in tracks if b >= split_id)} self-toss)')


def self_check():
    """Two-sided instrument acceptance, no bag required.

    Checks the ACCEPT side (real catches must be confirmed), the REFUSE side
    (corrupt tracks must not be), the mirror against the node's own constant, and
    the retention pin — the four ways this instrument could silently mis-score a
    capture."""
    sys.path.insert(0, _REPO)
    from tests.ros import possession_fixtures as fx
    from jugglebot.ball_possession import RETENTION_UNKNOWN

    failures = []
    src = TrackerArrivalSource(arrival_tol_mm=ARRIVAL_TOL_MM)

    def check(name, cond, detail=''):
        print(f'  {"PASS" if cond else "FAIL"}  {name}{" — " + detail if detail else ""}')
        if not cond:
            failures.append(name)

    toss = [src.judge(ball_xyz_mm=(x, y, z), ref_point_mm=CATCH_POINT_MM)
            for _i, x, y, z in fx.SELF_TOSS_CAUGHT]
    reload_ = [src.judge(ball_xyz_mm=(x, y, z), ref_point_mm=CATCH_POINT_MM)
               for _i, x, y, z in fx.RELOAD_CAUGHT]
    errs_t = [v.arrival_err_mm for v in toss]
    errs_r = [v.arrival_err_mm for v in reload_]

    print('SELF-CHECK: possession_verdict_bag_check')
    check('1. ACCEPT side: every self-toss catch is confirmed',
          all(v.confirmed for v in toss),
          f'{sum(v.confirmed for v in toss)}/{len(toss)}')
    check('2. REFUSE side: no reload split track is confirmed',
          not any(v.confirmed for v in reload_),
          f'{sum(v.confirmed for v in reload_)}/{len(reload_)} confirmed')
    check('3. the two populations are separated by >10x',
          errs_t and errs_r and min(errs_r) > 10.0 * max(errs_t),
          f'max clean {max(errs_t):.2f} mm vs min corrupt {min(errs_r):.1f} mm')
    check('4. the bound sits strictly between them',
          errs_t and errs_r and max(errs_t) < ARRIVAL_TOL_MM < min(errs_r),
          f'{max(errs_t):.2f} < {ARRIVAL_TOL_MM:.1f} < {min(errs_r):.1f}')
    check('5. retention is never claimed by this source',
          all(v.retention == RETENTION_UNKNOWN for v in toss + reload_))
    check('6. the 2026-07-23 corrupt track is still refused',
          not src.judge(ball_xyz_mm=fx.CORRUPT_2026_07_23,
                        ref_point_mm=CATCH_POINT_MM).confirmed)
    from jugglebot import reload_coordinator_node as rcn
    check('7. probe mirrors the coordinator tolerance',
          abs(rcn._CAUGHT_MAX_XY_ERROR_MM - ARRIVAL_TOL_MM) < 1e-9,
          f'node {rcn._CAUGHT_MAX_XY_ERROR_MM} vs probe {ARRIVAL_TOL_MM}')
    check('8. probe mirrors the coordinator catch point',
          all(abs(a - b) < 1e-6 for a, b in zip(
              CATCH_POINT_MM,
              rcn.compute_catch_point_mm(
                  hw.GEOM_INITIAL_HEIGHT_MM, hw.JB_OP_DEFAULT_ACTIVE_Z_MM,
                  landing_z_offset_mm=hw.HAND_CATCH_OFFSET_MM))))

    n = 8
    print(f'SELF-CHECK: {"PASS" if not failures else "FAIL"} '
          f'{n - len(failures)}/{n}')
    return 0 if not failures else 1


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.split('\n')[0])
    ap.add_argument('--bag', help='rosbag directory containing *.mcap')
    ap.add_argument('--robot', default='jugglebot',
                    help="destination filter (default 'jugglebot')")
    ap.add_argument('--ref', nargs=3, type=float, metavar=('X', 'Y', 'Z'),
                    help='reference point mm (default: the ACTIVE catch point)')
    ap.add_argument('--tol', type=float, default=ARRIVAL_TOL_MM,
                    help=f'arrival tolerance mm (default {ARRIVAL_TOL_MM})')
    ap.add_argument('--emit-fixtures', action='store_true',
                    help='regenerate tests/ros/possession_fixtures.py')
    ap.add_argument('--fixture-split-id', type=int, default=80,
                    help='first self-toss ball id (2026-07-27 session: 80)')
    ap.add_argument('--self-check', action='store_true',
                    help='instrument acceptance; no bag required')
    args = ap.parse_args(argv)

    if args.self_check:
        return self_check()
    if not args.bag:
        ap.error('--bag is required (or use --self-check)')

    bag = os.path.expanduser(args.bag)
    ref = tuple(args.ref) if args.ref else CATCH_POINT_MM
    tracks = read_caught_tracks(bag, args.robot)
    if not tracks:
        print(f'no CAUGHT tracks with destination={args.robot!r} in {bag}')
        return 1
    scored = score(tracks, ref, args.tol)
    print_table(scored, ref, args.tol)
    write_csv(scored, ref, args.tol)
    if args.emit_fixtures:
        emit_fixtures(tracks, bag, args.fixture_split_id)
    return 0


if __name__ == '__main__':
    sys.exit(main())
