"""
AUTO-GENERATED by config/generate_udp_protocol.py — DO NOT EDIT
Jetson <-> can-bridge Teensy UDP wire protocol (Python side).
See docs/teensy-udp-protocol.md. To regenerate: python config/generate_udp_protocol.py
"""
from __future__ import annotations
import struct
from dataclasses import dataclass, field
from enum import IntEnum

# ── Constants ──────────────────────────────────────────────────────────
PROTOCOL_VERSION = 4  # Bumped on any incompatible wire change
MAGIC = 19010  # "JB" little-endian preamble (bytes 0x42 0x4A)
HEADER_SIZE = 8  # Bytes before payload
CRC_SIZE = 2  # Trailing CRC-16 bytes
MAX_PAYLOAD = 1024  # Largest payload we will encode/accept
MAX_FRAME = 1034  # HEADER_SIZE + MAX_PAYLOAD + CRC_SIZE
PORT_STREAM = 5005  # High-rate push: setpoint dn, telem/diag/profile/heartbeat up
PORT_RPC = 5006  # Request/response with retry-on-timeout
TEENSY_IP_0 = 192  # Static Teensy IP octet 0 (192.168.42.2)
TEENSY_IP_1 = 168
TEENSY_IP_2 = 42
TEENSY_IP_3 = 2
JETSON_IP_3 = 1  # Static Jetson teensy-link IP octet 3 (192.168.42.1)
NUM_LEGS = 6  # Leg ODrive axes 0..5
NUM_AXES = 7  # Legs + hand (cache + telemetry breadth)
PROFILE_NUM_TASKS = 9  # Task slots reported in the profiling frame
HEARTBEAT_HZ = 10  # Both-direction liveness rate
LINK_LOST_MISSES = 5  # Missed heartbeats before declaring link lost
HEARTBEAT_TORQUE_CLAMP_SHIFT = 8  # Bit offset of TORQUE_CLAMP_MASK inside HeartbeatT2J.flags (bits 8-13)
HEARTBEAT_CONE_HEALTH_SHIFT = 4  # Bit offset of CONE_HEALTH_MASK inside HeartbeatT2J.flags (bits 4-5)

# ── Enums ──────────────────────────────────────────────────────────────
class MsgType(IntEnum):
    SETPOINT = 1  # 40 Hz MPC setpoint waypoints (STREAM, J→T)
    HEARTBEAT_J2T = 2  # Jetson liveness (STREAM, J→T)
    RPC_REQUEST = 16  # RPC request (RPC port, J→T)
    TELEMETRY = 129  # 100 Hz motor state (STREAM, T→J)
    DIAGNOSTIC = 130  # On-change per-axis diagnostics (STREAM, T→J)
    HEARTBEAT_T2J = 131  # Teensy liveness + link/bus health (STREAM, T→J)
    PROFILE = 132  # 1 Hz profiling/instrumentation (STREAM, T→J)
    CONE_FRAME = 133  # Catching-cone CAN2 frame relay (STREAM, T→J)
    BB_AXIS_ESTIMATES = 134  # Ball Butler pitch/hand ODrive pos+vel estimates (STREAM, T→J)
    CMD_RESULT = 135  # Ball Butler command-outcome CAN1 frame relay (STREAM, T→J)
    LEG_CMD = 136  # Teensy commanded leg interp output @100Hz (STREAM, T→J) — float32 interp residual check
    PLATFORM_FRAME = 137  # Verbatim Platform-Teensy relay-reply uplink (STREAM, T→J)
    HAND_CMD_ECHO = 138  # Hand command-echo telemetry (STREAM, T→J)
    HAND_SENSOR = 139  # Hand ball-present sensor state (STREAM, T→J)
    CAN_ERRORS = 140  # 1 Hz CAN3 wire-error + fault-confinement counters (STREAM, T→J)
    RPC_RESPONSE = 144  # RPC response (RPC port, T→J)

class RpcMethod(IntEnum):
    NOP = 0  # No-op (link test)
    TIME_OF_DAY_QUERY = 1  # Wall-clock bootstrap + drift resync (time-sync master)
    SET_AXIS_STATE = 16  # ODrive set_requested_state
    SET_CONTROLLER_MODE = 17  # ODrive set_controller_mode
    SET_VEL_CURR_LIMITS = 18  # ODrive set_vel_curr_limits
    SET_POS_GAIN = 19  # ODrive set_pos_gain
    SET_VEL_GAINS = 20  # ODrive set_vel_gains
    CLEAR_ERRORS = 21  # ODrive clear_errors
    REBOOT_ODRIVES = 22  # ODrive reboot
    SET_ABSOLUTE_POSITION = 23  # ODrive set_absolute_position (post-homing)
    ENCODER_SEARCH = 32  # Run encoder index search (firmware stub — returns ERR_NOT_IMPL)
    HOME = 33  # Run homing (firmware stub — returns ERR_NOT_IMPL)
    ACTIVATE = 34  # Run TRAP_TRAJ move to the active pose
    DEACTIVATE = 35  # Run TRAP_TRAJ move to the STOW pose, then IDLE
    SDO_READ = 48  # Arbitrary parameter read
    SDO_WRITE = 49  # Arbitrary parameter write
    BB_THROW = 64  # Ball Butler: send THROW_CMD on CAN1 (typed, validated)
    BB_RELOAD = 65  # Ball Butler: send RELOAD_CMD on CAN1 (no payload)
    BB_RESET = 66  # Ball Butler: send RESET_CMD on CAN1 (no payload)
    BB_CALIBRATE_LOC = 67  # Ball Butler: send CALIBRATE_LOC_CMD on CAN1 (no payload)
    GET_AXIS_VERSIONS = 80  # Pull cached raw Get_Version bytes + received bitmask
    TILT_READ = 81  # Relay: read Platform-Teensy inclinometer tilt
    STATE_READ = 82  # Relay: read Platform-Teensy RobotState (is_homed/level/pose)
    STATE_WRITE = 83  # Relay: write Platform-Teensy RobotState (read-modify-write via cache)
    HAND_TRAJ_CMD = 84  # Hand traj + smooth-move (byte-0 discriminator → 0x6D0)

class RpcStatus(IntEnum):
    OK = 0  # Success
    ERR_UNKNOWN_METHOD = 1  # Method id not recognised
    ERR_BAD_ARGS = 2  # Argument decode failed / wrong length
    ERR_BUS_DOWN = 3  # Refused: CAN bus is down (never command a dead bus)
    ERR_TIMEOUT = 4  # Downstream CAN op timed out
    ERR_REJECTED = 5  # Refused by a safety gate
    ERR_NOT_IMPL = 6  # Method not implemented in this firmware revision

class LinkState(IntEnum):
    INIT = 0  # Ethernet up, no Jetson heartbeat yet
    UP = 1  # Healthy bidirectional link
    DEGRADED = 2  # Some missed heartbeats, not yet lost
    LOST = 3  # Link lost → legs to safe behaviour

class BusHealth(IntEnum):
    UNKNOWN = 0  # No frames seen yet
    OK = 1  # Frames flowing, no error frames
    WARN = 2  # Error counters rising
    BUS_OFF = 3  # Controller bus-off

class FaultState(IntEnum):
    NONE = 0  # Nominal
    MPC_STALE = 1  # MPC setpoint older than staleness threshold → E-STOP
    LINK_LOST = 2  # Jetson link lost → safe behaviour on legs
    MOTOR_OVERSPEED = 3  # A leg exceeded the overspeed limit
    MAX_DEVIATION = 4  # Commanded pos diverged too far from encoder
    ODRIVE_FATAL = 5  # Active ODrive error / disarm-while-closed-loop
    CAN_BUS_DOWN = 6  # CAN3 (leg bus) down — hold, deferred stow armed
    MOTOR_FB_STALE = 7  # Leg encoder feedback stale → suppress output (recoverable)

class GuardMode(IntEnum):
    DISABLED = 0
    ENABLED = 1
    ESTOP = 2

class HandSensorFlags(IntEnum):
    RAW_HELD = 1  # bit0: raw per-sample bit (active-low decoded)
    DEBOUNCED_HELD = 2  # bit1: debounced verdict
    VALID = 4  # bit2: not UNKNOWN (fresh, gated good reply)
    STALE = 8  # bit3: no good reply within the staleness window
    TIME_SYNCED = 16  # bit4: bridge wall anchor set at the reply

class HeartbeatT2JFlags(IntEnum):
    TIME_SYNCED = 1  # bit0: Teensy clock synced to the Jetson anchor
    STOW_PENDING_ON_RECONNECT = 2  # bit1: deferred-stow latch armed (awaiting confirmed CAN3 reconnect)
    ALL_AXIS_HEARTBEATS_OK = 4  # bit2: every present axis heartbeat is fresh
    MPC_ACTIVE = 8  # bit3: firmware-side mpc_active (lets a setpoint source verify its arm took)
    CONE_HEALTH_MASK = 48  # bits 4-5: cone (CAN2) BusHealth (UNKNOWN=0/OK=1/WARN=2/BUS_OFF=3) << HEARTBEAT_CONE_HEALTH_SHIFT; reads 0 = UNKNOWN from a pre-cone-uplink flash
    TORQUE_CLAMP_MASK = 16128  # bits 8-13: bit (8+i) set = leg i's |torque_ff| was clamped to TORQUE_FF_FIRMWARE_CLAMP_WIRE_NM at UDP ingest on the last ACCEPTED setpoint frame (mirrors lead_clamp_mask; leg_interp.cpp interp_on_setpoint)

# ── Decode errors ──────────────────────────────────────────────────────
class CrcError(ValueError):
    """decode_frame() raised this on a CRC-16 mismatch (a corrupted frame).

    Subclasses ValueError so existing ``except ValueError`` handlers still
    catch it; callers that must distinguish a corrupted frame (bad CRC) from
    a structurally-malformed one (bad magic/version/length) catch CrcError
    specifically. See controller/teensy_link/client.py's RX decode path,
    which counts crc_errors vs decode_errors off this distinction.
    """

# ── CRC-16/CCITT-FALSE ─────────────────────────────────────────────────
def crc16_ccitt(data: bytes) -> int:
    crc = 0xFFFF
    for b in data:
        crc ^= b << 8
        for _ in range(8):
            crc = ((crc << 1) ^ 0x1021) & 0xFFFF if (crc & 0x8000) else (crc << 1) & 0xFFFF
    return crc & 0xFFFF

# ── Frame header ───────────────────────────────────────────────────────
_HEADER_FMT = "<HBBHH"  # magic, version, msg_type, seq, length
assert struct.calcsize(_HEADER_FMT) == HEADER_SIZE

def encode_frame(msg_type: int, seq: int, payload: bytes) -> bytes:
    """Build a full wire frame: header + payload + CRC-16."""
    if len(payload) > MAX_PAYLOAD:
        raise ValueError(f"payload {len(payload)} > MAX_PAYLOAD {MAX_PAYLOAD}")
    head = struct.pack(_HEADER_FMT, MAGIC, PROTOCOL_VERSION, msg_type,
                       seq & 0xFFFF, len(payload))
    body = head + payload
    crc = crc16_ccitt(body)
    return body + struct.pack('<H', crc)

def decode_frame(frame: bytes):
    """Validate + parse a wire frame. Returns (msg_type, seq, payload).

    Raises ValueError on bad magic/version/length/CRC.
    """
    if len(frame) < HEADER_SIZE + CRC_SIZE:
        raise ValueError("frame too short")
    magic, version, msg_type, seq, length = struct.unpack_from(_HEADER_FMT, frame, 0)
    if magic != MAGIC:
        raise ValueError(f"bad magic 0x{magic:04X}")
    if version != PROTOCOL_VERSION:
        raise ValueError(f"bad version {version}")
    if HEADER_SIZE + length + CRC_SIZE != len(frame):
        raise ValueError(f"length {length} inconsistent with frame {len(frame)}")
    want = crc16_ccitt(frame[:HEADER_SIZE + length])
    got = struct.unpack_from('<H', frame, HEADER_SIZE + length)[0]
    if want != got:
        raise CrcError(f"CRC mismatch want 0x{want:04X} got 0x{got:04X}")
    payload = frame[HEADER_SIZE:HEADER_SIZE + length]
    return msg_type, seq, payload

# ── Payload structs ────────────────────────────────────────────────────
# Setpoint: 40 Hz MPC setpoint waypoints. Carries motor-rev-space quantities (Jugglebot convention: positive = leg extension) exactly as motor_guard's interpolator consumes them. The Jetson bridge does the same mm→rev / pose conversions motor_guard does today; the Teensy interpolator works purely in rev-space. `u1`/`u2` presence is signalled by the flags bits (NOT NaN sentinels).
SETPOINT_FMT = '<ffffffffffffffffffffffffffffffffffffIQ'
SETPOINT_SIZE = 156
_SETPOINT_STRUCT = struct.Struct(SETPOINT_FMT)
assert _SETPOINT_STRUCT.size == 156

@dataclass
class Setpoint:
    u0: tuple = field(default_factory=lambda: (0.0,) * 6)
    u1: tuple = field(default_factory=lambda: (0.0,) * 6)
    u2: tuple = field(default_factory=lambda: (0.0,) * 6)
    v0: tuple = field(default_factory=lambda: (0.0,) * 6)
    accel: tuple = field(default_factory=lambda: (0.0,) * 6)
    torque_ff: tuple = field(default_factory=lambda: (0.0,) * 6)
    flags: int = 0
    t_origin_us: int = 0

    def pack(self) -> bytes:
        return _SETPOINT_STRUCT.pack(*self.u0, *self.u1, *self.u2, *self.v0, *self.accel, *self.torque_ff, self.flags, self.t_origin_us)

    @classmethod
    def unpack(cls, data: bytes) -> 'Setpoint':
        vals = _SETPOINT_STRUCT.unpack(data[:156])
        it = iter(vals)
        return cls(tuple(next(it) for _ in range(6)), tuple(next(it) for _ in range(6)), tuple(next(it) for _ in range(6)), tuple(next(it) for _ in range(6)), tuple(next(it) for _ in range(6)), tuple(next(it) for _ in range(6)), next(it), next(it))

# HeartbeatJ2T: Jetson → Teensy liveness, ~10 Hz.
HEARTBEAT_J2T_FMT = '<QI'
HEARTBEAT_J2T_SIZE = 12
_HEARTBEAT_J2T_STRUCT = struct.Struct(HEARTBEAT_J2T_FMT)
assert _HEARTBEAT_J2T_STRUCT.size == 12

@dataclass
class HeartbeatJ2T:
    t_jetson_us: int = 0
    flags: int = 0

    def pack(self) -> bytes:
        return _HEARTBEAT_J2T_STRUCT.pack(self.t_jetson_us, self.flags)

    @classmethod
    def unpack(cls, data: bytes) -> 'HeartbeatJ2T':
        vals = _HEARTBEAT_J2T_STRUCT.unpack(data[:12])
        it = iter(vals)
        return cls(next(it), next(it))

# Telemetry: 100 Hz motor state for all axes (legs + hand). pos/vel are in the Jugglebot convention (positive = extension), already sign-corrected from the ODrive convention.
TELEMETRY_FMT = '<Qffffffffffffff'
TELEMETRY_SIZE = 64
_TELEMETRY_STRUCT = struct.Struct(TELEMETRY_FMT)
assert _TELEMETRY_STRUCT.size == 64

@dataclass
class Telemetry:
    t_teensy_us: int = 0
    pos_rev: tuple = field(default_factory=lambda: (0.0,) * 7)
    vel_rps: tuple = field(default_factory=lambda: (0.0,) * 7)

    def pack(self) -> bytes:
        return _TELEMETRY_STRUCT.pack(self.t_teensy_us, *self.pos_rev, *self.vel_rps)

    @classmethod
    def unpack(cls, data: bytes) -> 'Telemetry':
        vals = _TELEMETRY_STRUCT.unpack(data[:64])
        it = iter(vals)
        return cls(next(it), tuple(next(it) for _ in range(7)), tuple(next(it) for _ in range(7)))

# Diagnostic: Per-axis diagnostics, published on-change (delta over threshold) OR on a 1 Hz heartbeat. One axis per frame.
DIAGNOSTIC_FMT = '<BBBBBBBBIIffffff'
DIAGNOSTIC_SIZE = 40
_DIAGNOSTIC_STRUCT = struct.Struct(DIAGNOSTIC_FMT)
assert _DIAGNOSTIC_STRUCT.size == 40

@dataclass
class Diagnostic:
    axis_id: int = 0
    axis_state: int = 0
    ctrl_mode: int = 0
    input_mode: int = 0
    flags: int = 0
    homing_result: int = 0
    pad: tuple = field(default_factory=lambda: (0,) * 2)
    active_errors: int = 0
    disarm_reason: int = 0
    iq_setpoint: float = 0.0
    iq_measured: float = 0.0
    temp_fet: float = 0.0
    temp_motor: float = 0.0
    bus_voltage: float = 0.0
    bus_current: float = 0.0

    def pack(self) -> bytes:
        return _DIAGNOSTIC_STRUCT.pack(self.axis_id, self.axis_state, self.ctrl_mode, self.input_mode, self.flags, self.homing_result, *self.pad, self.active_errors, self.disarm_reason, self.iq_setpoint, self.iq_measured, self.temp_fet, self.temp_motor, self.bus_voltage, self.bus_current)

    @classmethod
    def unpack(cls, data: bytes) -> 'Diagnostic':
        vals = _DIAGNOSTIC_STRUCT.unpack(data[:40])
        it = iter(vals)
        return cls(next(it), next(it), next(it), next(it), next(it), next(it), tuple(next(it) for _ in range(2)), next(it), next(it), next(it), next(it), next(it), next(it), next(it), next(it))

# HeartbeatT2J: Teensy → Jetson liveness + link/bus health, ~10 Hz.
HEARTBEAT_T2J_FMT = '<QBBBBIIBBBfffffffffBBfff'
HEARTBEAT_T2J_SIZE = 73
_HEARTBEAT_T2J_STRUCT = struct.Struct(HEARTBEAT_T2J_FMT)
assert _HEARTBEAT_T2J_STRUCT.size == 73

@dataclass
class HeartbeatT2J:
    t_teensy_us: int = 0
    link_state: int = 0
    bus1_health: int = 0
    bus2_health: int = 0
    fault_state: int = 0
    flags: int = 0
    uptime_ms: int = 0
    bb_state: int = 0
    bb_state_data: int = 0
    bb_flags: int = 0
    bb_yaw_deg: float = 0.0
    bb_pitch_deg: float = 0.0
    bb_hand_mm: float = 0.0
    live_deviation: tuple = field(default_factory=lambda: (0.0,) * 6)
    lead_clamp_mask: int = 0
    max_dev_leg: int = 0
    max_dev_value: float = 0.0
    max_dev_u0: float = 0.0
    max_dev_enc: float = 0.0

    def pack(self) -> bytes:
        return _HEARTBEAT_T2J_STRUCT.pack(self.t_teensy_us, self.link_state, self.bus1_health, self.bus2_health, self.fault_state, self.flags, self.uptime_ms, self.bb_state, self.bb_state_data, self.bb_flags, self.bb_yaw_deg, self.bb_pitch_deg, self.bb_hand_mm, *self.live_deviation, self.lead_clamp_mask, self.max_dev_leg, self.max_dev_value, self.max_dev_u0, self.max_dev_enc)

    @classmethod
    def unpack(cls, data: bytes) -> 'HeartbeatT2J':
        vals = _HEARTBEAT_T2J_STRUCT.unpack(data[:73])
        it = iter(vals)
        return cls(next(it), next(it), next(it), next(it), next(it), next(it), next(it), next(it), next(it), next(it), next(it), next(it), next(it), tuple(next(it) for _ in range(6)), next(it), next(it), next(it), next(it), next(it))

# Profile: 1 Hz firmware instrumentation. Per-task CPU%, CAN bus utilisation, UDP round-trip/jitter, the 500 Hz interp deadline-miss counter, and free heap. Consumed by tools/probes/teensy_link_profiling/jetson.
PROFILE_FMT = '<QHHHHHHHHHIIIIHHIIIII'
PROFILE_SIZE = 66
_PROFILE_STRUCT = struct.Struct(PROFILE_FMT)
assert _PROFILE_STRUCT.size == 66

@dataclass
class Profile:
    t_teensy_us: int = 0
    cpu_pct_x100: tuple = field(default_factory=lambda: (0,) * 9)
    can1_rx: int = 0
    can1_tx: int = 0
    can2_rx: int = 0
    can2_tx: int = 0
    can1_util_x100: int = 0
    can2_util_x100: int = 0
    udp_rtt_us: int = 0
    udp_jitter_us: int = 0
    interp_deadline_misses: int = 0
    interp_max_jitter_us: int = 0
    free_heap_bytes: int = 0

    def pack(self) -> bytes:
        return _PROFILE_STRUCT.pack(self.t_teensy_us, *self.cpu_pct_x100, self.can1_rx, self.can1_tx, self.can2_rx, self.can2_tx, self.can1_util_x100, self.can2_util_x100, self.udp_rtt_us, self.udp_jitter_us, self.interp_deadline_misses, self.interp_max_jitter_us, self.free_heap_bytes)

    @classmethod
    def unpack(cls, data: bytes) -> 'Profile':
        vals = _PROFILE_STRUCT.unpack(data[:66])
        it = iter(vals)
        return cls(next(it), tuple(next(it) for _ in range(9)), next(it), next(it), next(it), next(it), next(it), next(it), next(it), next(it), next(it), next(it), next(it))

# ConeFrame: Catching-cone CAN2 frame relay. The can-bridge forwards every frame received on the cone bus verbatim — CATCH_EVENT (0x7E0) and CONE_HEARTBEAT (0x7E1) today — so the Jetson reuses the tested jugglebot.can.catching_cone decoders unchanged and future cone frames flow without a wire change. The cone's microsecond impact timestamp travels INSIDE `data` (it is latched in the cone's piezo ISR); `t_bridge_us` only stamps bridge-side CAN RX for latency/diagnostic checks.
CONE_FRAME_FMT = '<QIBBBBBBBBB'
CONE_FRAME_SIZE = 21
_CONE_FRAME_STRUCT = struct.Struct(CONE_FRAME_FMT)
assert _CONE_FRAME_STRUCT.size == 21

@dataclass
class ConeFrame:
    t_bridge_us: int = 0
    can_id: int = 0
    dlc: int = 0
    data: tuple = field(default_factory=lambda: (0,) * 8)

    def pack(self) -> bytes:
        return _CONE_FRAME_STRUCT.pack(self.t_bridge_us, self.can_id, self.dlc, *self.data)

    @classmethod
    def unpack(cls, data: bytes) -> 'ConeFrame':
        vals = _CONE_FRAME_STRUCT.unpack(data[:21])
        it = iter(vals)
        return cls(next(it), next(it), next(it), tuple(next(it) for _ in range(8)))

# CmdResultFrame: Ball Butler command-outcome relay (the loud outcome channel). The can-bridge forwards the BB CMD_RESULT CAN1 frame (0x7D5) verbatim so the host learns the firmware's terminal outcome of an operator command (throw today; reload/calibrate/home later) instead of only the bridge-side RPC ack. The decoded payload lives INSIDE `data`: byte0=command_type, byte1=command_outcome (shared base 0x00-0x0F + per-command extension >=0x20), bytes2-3=detail0 (int16 LE), bytes4-5=detail1 (int16 LE). `t_bridge_us` only stamps bridge-side CAN1 RX for latency/diagnostic checks.
CMD_RESULT_FRAME_FMT = '<QIBBBBBBBBB'
CMD_RESULT_FRAME_SIZE = 21
_CMD_RESULT_FRAME_STRUCT = struct.Struct(CMD_RESULT_FRAME_FMT)
assert _CMD_RESULT_FRAME_STRUCT.size == 21

@dataclass
class CmdResultFrame:
    t_bridge_us: int = 0
    can_id: int = 0
    dlc: int = 0
    data: tuple = field(default_factory=lambda: (0,) * 8)

    def pack(self) -> bytes:
        return _CMD_RESULT_FRAME_STRUCT.pack(self.t_bridge_us, self.can_id, self.dlc, *self.data)

    @classmethod
    def unpack(cls, data: bytes) -> 'CmdResultFrame':
        vals = _CMD_RESULT_FRAME_STRUCT.unpack(data[:21])
        it = iter(vals)
        return cls(next(it), next(it), next(it), tuple(next(it) for _ in range(8)))

# BbAxisEstimates: High-rate Ball Butler pitch(node 7)/hand(node 8) ODrive encoder estimates, forwarded for during-throw diagnostics (launch angle vs commanded pitch; hand launch speed vs commanded). The can-bridge decodes the CAN1 get_encoder_estimate frames into its bb_axes cache (can_buses.cpp) at the ODrive broadcast rate; this message snapshots that cache at the telemetry-task rate. Pitch position maps to barrel degrees via deg = 90 + 360*rev (PitchAxis.h); hand velocity maps to ball speed via v = vel_rps * 2*pi*HAND_SPOOL_RADIUS_M.
BB_AXIS_ESTIMATES_FMT = '<Qffff'
BB_AXIS_ESTIMATES_SIZE = 24
_BB_AXIS_ESTIMATES_STRUCT = struct.Struct(BB_AXIS_ESTIMATES_FMT)
assert _BB_AXIS_ESTIMATES_STRUCT.size == 24

@dataclass
class BbAxisEstimates:
    t_bridge_us: int = 0
    pitch_pos_rev: float = 0.0
    pitch_vel_rps: float = 0.0
    hand_pos_rev: float = 0.0
    hand_vel_rps: float = 0.0

    def pack(self) -> bytes:
        return _BB_AXIS_ESTIMATES_STRUCT.pack(self.t_bridge_us, self.pitch_pos_rev, self.pitch_vel_rps, self.hand_pos_rev, self.hand_vel_rps)

    @classmethod
    def unpack(cls, data: bytes) -> 'BbAxisEstimates':
        vals = _BB_AXIS_ESTIMATES_STRUCT.unpack(data[:24])
        it = iter(vals)
        return cls(next(it), next(it), next(it), next(it), next(it))

# LegCmd: The Teensy's COMMANDED leg interp output — the float32 cubic-Hermite ladder result (after the lead + stroke clamps) that leg_interp.cpp writes to axes[i].target_pos_rev each 500 Hz tick and would send to the leg ODrives — snapshotted at the telemetry-task rate. Additive diagnostic (no existing frame changes, so NO PROTOCOL_VERSION bump): it exposes the on-Teensy float32 interpolator output so a bench validation can measure the float32-vs-float64 interp residual DIRECTLY, rather than inferring it from the encoder. Written for all legs regardless of the output gate, so it reflects the interp even when CAN3 TX is suppressed. Jugglebot convention (positive = extension).
LEG_CMD_FMT = '<Qffffffffffff'
LEG_CMD_SIZE = 56
_LEG_CMD_STRUCT = struct.Struct(LEG_CMD_FMT)
assert _LEG_CMD_STRUCT.size == 56

@dataclass
class LegCmd:
    t_teensy_us: int = 0
    cmd_pos_rev: tuple = field(default_factory=lambda: (0.0,) * 6)
    cmd_vel_rps: tuple = field(default_factory=lambda: (0.0,) * 6)

    def pack(self) -> bytes:
        return _LEG_CMD_STRUCT.pack(self.t_teensy_us, *self.cmd_pos_rev, *self.cmd_vel_rps)

    @classmethod
    def unpack(cls, data: bytes) -> 'LegCmd':
        vals = _LEG_CMD_STRUCT.unpack(data[:56])
        it = iter(vals)
        return cls(next(it), tuple(next(it) for _ in range(6)), tuple(next(it) for _ in range(6)))

# PlatformFrame: Verbatim Platform-Teensy relay-reply uplink. The can-bridge forwards every CAN3 frame it receives whose arbitration id is a Platform-Teensy reply (STATE_UPDATE 0x6E0 RobotState, TILT_READING 0x7DE inclinometer) verbatim, so the host owns the decode and the bridge stays decoupled from the Platform-Teensy byte layout (Teensy_code.ino createStateCANMessage / sendTiltData). The host correlates a reply to its pending relay read by (can_id, dlc): a STATE_READ awaits (0x6E0, 8); a TILT_READ awaits (0x7DE, 8). `t_bridge_us` only stamps bridge-side CAN3 RX for latency/diagnostics. NOTE(bench): the (id, dlc) discriminator is only sound if CAN3 SRX_DIS is set so the bridge's own 0x6E0 STATE_WRITE is not looped back as a reply — verify on the bench before trusting on hardware.
PLATFORM_FRAME_FMT = '<QIBBBBBBBBB'
PLATFORM_FRAME_SIZE = 21
_PLATFORM_FRAME_STRUCT = struct.Struct(PLATFORM_FRAME_FMT)
assert _PLATFORM_FRAME_STRUCT.size == 21

@dataclass
class PlatformFrame:
    t_bridge_us: int = 0
    can_id: int = 0
    dlc: int = 0
    data: tuple = field(default_factory=lambda: (0,) * 8)

    def pack(self) -> bytes:
        return _PLATFORM_FRAME_STRUCT.pack(self.t_bridge_us, self.can_id, self.dlc, *self.data)

    @classmethod
    def unpack(cls, data: bytes) -> 'PlatformFrame':
        vals = _PLATFORM_FRAME_STRUCT.unpack(data[:21])
        it = iter(vals)
        return cls(next(it), next(it), next(it), tuple(next(it) for _ in range(8)))

# HandCmdEcho: Hand command-echo telemetry. The can-bridge sniffs the Platform Teensy's Set_Input_Pos command to the HAND ODrive (axis 6) on CAN3 — arb_id(6, set_input_pos, cmd 0x0C) — and forwards the raw 8-byte payload verbatim so the host echoes the hand's COMMANDED pos/vel_ff/tor_ff (can_node._handle_hand_input_pos parity; the hand_telemetry pos_cmd/vel_ff_cmd/tor_ff_cmd fields were hardcoded 0 on the bridge until now). The host decodes `data` as `<f h h>` (float32 pos_rev + int16 vel_ff + int16 tor_ff) and divides vel/tor by INPUT_SCALE_HAND_VEL / INPUT_SCALE_HAND_TOR (100.0). Emitted at the telemetry-task rate only when a FRESH command was sniffed (event-driven; silent while the hand is idle). CAN3 SRX_DIS means the bridge never sniffs its own TX, so only genuine Platform→hand commands are echoed. `t_bridge_us` stamps CAN3 RX for latency/diagnostics.
HAND_CMD_ECHO_FMT = '<QBBBBBBBB'
HAND_CMD_ECHO_SIZE = 16
_HAND_CMD_ECHO_STRUCT = struct.Struct(HAND_CMD_ECHO_FMT)
assert _HAND_CMD_ECHO_STRUCT.size == 16

@dataclass
class HandCmdEcho:
    t_bridge_us: int = 0
    data: tuple = field(default_factory=lambda: (0,) * 8)

    def pack(self) -> bytes:
        return _HAND_CMD_ECHO_STRUCT.pack(self.t_bridge_us, *self.data)

    @classmethod
    def unpack(cls, data: bytes) -> 'HandCmdEcho':
        vals = _HAND_CMD_ECHO_STRUCT.unpack(data[:16])
        it = iter(vals)
        return cls(next(it), tuple(next(it) for _ in range(8)))

# HandSensor: Hand ball-present sensor state. A switch in the hand shorts the hand ODrive Pro's G02 to GND when a ball is seated; no released ODrive firmware pushes GPIO state on CANSimple, so the bridge POLLS get_gpio_states over an RxSdo/TxSdo pair (gpio_poll.cpp) and publishes the decoded cache here. Additive message — no existing frame changes, so NO PROTOCOL_VERSION bump (LegCmd precedent); an old Jetson ignores the unknown msg_type and a new Jetson treats never-seen as UNKNOWN. Emitted from task_telem: one frame per NEW good reply (so naturally rate-limited to the poll rate), plus a 1 Hz keepalive while no new reply lands, so staleness is itself observable on the wire. plans/active/hand-ball-sensor.md § Architecture is NORMATIVE for the signal semantics; these flags describe the bridge's cache and say nothing about the link, so the consumer applies its own RX-age gate.
HAND_SENSOR_FMT = '<QIBB'
HAND_SENSOR_SIZE = 14
_HAND_SENSOR_STRUCT = struct.Struct(HAND_SENSOR_FMT)
assert _HAND_SENSOR_STRUCT.size == 14

@dataclass
class HandSensor:
    t_bridge_us: int = 0
    raw_states: int = 0
    flags: int = 0
    miss_count: int = 0

    def pack(self) -> bytes:
        return _HAND_SENSOR_STRUCT.pack(self.t_bridge_us, self.raw_states, self.flags, self.miss_count)

    @classmethod
    def unpack(cls, data: bytes) -> 'HandSensor':
        vals = _HAND_SENSOR_STRUCT.unpack(data[:14])
        it = iter(vals)
        return cls(next(it), next(it), next(it), next(it))

# CanErrors: CAN3 wire-error + fault-confinement counters, 1 Hz. These numbers were already computed on every 1 kHz service tick (can_buses.cpp poll_bus_errors / service_bus) and then DISCARDED to the USB serial console — can_buses.h said outright that they are 'NOT on the UDP uplink'. That is exactly why the 2026-07-29 CAN3 bus-health flap could not be root-caused from an 8 MB bag: the bag proved the bus was entering error-passive at 42.4 % duty but carried nothing that could say WHICH wire-error class was driving it, so layer 2 of that investigation (logbook/2026-07-29-can3-bus-health-flap-hand-sensor-poller.md) stayed open pending a serial-console bench session. This message closes that gap: it is the Jetson-side half of the discriminator table in that entry. Additive — no existing frame changes, so NO PROTOCOL_VERSION bump (the LegCmd / HandSensor precedent): an old Jetson ignores the unknown msg_type and a new Jetson renders never-seen as unknown. CAN3 (the Jugglebot core bus) ONLY — CAN1/CAN2 keep their serial-only counters until something needs them, and a per-bus array would triple the wire cost for two buses nobody is currently debugging. All counters are CUMULATIVE SINCE BOOT (u32, free-running; the consumer differences them) except the three live/derived bytes at the end. Read tec_inc_sum vs rec_inc_sum to attribute error pressure to TX vs RX even when the live counters decay between 1 Hz samples.
CAN_ERRORS_FMT = '<IIIIIIIIIIIBBBB'
CAN_ERRORS_SIZE = 48
_CAN_ERRORS_STRUCT = struct.Struct(CAN_ERRORS_FMT)
assert _CAN_ERRORS_STRUCT.size == 48

@dataclass
class CanErrors:
    ack_cnt: int = 0
    crc_cnt: int = 0
    form_cnt: int = 0
    stuff_cnt: int = 0
    bit0_cnt: int = 0
    bit1_cnt: int = 0
    err_tx_ctx: int = 0
    err_rx_ctx: int = 0
    tec_inc_sum: int = 0
    rec_inc_sum: int = 0
    tx_gated: int = 0
    tec_live: int = 0
    rec_live: int = 0
    flt_live: int = 0
    flt_sustained: int = 0

    def pack(self) -> bytes:
        return _CAN_ERRORS_STRUCT.pack(self.ack_cnt, self.crc_cnt, self.form_cnt, self.stuff_cnt, self.bit0_cnt, self.bit1_cnt, self.err_tx_ctx, self.err_rx_ctx, self.tec_inc_sum, self.rec_inc_sum, self.tx_gated, self.tec_live, self.rec_live, self.flt_live, self.flt_sustained)

    @classmethod
    def unpack(cls, data: bytes) -> 'CanErrors':
        vals = _CAN_ERRORS_STRUCT.unpack(data[:48])
        it = iter(vals)
        return cls(next(it), next(it), next(it), next(it), next(it), next(it), next(it), next(it), next(it), next(it), next(it), next(it), next(it), next(it), next(it))

# RpcRequest: Generic RPC envelope. `method` selects the operation; `args` is a method-specific blob (see docs). `req_id` is echoed in the response for matching independent of the frame sequence counter.
RPC_REQUEST_FMT = '<HHHH'
RPC_REQUEST_SIZE = 8
_RPC_REQUEST_STRUCT = struct.Struct(RPC_REQUEST_FMT)
assert _RPC_REQUEST_STRUCT.size == 8

@dataclass
class RpcRequest:
    method: int = 0
    req_id: int = 0
    arg_len: int = 0
    pad: int = 0

    def pack(self) -> bytes:
        return _RPC_REQUEST_STRUCT.pack(self.method, self.req_id, self.arg_len, self.pad)

    @classmethod
    def unpack(cls, data: bytes) -> 'RpcRequest':
        vals = _RPC_REQUEST_STRUCT.unpack(data[:8])
        it = iter(vals)
        return cls(next(it), next(it), next(it), next(it))

# RpcResponse: Response to an RpcRequest. `result` is method-specific.
RPC_RESPONSE_FMT = '<HHHH'
RPC_RESPONSE_SIZE = 8
_RPC_RESPONSE_STRUCT = struct.Struct(RPC_RESPONSE_FMT)
assert _RPC_RESPONSE_STRUCT.size == 8

@dataclass
class RpcResponse:
    method: int = 0
    req_id: int = 0
    status: int = 0
    res_len: int = 0

    def pack(self) -> bytes:
        return _RPC_RESPONSE_STRUCT.pack(self.method, self.req_id, self.status, self.res_len)

    @classmethod
    def unpack(cls, data: bytes) -> 'RpcResponse':
        vals = _RPC_RESPONSE_STRUCT.unpack(data[:8])
        it = iter(vals)
        return cls(next(it), next(it), next(it), next(it))

# ── RPC method argument layouts ────────────────────────────────────────
AXIS_ALL = 255  # broadcast-to-all-legs sentinel

# ArgAxisState (SET_AXIS_STATE)
ARG_AXIS_STATE_FMT = '<BI'
ARG_AXIS_STATE_SIZE = 5
_ARG_AXIS_STATE_STRUCT = struct.Struct(ARG_AXIS_STATE_FMT)
assert _ARG_AXIS_STATE_STRUCT.size == 5

@dataclass
class ArgAxisState:
    axis: int = 0
    state: int = 0

    def pack(self) -> bytes:
        return _ARG_AXIS_STATE_STRUCT.pack(self.axis, self.state)

    @classmethod
    def unpack(cls, data: bytes) -> 'ArgAxisState':
        vals = _ARG_AXIS_STATE_STRUCT.unpack(data[:5])
        it = iter(vals)
        return cls(next(it), next(it))

# ArgControllerMode (SET_CONTROLLER_MODE)
ARG_CONTROLLER_MODE_FMT = '<BII'
ARG_CONTROLLER_MODE_SIZE = 9
_ARG_CONTROLLER_MODE_STRUCT = struct.Struct(ARG_CONTROLLER_MODE_FMT)
assert _ARG_CONTROLLER_MODE_STRUCT.size == 9

@dataclass
class ArgControllerMode:
    axis: int = 0
    ctrl: int = 0
    input: int = 0

    def pack(self) -> bytes:
        return _ARG_CONTROLLER_MODE_STRUCT.pack(self.axis, self.ctrl, self.input)

    @classmethod
    def unpack(cls, data: bytes) -> 'ArgControllerMode':
        vals = _ARG_CONTROLLER_MODE_STRUCT.unpack(data[:9])
        it = iter(vals)
        return cls(next(it), next(it), next(it))

# ArgVelCurr (SET_VEL_CURR_LIMITS)
ARG_VEL_CURR_FMT = '<Bff'
ARG_VEL_CURR_SIZE = 9
_ARG_VEL_CURR_STRUCT = struct.Struct(ARG_VEL_CURR_FMT)
assert _ARG_VEL_CURR_STRUCT.size == 9

@dataclass
class ArgVelCurr:
    axis: int = 0
    vel_limit: float = 0.0
    curr_limit: float = 0.0

    def pack(self) -> bytes:
        return _ARG_VEL_CURR_STRUCT.pack(self.axis, self.vel_limit, self.curr_limit)

    @classmethod
    def unpack(cls, data: bytes) -> 'ArgVelCurr':
        vals = _ARG_VEL_CURR_STRUCT.unpack(data[:9])
        it = iter(vals)
        return cls(next(it), next(it), next(it))

# ArgPosGain (SET_POS_GAIN)
ARG_POS_GAIN_FMT = '<Bf'
ARG_POS_GAIN_SIZE = 5
_ARG_POS_GAIN_STRUCT = struct.Struct(ARG_POS_GAIN_FMT)
assert _ARG_POS_GAIN_STRUCT.size == 5

@dataclass
class ArgPosGain:
    axis: int = 0
    pos_gain: float = 0.0

    def pack(self) -> bytes:
        return _ARG_POS_GAIN_STRUCT.pack(self.axis, self.pos_gain)

    @classmethod
    def unpack(cls, data: bytes) -> 'ArgPosGain':
        vals = _ARG_POS_GAIN_STRUCT.unpack(data[:5])
        it = iter(vals)
        return cls(next(it), next(it))

# ArgVelGains (SET_VEL_GAINS)
ARG_VEL_GAINS_FMT = '<Bff'
ARG_VEL_GAINS_SIZE = 9
_ARG_VEL_GAINS_STRUCT = struct.Struct(ARG_VEL_GAINS_FMT)
assert _ARG_VEL_GAINS_STRUCT.size == 9

@dataclass
class ArgVelGains:
    axis: int = 0
    vel_gain: float = 0.0
    vel_int_gain: float = 0.0

    def pack(self) -> bytes:
        return _ARG_VEL_GAINS_STRUCT.pack(self.axis, self.vel_gain, self.vel_int_gain)

    @classmethod
    def unpack(cls, data: bytes) -> 'ArgVelGains':
        vals = _ARG_VEL_GAINS_STRUCT.unpack(data[:9])
        it = iter(vals)
        return cls(next(it), next(it), next(it))

# ArgAbsPosition (SET_ABSOLUTE_POSITION)
ARG_ABS_POSITION_FMT = '<Bf'
ARG_ABS_POSITION_SIZE = 5
_ARG_ABS_POSITION_STRUCT = struct.Struct(ARG_ABS_POSITION_FMT)
assert _ARG_ABS_POSITION_STRUCT.size == 5

@dataclass
class ArgAbsPosition:
    axis: int = 0
    position: float = 0.0

    def pack(self) -> bytes:
        return _ARG_ABS_POSITION_STRUCT.pack(self.axis, self.position)

    @classmethod
    def unpack(cls, data: bytes) -> 'ArgAbsPosition':
        vals = _ARG_ABS_POSITION_STRUCT.unpack(data[:5])
        it = iter(vals)
        return cls(next(it), next(it))

# ArgAxisOnly (CLEAR_ERRORS / REBOOT_ODRIVES / ENCODER_SEARCH / HOME / ACTIVATE / DEACTIVATE)
ARG_AXIS_ONLY_FMT = '<B'
ARG_AXIS_ONLY_SIZE = 1
_ARG_AXIS_ONLY_STRUCT = struct.Struct(ARG_AXIS_ONLY_FMT)
assert _ARG_AXIS_ONLY_STRUCT.size == 1

@dataclass
class ArgAxisOnly:
    axis: int = 0

    def pack(self) -> bytes:
        return _ARG_AXIS_ONLY_STRUCT.pack(self.axis)

    @classmethod
    def unpack(cls, data: bytes) -> 'ArgAxisOnly':
        vals = _ARG_AXIS_ONLY_STRUCT.unpack(data[:1])
        it = iter(vals)
        return cls(next(it))

# ArgSdoRead (SDO_READ)
ARG_SDO_READ_FMT = '<BH'
ARG_SDO_READ_SIZE = 3
_ARG_SDO_READ_STRUCT = struct.Struct(ARG_SDO_READ_FMT)
assert _ARG_SDO_READ_STRUCT.size == 3

@dataclass
class ArgSdoRead:
    axis: int = 0
    endpoint: int = 0

    def pack(self) -> bytes:
        return _ARG_SDO_READ_STRUCT.pack(self.axis, self.endpoint)

    @classmethod
    def unpack(cls, data: bytes) -> 'ArgSdoRead':
        vals = _ARG_SDO_READ_STRUCT.unpack(data[:3])
        it = iter(vals)
        return cls(next(it), next(it))

# ArgSdoWrite (SDO_WRITE)
ARG_SDO_WRITE_FMT = '<BHf'
ARG_SDO_WRITE_SIZE = 7
_ARG_SDO_WRITE_STRUCT = struct.Struct(ARG_SDO_WRITE_FMT)
assert _ARG_SDO_WRITE_STRUCT.size == 7

@dataclass
class ArgSdoWrite:
    axis: int = 0
    endpoint: int = 0
    value: float = 0.0

    def pack(self) -> bytes:
        return _ARG_SDO_WRITE_STRUCT.pack(self.axis, self.endpoint, self.value)

    @classmethod
    def unpack(cls, data: bytes) -> 'ArgSdoWrite':
        vals = _ARG_SDO_WRITE_STRUCT.unpack(data[:7])
        it = iter(vals)
        return cls(next(it), next(it), next(it))

# ResultTimeOfDay (TIME_OF_DAY_QUERY (result))
RESULT_TIME_OF_DAY_FMT = '<Q'
RESULT_TIME_OF_DAY_SIZE = 8
_RESULT_TIME_OF_DAY_STRUCT = struct.Struct(RESULT_TIME_OF_DAY_FMT)
assert _RESULT_TIME_OF_DAY_STRUCT.size == 8

@dataclass
class ResultTimeOfDay:
    jetson_wall_us: int = 0

    def pack(self) -> bytes:
        return _RESULT_TIME_OF_DAY_STRUCT.pack(self.jetson_wall_us)

    @classmethod
    def unpack(cls, data: bytes) -> 'ResultTimeOfDay':
        vals = _RESULT_TIME_OF_DAY_STRUCT.unpack(data[:8])
        it = iter(vals)
        return cls(next(it))

# ResultAxisVersions (GET_AXIS_VERSIONS (result))
RESULT_AXIS_VERSIONS_FMT = '<BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB'
RESULT_AXIS_VERSIONS_SIZE = 57
_RESULT_AXIS_VERSIONS_STRUCT = struct.Struct(RESULT_AXIS_VERSIONS_FMT)
assert _RESULT_AXIS_VERSIONS_STRUCT.size == 57

@dataclass
class ResultAxisVersions:
    received_mask: int = 0
    raw: tuple = field(default_factory=lambda: (0,) * 56)

    def pack(self) -> bytes:
        return _RESULT_AXIS_VERSIONS_STRUCT.pack(self.received_mask, *self.raw)

    @classmethod
    def unpack(cls, data: bytes) -> 'ResultAxisVersions':
        vals = _RESULT_AXIS_VERSIONS_STRUCT.unpack(data[:57])
        it = iter(vals)
        return cls(next(it), tuple(next(it) for _ in range(56)))

# ArgBbThrow (BB_THROW)
ARG_BB_THROW_FMT = '<ffff'
ARG_BB_THROW_SIZE = 16
_ARG_BB_THROW_STRUCT = struct.Struct(ARG_BB_THROW_FMT)
assert _ARG_BB_THROW_STRUCT.size == 16

@dataclass
class ArgBbThrow:
    yaw_rad: float = 0.0
    pitch_rad: float = 0.0
    speed_mps: float = 0.0
    delay_s: float = 0.0

    def pack(self) -> bytes:
        return _ARG_BB_THROW_STRUCT.pack(self.yaw_rad, self.pitch_rad, self.speed_mps, self.delay_s)

    @classmethod
    def unpack(cls, data: bytes) -> 'ArgBbThrow':
        vals = _ARG_BB_THROW_STRUCT.unpack(data[:16])
        it = iter(vals)
        return cls(next(it), next(it), next(it), next(it))

# ArgRobotState (STATE_WRITE)
ARG_ROBOT_STATE_FMT = '<BBff'
ARG_ROBOT_STATE_SIZE = 10
_ARG_ROBOT_STATE_STRUCT = struct.Struct(ARG_ROBOT_STATE_FMT)
assert _ARG_ROBOT_STATE_STRUCT.size == 10

@dataclass
class ArgRobotState:
    is_homed: int = 0
    levelling_complete: int = 0
    pose_offset_tiltX: float = 0.0
    pose_offset_tiltY: float = 0.0

    def pack(self) -> bytes:
        return _ARG_ROBOT_STATE_STRUCT.pack(self.is_homed, self.levelling_complete, self.pose_offset_tiltX, self.pose_offset_tiltY)

    @classmethod
    def unpack(cls, data: bytes) -> 'ArgRobotState':
        vals = _ARG_ROBOT_STATE_STRUCT.unpack(data[:10])
        it = iter(vals)
        return cls(next(it), next(it), next(it), next(it))

# ArgHandTraj (HAND_TRAJ_CMD)
ARG_HAND_TRAJ_FMT = '<BBBBBBBB'
ARG_HAND_TRAJ_SIZE = 8
_ARG_HAND_TRAJ_STRUCT = struct.Struct(ARG_HAND_TRAJ_FMT)
assert _ARG_HAND_TRAJ_STRUCT.size == 8

@dataclass
class ArgHandTraj:
    payload: tuple = field(default_factory=lambda: (0,) * 8)

    def pack(self) -> bytes:
        return _ARG_HAND_TRAJ_STRUCT.pack(*self.payload)

    @classmethod
    def unpack(cls, data: bytes) -> 'ArgHandTraj':
        vals = _ARG_HAND_TRAJ_STRUCT.unpack(data[:8])
        it = iter(vals)
        return cls(tuple(next(it) for _ in range(8)))

# ── Hand axis-6 allow-table ──────────────────────────────────────────────
# RpcMethod ids the can-bridge forwards to the hand ODrive (axis 6); the
# single source mirrored by the firmware JbUdp::hand_axis6_permitted predicate.
HAND_AXIS6_PERMITTED = frozenset({
    int(RpcMethod.SET_AXIS_STATE),
    int(RpcMethod.SET_CONTROLLER_MODE),
    int(RpcMethod.SET_POS_GAIN),
    int(RpcMethod.SET_VEL_GAINS),
    int(RpcMethod.SET_VEL_CURR_LIMITS),
    int(RpcMethod.CLEAR_ERRORS),
    int(RpcMethod.REBOOT_ODRIVES),
    int(RpcMethod.HOME),
    int(RpcMethod.SET_ABSOLUTE_POSITION),
})

def hand_axis6_permitted(method: int) -> bool:
    """True iff `method` may be forwarded to the hand ODrive (axis 6)."""
    return int(method) in HAND_AXIS6_PERMITTED
