"""
AUTO-GENERATED by config/generate_udp_protocol.py — DO NOT EDIT
Jetson <-> leg-bridge Teensy UDP wire protocol (Python side).
See docs/teensy-udp-protocol.md. To regenerate: python config/generate_udp_protocol.py
"""
from __future__ import annotations
import struct
from dataclasses import dataclass, field
from enum import IntEnum

# ── Constants ──────────────────────────────────────────────────────────
PROTOCOL_VERSION = 1  # Bumped on any incompatible wire change
MAGIC = 19010  # "JB" little-endian preamble (bytes 0x42 0x4A)
HEADER_SIZE = 8  # Bytes before payload
CRC_SIZE = 2  # Trailing CRC-16 bytes
MAX_PAYLOAD = 1024  # Largest payload we will encode/accept
MAX_FRAME = 1034  # HEADER_SIZE + MAX_PAYLOAD + CRC_SIZE
PORT_STREAM = 5005  # High-rate push: setpoint dn, telem/diag/profile/heartbeat up
PORT_RPC = 5006  # Request/response with retry-on-timeout
TEENSY_IP_0 = 192  # Static Teensy IP octet 0 (192.168.42.2)
TEENSY_IP_1 = 168
TEENSY_IP_2 = 42
TEENSY_IP_3 = 2
JETSON_IP_3 = 1  # Static Jetson teensy-link IP octet 3 (192.168.42.1)
NUM_LEGS = 6  # Leg ODrive axes 0..5
NUM_AXES = 7  # Legs + hand (cache + telemetry breadth)
PROFILE_NUM_TASKS = 9  # Task slots reported in the profiling frame
HEARTBEAT_HZ = 10  # Both-direction liveness rate
LINK_LOST_MISSES = 5  # Missed heartbeats before declaring link lost

# ── Enums ──────────────────────────────────────────────────────────────
class MsgType(IntEnum):
    SETPOINT = 1  # 40 Hz MPC setpoint waypoints (STREAM, J→T)
    HEARTBEAT_J2T = 2  # Jetson liveness (STREAM, J→T)
    RPC_REQUEST = 16  # RPC request (RPC port, J→T)
    TELEMETRY = 129  # 100 Hz motor state (STREAM, T→J)
    DIAGNOSTIC = 130  # On-change per-axis diagnostics (STREAM, T→J)
    HEARTBEAT_T2J = 131  # Teensy liveness + link/bus health (STREAM, T→J)
    PROFILE = 132  # 1 Hz profiling/instrumentation (STREAM, T→J)
    RPC_RESPONSE = 144  # RPC response (RPC port, T→J)

class RpcMethod(IntEnum):
    NOP = 0  # No-op (link test)
    TIME_OF_DAY_QUERY = 1  # Wall-clock bootstrap + drift resync (time-sync master)
    SET_AXIS_STATE = 16  # ODrive set_requested_state
    SET_CONTROLLER_MODE = 17  # ODrive set_controller_mode
    SET_VEL_CURR_LIMITS = 18  # ODrive set_vel_curr_limits
    SET_POS_GAIN = 19  # ODrive set_pos_gain
    SET_VEL_GAINS = 20  # ODrive set_vel_gains
    CLEAR_ERRORS = 21  # ODrive clear_errors
    REBOOT_ODRIVES = 22  # ODrive reboot
    SET_ABSOLUTE_POSITION = 23  # ODrive set_absolute_position (post-homing)
    ENCODER_SEARCH = 32  # Run encoder index search (Phase 9 — stubbed)
    HOME = 33  # Run homing (Phase 9 — stubbed)
    SDO_READ = 48  # Arbitrary parameter read
    SDO_WRITE = 49  # Arbitrary parameter write

class RpcStatus(IntEnum):
    OK = 0  # Success
    ERR_UNKNOWN_METHOD = 1  # Method id not recognised
    ERR_BAD_ARGS = 2  # Argument decode failed / wrong length
    ERR_BUS_DOWN = 3  # Refused: CAN bus is down (never command a dead bus)
    ERR_TIMEOUT = 4  # Downstream CAN op timed out
    ERR_REJECTED = 5  # Refused by a safety gate
    ERR_NOT_IMPL = 6  # Method not implemented in this firmware revision

class LinkState(IntEnum):
    INIT = 0  # Ethernet up, no Jetson heartbeat yet
    UP = 1  # Healthy bidirectional link
    DEGRADED = 2  # Some missed heartbeats, not yet lost
    LOST = 3  # Link lost → legs to safe behaviour

class BusHealth(IntEnum):
    UNKNOWN = 0  # No frames seen yet
    OK = 1  # Frames flowing, no error frames
    WARN = 2  # Error counters rising
    BUS_OFF = 3  # Controller bus-off

class FaultState(IntEnum):
    NONE = 0  # Nominal
    MPC_STALE = 1  # MPC setpoint older than staleness threshold → E-STOP
    LINK_LOST = 2  # Jetson link lost → safe behaviour on legs
    MOTOR_OVERSPEED = 3  # A leg exceeded the overspeed limit
    MAX_DEVIATION = 4  # Commanded pos diverged too far from encoder
    ODRIVE_FATAL = 5  # Active ODrive error / disarm-while-closed-loop
    CAN_BUS_DOWN = 6  # CAN2 (leg bus) down — hold, deferred stow armed

class GuardMode(IntEnum):
    DISABLED = 0
    ENABLED = 1
    ESTOP = 2

# ── CRC-16/CCITT-FALSE ─────────────────────────────────────────────────
def crc16_ccitt(data: bytes) -> int:
    crc = 0xFFFF
    for b in data:
        crc ^= b << 8
        for _ in range(8):
            crc = ((crc << 1) ^ 0x1021) & 0xFFFF if (crc & 0x8000) else (crc << 1) & 0xFFFF
    return crc & 0xFFFF

# ── Frame header ───────────────────────────────────────────────────────
_HEADER_FMT = "<HBBHH"  # magic, version, msg_type, seq, length
assert struct.calcsize(_HEADER_FMT) == HEADER_SIZE

def encode_frame(msg_type: int, seq: int, payload: bytes) -> bytes:
    """Build a full wire frame: header + payload + CRC-16."""
    if len(payload) > MAX_PAYLOAD:
        raise ValueError(f"payload {len(payload)} > MAX_PAYLOAD {MAX_PAYLOAD}")
    head = struct.pack(_HEADER_FMT, MAGIC, PROTOCOL_VERSION, msg_type,
                       seq & 0xFFFF, len(payload))
    body = head + payload
    crc = crc16_ccitt(body)
    return body + struct.pack('<H', crc)

def decode_frame(frame: bytes):
    """Validate + parse a wire frame. Returns (msg_type, seq, payload).

    Raises ValueError on bad magic/version/length/CRC.
    """
    if len(frame) < HEADER_SIZE + CRC_SIZE:
        raise ValueError("frame too short")
    magic, version, msg_type, seq, length = struct.unpack_from(_HEADER_FMT, frame, 0)
    if magic != MAGIC:
        raise ValueError(f"bad magic 0x{magic:04X}")
    if version != PROTOCOL_VERSION:
        raise ValueError(f"bad version {version}")
    if HEADER_SIZE + length + CRC_SIZE != len(frame):
        raise ValueError(f"length {length} inconsistent with frame {len(frame)}")
    want = crc16_ccitt(frame[:HEADER_SIZE + length])
    got = struct.unpack_from('<H', frame, HEADER_SIZE + length)[0]
    if want != got:
        raise ValueError(f"CRC mismatch want 0x{want:04X} got 0x{got:04X}")
    payload = frame[HEADER_SIZE:HEADER_SIZE + length]
    return msg_type, seq, payload

# ── Payload structs ────────────────────────────────────────────────────
# Setpoint: 40 Hz MPC setpoint waypoints. Carries motor-rev-space quantities (Jugglebot convention: positive = leg extension) exactly as motor_guard's interpolator consumes them. The Jetson bridge does the same mm→rev / pose conversions motor_guard does today; the Teensy interpolator works purely in rev-space. `u1`/`u2` presence is signalled by the flags bits (NOT NaN sentinels).
SETPOINT_FMT = '<ffffffffffffffffffffffffffffffffffffIQ'
SETPOINT_SIZE = 156
_SETPOINT_STRUCT = struct.Struct(SETPOINT_FMT)
assert _SETPOINT_STRUCT.size == 156

@dataclass
class Setpoint:
    u0: tuple = field(default_factory=lambda: (0.0,) * 6)
    u1: tuple = field(default_factory=lambda: (0.0,) * 6)
    u2: tuple = field(default_factory=lambda: (0.0,) * 6)
    v0: tuple = field(default_factory=lambda: (0.0,) * 6)
    accel: tuple = field(default_factory=lambda: (0.0,) * 6)
    torque_ff: tuple = field(default_factory=lambda: (0.0,) * 6)
    flags: int = 0
    t_origin_us: int = 0

    def pack(self) -> bytes:
        return _SETPOINT_STRUCT.pack(*self.u0, *self.u1, *self.u2, *self.v0, *self.accel, *self.torque_ff, self.flags, self.t_origin_us)

    @classmethod
    def unpack(cls, data: bytes) -> 'Setpoint':
        vals = _SETPOINT_STRUCT.unpack(data[:156])
        it = iter(vals)
        return cls(tuple(next(it) for _ in range(6)), tuple(next(it) for _ in range(6)), tuple(next(it) for _ in range(6)), tuple(next(it) for _ in range(6)), tuple(next(it) for _ in range(6)), tuple(next(it) for _ in range(6)), next(it), next(it))

# HeartbeatJ2T: Jetson → Teensy liveness, ~10 Hz.
HEARTBEAT_J2T_FMT = '<QI'
HEARTBEAT_J2T_SIZE = 12
_HEARTBEAT_J2T_STRUCT = struct.Struct(HEARTBEAT_J2T_FMT)
assert _HEARTBEAT_J2T_STRUCT.size == 12

@dataclass
class HeartbeatJ2T:
    t_jetson_us: int = 0
    flags: int = 0

    def pack(self) -> bytes:
        return _HEARTBEAT_J2T_STRUCT.pack(self.t_jetson_us, self.flags)

    @classmethod
    def unpack(cls, data: bytes) -> 'HeartbeatJ2T':
        vals = _HEARTBEAT_J2T_STRUCT.unpack(data[:12])
        it = iter(vals)
        return cls(next(it), next(it))

# Telemetry: 100 Hz motor state for all axes (legs + hand). pos/vel are in the Jugglebot convention (positive = extension), already sign-corrected from the ODrive convention.
TELEMETRY_FMT = '<Qffffffffffffff'
TELEMETRY_SIZE = 64
_TELEMETRY_STRUCT = struct.Struct(TELEMETRY_FMT)
assert _TELEMETRY_STRUCT.size == 64

@dataclass
class Telemetry:
    t_teensy_us: int = 0
    pos_rev: tuple = field(default_factory=lambda: (0.0,) * 7)
    vel_rps: tuple = field(default_factory=lambda: (0.0,) * 7)

    def pack(self) -> bytes:
        return _TELEMETRY_STRUCT.pack(self.t_teensy_us, *self.pos_rev, *self.vel_rps)

    @classmethod
    def unpack(cls, data: bytes) -> 'Telemetry':
        vals = _TELEMETRY_STRUCT.unpack(data[:64])
        it = iter(vals)
        return cls(next(it), tuple(next(it) for _ in range(7)), tuple(next(it) for _ in range(7)))

# Diagnostic: Per-axis diagnostics, published on-change (delta over threshold) OR on a 1 Hz heartbeat. One axis per frame.
DIAGNOSTIC_FMT = '<BBBBBBBBIIfffff'
DIAGNOSTIC_SIZE = 36
_DIAGNOSTIC_STRUCT = struct.Struct(DIAGNOSTIC_FMT)
assert _DIAGNOSTIC_STRUCT.size == 36

@dataclass
class Diagnostic:
    axis_id: int = 0
    axis_state: int = 0
    ctrl_mode: int = 0
    input_mode: int = 0
    flags: int = 0
    pad: tuple = field(default_factory=lambda: (0,) * 3)
    active_errors: int = 0
    disarm_reason: int = 0
    iq_setpoint: float = 0.0
    iq_measured: float = 0.0
    temp_fet: float = 0.0
    temp_motor: float = 0.0
    bus_voltage: float = 0.0

    def pack(self) -> bytes:
        return _DIAGNOSTIC_STRUCT.pack(self.axis_id, self.axis_state, self.ctrl_mode, self.input_mode, self.flags, *self.pad, self.active_errors, self.disarm_reason, self.iq_setpoint, self.iq_measured, self.temp_fet, self.temp_motor, self.bus_voltage)

    @classmethod
    def unpack(cls, data: bytes) -> 'Diagnostic':
        vals = _DIAGNOSTIC_STRUCT.unpack(data[:36])
        it = iter(vals)
        return cls(next(it), next(it), next(it), next(it), next(it), tuple(next(it) for _ in range(3)), next(it), next(it), next(it), next(it), next(it), next(it), next(it))

# HeartbeatT2J: Teensy → Jetson liveness + link/bus health, ~10 Hz.
HEARTBEAT_T2J_FMT = '<QBBBBII'
HEARTBEAT_T2J_SIZE = 20
_HEARTBEAT_T2J_STRUCT = struct.Struct(HEARTBEAT_T2J_FMT)
assert _HEARTBEAT_T2J_STRUCT.size == 20

@dataclass
class HeartbeatT2J:
    t_teensy_us: int = 0
    link_state: int = 0
    bus1_health: int = 0
    bus2_health: int = 0
    fault_state: int = 0
    flags: int = 0
    uptime_ms: int = 0

    def pack(self) -> bytes:
        return _HEARTBEAT_T2J_STRUCT.pack(self.t_teensy_us, self.link_state, self.bus1_health, self.bus2_health, self.fault_state, self.flags, self.uptime_ms)

    @classmethod
    def unpack(cls, data: bytes) -> 'HeartbeatT2J':
        vals = _HEARTBEAT_T2J_STRUCT.unpack(data[:20])
        it = iter(vals)
        return cls(next(it), next(it), next(it), next(it), next(it), next(it), next(it))

# Profile: 1 Hz firmware instrumentation. Per-task CPU%, CAN bus utilisation, UDP round-trip/jitter, the 500 Hz interp deadline-miss counter, and free heap. Consumed by tools/probes/teensy_link_profiling/jetson.
PROFILE_FMT = '<QHHHHHHHHHIIIIHHIIIII'
PROFILE_SIZE = 66
_PROFILE_STRUCT = struct.Struct(PROFILE_FMT)
assert _PROFILE_STRUCT.size == 66

@dataclass
class Profile:
    t_teensy_us: int = 0
    cpu_pct_x100: tuple = field(default_factory=lambda: (0,) * 9)
    can1_rx: int = 0
    can1_tx: int = 0
    can2_rx: int = 0
    can2_tx: int = 0
    can1_util_x100: int = 0
    can2_util_x100: int = 0
    udp_rtt_us: int = 0
    udp_jitter_us: int = 0
    interp_deadline_misses: int = 0
    interp_max_jitter_us: int = 0
    free_heap_bytes: int = 0

    def pack(self) -> bytes:
        return _PROFILE_STRUCT.pack(self.t_teensy_us, *self.cpu_pct_x100, self.can1_rx, self.can1_tx, self.can2_rx, self.can2_tx, self.can1_util_x100, self.can2_util_x100, self.udp_rtt_us, self.udp_jitter_us, self.interp_deadline_misses, self.interp_max_jitter_us, self.free_heap_bytes)

    @classmethod
    def unpack(cls, data: bytes) -> 'Profile':
        vals = _PROFILE_STRUCT.unpack(data[:66])
        it = iter(vals)
        return cls(next(it), tuple(next(it) for _ in range(9)), next(it), next(it), next(it), next(it), next(it), next(it), next(it), next(it), next(it), next(it), next(it))

# RpcRequest: Generic RPC envelope. `method` selects the operation; `args` is a method-specific blob (see docs). `req_id` is echoed in the response for matching independent of the frame sequence counter.
RPC_REQUEST_FMT = '<HHHH'
RPC_REQUEST_SIZE = 8
_RPC_REQUEST_STRUCT = struct.Struct(RPC_REQUEST_FMT)
assert _RPC_REQUEST_STRUCT.size == 8

@dataclass
class RpcRequest:
    method: int = 0
    req_id: int = 0
    arg_len: int = 0
    pad: int = 0

    def pack(self) -> bytes:
        return _RPC_REQUEST_STRUCT.pack(self.method, self.req_id, self.arg_len, self.pad)

    @classmethod
    def unpack(cls, data: bytes) -> 'RpcRequest':
        vals = _RPC_REQUEST_STRUCT.unpack(data[:8])
        it = iter(vals)
        return cls(next(it), next(it), next(it), next(it))

# RpcResponse: Response to an RpcRequest. `result` is method-specific.
RPC_RESPONSE_FMT = '<HHHH'
RPC_RESPONSE_SIZE = 8
_RPC_RESPONSE_STRUCT = struct.Struct(RPC_RESPONSE_FMT)
assert _RPC_RESPONSE_STRUCT.size == 8

@dataclass
class RpcResponse:
    method: int = 0
    req_id: int = 0
    status: int = 0
    res_len: int = 0

    def pack(self) -> bytes:
        return _RPC_RESPONSE_STRUCT.pack(self.method, self.req_id, self.status, self.res_len)

    @classmethod
    def unpack(cls, data: bytes) -> 'RpcResponse':
        vals = _RPC_RESPONSE_STRUCT.unpack(data[:8])
        it = iter(vals)
        return cls(next(it), next(it), next(it), next(it))

# ── RPC method argument layouts ────────────────────────────────────────
AXIS_ALL = 255  # broadcast-to-all-legs sentinel

# ArgAxisState (SET_AXIS_STATE)
ARG_AXIS_STATE_FMT = '<BI'
ARG_AXIS_STATE_SIZE = 5
_ARG_AXIS_STATE_STRUCT = struct.Struct(ARG_AXIS_STATE_FMT)
assert _ARG_AXIS_STATE_STRUCT.size == 5

@dataclass
class ArgAxisState:
    axis: int = 0
    state: int = 0

    def pack(self) -> bytes:
        return _ARG_AXIS_STATE_STRUCT.pack(self.axis, self.state)

    @classmethod
    def unpack(cls, data: bytes) -> 'ArgAxisState':
        return cls(*_ARG_AXIS_STATE_STRUCT.unpack(data[:5]))

# ArgControllerMode (SET_CONTROLLER_MODE)
ARG_CONTROLLER_MODE_FMT = '<BII'
ARG_CONTROLLER_MODE_SIZE = 9
_ARG_CONTROLLER_MODE_STRUCT = struct.Struct(ARG_CONTROLLER_MODE_FMT)
assert _ARG_CONTROLLER_MODE_STRUCT.size == 9

@dataclass
class ArgControllerMode:
    axis: int = 0
    ctrl: int = 0
    input: int = 0

    def pack(self) -> bytes:
        return _ARG_CONTROLLER_MODE_STRUCT.pack(self.axis, self.ctrl, self.input)

    @classmethod
    def unpack(cls, data: bytes) -> 'ArgControllerMode':
        return cls(*_ARG_CONTROLLER_MODE_STRUCT.unpack(data[:9]))

# ArgVelCurr (SET_VEL_CURR_LIMITS)
ARG_VEL_CURR_FMT = '<Bff'
ARG_VEL_CURR_SIZE = 9
_ARG_VEL_CURR_STRUCT = struct.Struct(ARG_VEL_CURR_FMT)
assert _ARG_VEL_CURR_STRUCT.size == 9

@dataclass
class ArgVelCurr:
    axis: int = 0
    vel_limit: float = 0.0
    curr_limit: float = 0.0

    def pack(self) -> bytes:
        return _ARG_VEL_CURR_STRUCT.pack(self.axis, self.vel_limit, self.curr_limit)

    @classmethod
    def unpack(cls, data: bytes) -> 'ArgVelCurr':
        return cls(*_ARG_VEL_CURR_STRUCT.unpack(data[:9]))

# ArgPosGain (SET_POS_GAIN)
ARG_POS_GAIN_FMT = '<Bf'
ARG_POS_GAIN_SIZE = 5
_ARG_POS_GAIN_STRUCT = struct.Struct(ARG_POS_GAIN_FMT)
assert _ARG_POS_GAIN_STRUCT.size == 5

@dataclass
class ArgPosGain:
    axis: int = 0
    pos_gain: float = 0.0

    def pack(self) -> bytes:
        return _ARG_POS_GAIN_STRUCT.pack(self.axis, self.pos_gain)

    @classmethod
    def unpack(cls, data: bytes) -> 'ArgPosGain':
        return cls(*_ARG_POS_GAIN_STRUCT.unpack(data[:5]))

# ArgVelGains (SET_VEL_GAINS)
ARG_VEL_GAINS_FMT = '<Bff'
ARG_VEL_GAINS_SIZE = 9
_ARG_VEL_GAINS_STRUCT = struct.Struct(ARG_VEL_GAINS_FMT)
assert _ARG_VEL_GAINS_STRUCT.size == 9

@dataclass
class ArgVelGains:
    axis: int = 0
    vel_gain: float = 0.0
    vel_int_gain: float = 0.0

    def pack(self) -> bytes:
        return _ARG_VEL_GAINS_STRUCT.pack(self.axis, self.vel_gain, self.vel_int_gain)

    @classmethod
    def unpack(cls, data: bytes) -> 'ArgVelGains':
        return cls(*_ARG_VEL_GAINS_STRUCT.unpack(data[:9]))

# ArgAbsPosition (SET_ABSOLUTE_POSITION)
ARG_ABS_POSITION_FMT = '<Bf'
ARG_ABS_POSITION_SIZE = 5
_ARG_ABS_POSITION_STRUCT = struct.Struct(ARG_ABS_POSITION_FMT)
assert _ARG_ABS_POSITION_STRUCT.size == 5

@dataclass
class ArgAbsPosition:
    axis: int = 0
    position: float = 0.0

    def pack(self) -> bytes:
        return _ARG_ABS_POSITION_STRUCT.pack(self.axis, self.position)

    @classmethod
    def unpack(cls, data: bytes) -> 'ArgAbsPosition':
        return cls(*_ARG_ABS_POSITION_STRUCT.unpack(data[:5]))

# ArgAxisOnly (CLEAR_ERRORS / REBOOT_ODRIVES / ENCODER_SEARCH / HOME)
ARG_AXIS_ONLY_FMT = '<B'
ARG_AXIS_ONLY_SIZE = 1
_ARG_AXIS_ONLY_STRUCT = struct.Struct(ARG_AXIS_ONLY_FMT)
assert _ARG_AXIS_ONLY_STRUCT.size == 1

@dataclass
class ArgAxisOnly:
    axis: int = 0

    def pack(self) -> bytes:
        return _ARG_AXIS_ONLY_STRUCT.pack(self.axis)

    @classmethod
    def unpack(cls, data: bytes) -> 'ArgAxisOnly':
        return cls(*_ARG_AXIS_ONLY_STRUCT.unpack(data[:1]))

# ArgSdoRead (SDO_READ)
ARG_SDO_READ_FMT = '<BH'
ARG_SDO_READ_SIZE = 3
_ARG_SDO_READ_STRUCT = struct.Struct(ARG_SDO_READ_FMT)
assert _ARG_SDO_READ_STRUCT.size == 3

@dataclass
class ArgSdoRead:
    axis: int = 0
    endpoint: int = 0

    def pack(self) -> bytes:
        return _ARG_SDO_READ_STRUCT.pack(self.axis, self.endpoint)

    @classmethod
    def unpack(cls, data: bytes) -> 'ArgSdoRead':
        return cls(*_ARG_SDO_READ_STRUCT.unpack(data[:3]))

# ArgSdoWrite (SDO_WRITE)
ARG_SDO_WRITE_FMT = '<BHf'
ARG_SDO_WRITE_SIZE = 7
_ARG_SDO_WRITE_STRUCT = struct.Struct(ARG_SDO_WRITE_FMT)
assert _ARG_SDO_WRITE_STRUCT.size == 7

@dataclass
class ArgSdoWrite:
    axis: int = 0
    endpoint: int = 0
    value: float = 0.0

    def pack(self) -> bytes:
        return _ARG_SDO_WRITE_STRUCT.pack(self.axis, self.endpoint, self.value)

    @classmethod
    def unpack(cls, data: bytes) -> 'ArgSdoWrite':
        return cls(*_ARG_SDO_WRITE_STRUCT.unpack(data[:7]))

# ResultTimeOfDay (TIME_OF_DAY_QUERY (result))
RESULT_TIME_OF_DAY_FMT = '<Q'
RESULT_TIME_OF_DAY_SIZE = 8
_RESULT_TIME_OF_DAY_STRUCT = struct.Struct(RESULT_TIME_OF_DAY_FMT)
assert _RESULT_TIME_OF_DAY_STRUCT.size == 8

@dataclass
class ResultTimeOfDay:
    jetson_wall_us: int = 0

    def pack(self) -> bytes:
        return _RESULT_TIME_OF_DAY_STRUCT.pack(self.jetson_wall_us)

    @classmethod
    def unpack(cls, data: bytes) -> 'ResultTimeOfDay':
        return cls(*_RESULT_TIME_OF_DAY_STRUCT.unpack(data[:8]))
