M48
; DRILL file {KiCad (6.0.9)} date Tue Jul 21 22:24:25 2026
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-07-21T22:24:25+10:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.9)
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.400
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C1.200
%
G90
G05
T1
X290.57Y-165.11
X291.84Y-165.11
X293.11Y-165.11
T2
X291.84Y-148.6
X302.0Y-148.6
T0
M30
