#!/usr/bin/env python3
"""
generate_config.py — Generate C++ and Python constants from YAML config files.

Usage:
    python generate_config.py                  # generate all configs
    python generate_config.py path/to/yaml     # specify protocol YAML only

Outputs:
    config/generated/protocol_config.h          (C++ constexpr header)
    config/generated/protocol_config.py         (Python constants module)
    config/generated/hardware_config.h         (C++ constexpr header)
    config/generated/hardware_config.py        (Python constants module)
"""

import math
import sys
from pathlib import Path
import yaml

SCRIPT_DIR = Path(__file__).resolve().parent
REPO_ROOT = SCRIPT_DIR.parent
DEFAULT_YAML = SCRIPT_DIR / "protocol_config.yaml"
HW_YAML = SCRIPT_DIR / "hardware_config.yaml"
OUTPUT_DIR = SCRIPT_DIR / "generated"

# Additional output locations so consumers can import/include directly
ROS_PKG_DIR = REPO_ROOT / "ros_ws" / "src" / "jugglebot" / "jugglebot"
BB_FIRMWARE_DIR = REPO_ROOT / "Ball Butler" / "ball_butler_main"
PLATFORM_FIRMWARE_DIR = REPO_ROOT / "ros_ws" / "src" / "jugglebot" / "Teensy_code"


def load_yaml(path: Path) -> dict:
    with open(path, "r") as f:
        return yaml.safe_load(f)


def fmt_hex(v) -> str:
    """Format an integer as 0x.. hex (minimal digits, no zero-padding), or float as-is."""
    if isinstance(v, int):
        return f"0x{v:02X}" if v <= 0xFF else f"0x{v:X}"
    return str(v)


# ── C++ generation ──────────────────────────────────────────────────────────

def cpp_section(title: str) -> list[str]:
    """Return a C++ section-divider comment block."""
    bar = "// " + "=" * 74
    return ["", bar, f"// {title}", bar, ""]


def generate_cpp(cfg: dict) -> str:
    lines = [
        "#pragma once",
        "// AUTO-GENERATED by generate_config.py — DO NOT EDIT",
        "// Source: config/protocol_config.yaml",
        "//",
        "// Shared protocol constants for the Jugglebot CAN bus.",
        "// Consumed by: Ball Butler firmware, Platform Teensy firmware, ROS2 Python.",
        "// To regenerate: python config/generate_config.py",
        "",
        "#include <cstdint>",
    ]

    # CAN bus
    lines += cpp_section("CAN Bus Configuration")
    lines.append("namespace CanBus {")
    lines.append(f"  constexpr uint32_t BAUD_RATE = {cfg['can_bus']['baud_rate']}u;  // All nodes must agree")
    lines.append("}")

    # ODrive commands
    lines += cpp_section("ODrive CAN Protocol — Command IDs (lower 5 bits of arbitration ID)")
    lines.append("namespace ODriveCmd {")
    for name, val in cfg["odrive"]["commands"].items():
        lines.append(f"  constexpr uint8_t {name} = {fmt_hex(val)};")
    lines.append("}")

    # ODrive states
    lines += cpp_section("ODrive Axis States")
    lines.append("namespace ODriveState {")
    for name, val in cfg["odrive"]["states"].items():
        lines.append(f"  constexpr uint32_t {name} = {val}u;")
    lines.append("}")

    # ODrive control modes
    lines.append("")
    lines.append("// ODrive control modes")
    lines.append("namespace ODriveControlMode {")
    for name, val in cfg["odrive"]["control_modes"].items():
        lines.append(f"  constexpr uint32_t {name} = {val}u;")
    lines.append("}")

    # ODrive input modes
    lines.append("")
    lines.append("// ODrive input modes")
    lines.append("namespace ODriveInputMode {")
    for name, val in cfg["odrive"]["input_modes"].items():
        lines.append(f"  constexpr uint32_t {name} = {val}u;")
    lines.append("}")

    # ODrive errors
    lines.append("")
    lines.append("// ODrive error bit masks")
    lines.append("namespace ODriveErrors {")
    for name, val in cfg["odrive"]["errors"].items():
        lines.append(f"  constexpr uint32_t {name} = {fmt_hex(val)}u;")
    lines.append("}")

    # Node IDs
    lines += cpp_section("CAN Node IDs — ODrive axis addresses")
    lines.append("namespace NodeId {")
    legs = cfg["node_ids"]["legs"]
    for i, nid in enumerate(legs):
        lines.append(f"  constexpr uint8_t LEG_{i} = {nid};")
    lines.append(f"  constexpr uint8_t JUGGLEBOT_HAND = {cfg['node_ids']['jugglebot_hand']};")
    lines.append(f"  constexpr uint8_t BB_PITCH = {cfg['node_ids']['bb_pitch']};")
    lines.append(f"  constexpr uint8_t BB_HAND = {cfg['node_ids']['bb_hand']};")
    lines.append("}")

    # Shared CAN IDs
    lines += cpp_section("Custom CAN Message IDs")
    lines.append("// Shared IDs — used by both Platform and Ball Butler Teensys")
    lines.append("namespace SharedCanId {")
    for name, val in cfg["can_ids"]["shared"].items():
        lines.append(f"  constexpr uint32_t {name} = {fmt_hex(val)};")
    lines.append("}")

    # Platform CAN IDs
    lines.append("")
    lines.append("// Platform Teensy <-> Host")
    lines.append("namespace PlatformCanId {")
    for name, val in cfg["can_ids"]["platform"].items():
        lines.append(f"  constexpr uint32_t {name} = {fmt_hex(val)};")
    lines.append("}")

    # Ball Butler CAN IDs
    lines.append("")
    lines.append("// Ball Butler Teensy <-> Host")
    lines.append("namespace BallButlerCanId {")
    for name, val in cfg["can_ids"]["ball_butler"].items():
        lines.append(f"  constexpr uint32_t {name} = {fmt_hex(val)};")
    lines.append("}")

    # Ball Butler states
    lines += cpp_section("Ball Butler State Machine")
    lines.append("// States — encoded in heartbeat byte 0 (bits 1-7)")
    lines.append("namespace BallButlerState {")
    for name, val in cfg["ball_butler"]["states"].items():
        lines.append(f"  constexpr uint8_t {name} = {val};")
    lines.append("}")

    # Ball Butler errors
    lines.append("")
    lines.append("// Error codes — encoded in heartbeat byte 1 when state == ERROR")
    lines.append("namespace BallButlerErrorCode {")
    for name, val in cfg["ball_butler"]["errors"].items():
        lines.append(f"  constexpr uint8_t {name} = {val};")
    lines.append("}")

    # Heartbeat encoding
    lines += cpp_section("Encoding / Scaling")
    lines.append("// Ball Butler heartbeat CAN frame encoding resolutions")
    lines.append("namespace HeartbeatEncoding {")
    for name, val in cfg["encoding"]["heartbeat"].items():
        lines.append(f"  constexpr float {name} = {val}f;")
    lines.append("}")

    # Input scales
    lines.append("")
    lines.append("// ODrive input scaling (vel_ff and torque_ff are sent as int16 * scale)")
    lines.append("namespace InputScale {")
    for name, val in cfg["encoding"]["input_scales"].items():
        lines.append(f"  constexpr float {name} = {float(val)}f;")
    lines.append("}")

    # SDO
    lines += cpp_section("SDO — Arbitrary Parameter Access")
    lines.append("namespace SDO {")
    for name, val in cfg["sdo"].items():
        lines.append(f"  constexpr uint8_t {name} = {fmt_hex(val)};")
    lines.append("}")

    # Endpoints
    lines += cpp_section("Endpoint IDs — ODrive internal parameter addresses")
    lines.append("namespace EndpointId {")
    for name, val in cfg["endpoints"].items():
        lines.append(f"  constexpr uint16_t {name} = {val};")
    lines.append("}")
    lines.append("")

    return "\n".join(lines)


# ── Python generation ───────────────────────────────────────────────────────

def py_section(title: str) -> list[str]:
    """Return a Python section-divider comment block."""
    bar = "# " + "=" * 76
    return ["", bar, f"# {title}", bar, ""]


def generate_python(cfg: dict) -> str:
    lines = [
        '"""',
        "AUTO-GENERATED by generate_config.py — DO NOT EDIT",
        "Source: config/protocol_config.yaml",
        "",
        "Shared protocol constants for the Jugglebot CAN bus.",
        "Consumed by: ROS2 Python nodes (can_interface.py, ball_butler_node.py, etc.)",
        "To regenerate: python config/generate_config.py",
        '"""',
        "",
        "from enum import IntEnum",
    ]

    # CAN bus
    lines += py_section("CAN Bus Configuration")
    lines.append(f"CAN_BAUD_RATE = {cfg['can_bus']['baud_rate']}  # All nodes must agree")

    # ODrive commands
    lines += py_section("ODrive CAN Protocol — Command IDs (lower 5 bits of arbitration ID)")
    lines.append("ODRIVE_COMMANDS = {")
    for name, val in cfg["odrive"]["commands"].items():
        lines.append(f'    "{name}": {fmt_hex(val)},')
    lines.append("}")

    # ODrive states
    lines += py_section("ODrive Axis States, Control Modes, Input Modes")
    lines.append("ODRIVE_STATES = {")
    for name, val in cfg["odrive"]["states"].items():
        lines.append(f'    "{name}": {val},')
    lines.append("}")
    lines.append("")

    # ODrive control modes
    lines.append("ODRIVE_CONTROL_MODES = {")
    for name, val in cfg["odrive"]["control_modes"].items():
        lines.append(f'    "{name}": {val},')
    lines.append("}")
    lines.append("")

    # ODrive input modes
    lines.append("ODRIVE_INPUT_MODES = {")
    for name, val in cfg["odrive"]["input_modes"].items():
        lines.append(f'    "{name}": {val},')
    lines.append("}")
    lines.append("")

    # ODrive errors
    lines.append("# ODrive error bit masks")
    lines.append("ODRIVE_ERRORS = {")
    for name, val in cfg["odrive"]["errors"].items():
        lines.append(f'    "{name}": {fmt_hex(val)},')
    lines.append("}")

    # Node IDs
    lines += py_section("CAN Node IDs — ODrive axis addresses")
    lines.append(f"NODE_ID_LEGS = {cfg['node_ids']['legs']}")
    lines.append(f"NODE_ID_JUGGLEBOT_HAND = {cfg['node_ids']['jugglebot_hand']}")
    lines.append(f"NODE_ID_BB_PITCH = {cfg['node_ids']['bb_pitch']}")
    lines.append(f"NODE_ID_BB_HAND = {cfg['node_ids']['bb_hand']}")

    # Shared CAN IDs
    lines += py_section("Custom CAN Message IDs")
    lines.append("# Shared IDs — used by both Platform and Ball Butler Teensys")
    for name, val in cfg["can_ids"]["shared"].items():
        lines.append(f"CAN_ID_SHARED_{name} = {fmt_hex(val)}")
    lines.append("")

    # Platform CAN IDs
    lines.append("# Platform Teensy <-> Host")
    for name, val in cfg["can_ids"]["platform"].items():
        lines.append(f"CAN_ID_PLATFORM_{name} = {fmt_hex(val)}")
    lines.append("")

    # Ball Butler CAN IDs
    lines.append("# Ball Butler Teensy <-> Host")
    for name, val in cfg["can_ids"]["ball_butler"].items():
        lines.append(f"CAN_ID_BB_{name} = {fmt_hex(val)}")

    # Ball Butler states (as IntEnum for type safety)
    lines += py_section("Ball Butler State Machine")
    lines.append("# States — encoded in heartbeat byte 0 (bits 1-7)")
    lines.append("class BallButlerStates(IntEnum):")
    for name, val in cfg["ball_butler"]["states"].items():
        lines.append(f"    {name} = {val}")
    lines.append("")

    # Ball Butler errors (as IntEnum)
    lines.append("# Error codes — encoded in heartbeat byte 1 when state == ERROR")
    lines.append("class BallButlerError(IntEnum):")
    for name, val in cfg["ball_butler"]["errors"].items():
        lines.append(f"    {name} = {val}")

    # Heartbeat encoding
    lines += py_section("Encoding / Scaling")
    lines.append("# Ball Butler heartbeat CAN frame encoding resolutions")
    for name, val in cfg["encoding"]["heartbeat"].items():
        lines.append(f"HEARTBEAT_{name.upper()} = {val}")
    lines.append("")

    # Input scales
    lines.append("# ODrive input scaling (vel_ff and torque_ff are sent as int16 * scale)")
    for name, val in cfg["encoding"]["input_scales"].items():
        lines.append(f"INPUT_SCALE_{name.upper()} = {float(val)}")

    # SDO
    lines += py_section("SDO — Arbitrary Parameter Access")
    for name, val in cfg["sdo"].items():
        lines.append(f"{name} = {fmt_hex(val)}")

    # Endpoints
    lines += py_section("Endpoint IDs — ODrive internal parameter addresses")
    for name, val in cfg["endpoints"].items():
        lines.append(f"ENDPOINT_{name.upper()} = {val}")
    lines.append("")

    return "\n".join(lines)


# ── Hardware config generation ─────────────────────────────────────────────

# Each tuple: (yaml_key, py_prefix, cpp_namespace, section_title)
HW_SECTIONS = [
    # 1. Shared Physics
    ("physics",                  "",           "Physics",    "Shared Physics"),
    # 2–6. Jugglebot (Stewart platform)
    ("jugglebot_geometry",       "GEOM_",      "Geometry",   "Jugglebot Stewart Platform Geometry"),
    ("jugglebot_homing",         "HOMING_",    "Homing",     "Jugglebot Homing"),
    ("jugglebot_odrive_defaults","ODRIVE_",    "ODriveDefaults", "Jugglebot ODrive Defaults"),
    ("jugglebot_operational",    "JB_OP_",     "JBOp",       "Jugglebot Operational"),
    ("jugglebot_spacemouse",     "SPACEMOUSE_","Spacemouse", "Jugglebot SpaceMouse"),
    # 7–8. Teensy (platform microcontroller)
    ("teensy_trajectory",        "TEENSY_TRAJ_", "TeensyTraj", "Teensy Trajectory"),
    ("teensy_operational",       "TEENSY_",    "TeensyOp",   "Teensy Operational"),
    # 9. Motion Capture
    ("mocap",                    "MOCAP_",     "Mocap",      "Motion Capture"),
    # 10. Ball Tracking & Prediction
    ("ball_tracking",            "TRACKING_",  "Tracking",   "Ball Tracking & Prediction"),
    # 11–21. Ball Butler
    ("ball_butler_geometry",     "BB_GEOM_",   "BBGeom",     "Ball Butler Geometry & Kinematics"),
    ("ball_butler_trajectory",   "BB_TRAJ_",   "BBTraj",     "Ball Butler Trajectory"),
    ("ball_butler_pins",         "BB_PIN_",    "BBPins",     "Ball Butler Hardware Pins"),
    ("ball_butler_can",          "BB_CAN_",    "BBCan",      "Ball Butler CAN Config"),
    ("ball_butler_yaw",          "BB_YAW_",    "BBYaw",      "Ball Butler Yaw Axis"),
    ("ball_butler_pitch",        "BB_PITCH_",  "BBPitch",    "Ball Butler Pitch Axis"),
    ("ball_butler_hand",         "BB_HAND_",   "BBHand",     "Ball Butler Hand Axis"),
    ("ball_butler_state_machine","BB_SM_",     "BBSM",       "Ball Butler State Machine"),
    ("ball_butler_operational",  "BB_OP_",     "BBOp",       "Ball Butler Operational"),
    ("ball_butler_heartbeat",    "BB_HB_",     "BBHb",       "Ball Butler Heartbeat Encoding"),
    ("ball_butler_ball_detect",  "BB_BD_",     "BBBallDetect","Ball Butler Ball Detection"),
]


def _is_2d_list(val) -> bool:
    """Check if val is a list of lists (2D array)."""
    return isinstance(val, list) and len(val) > 0 and isinstance(val[0], list)


def _cpp_type_and_val(val) -> tuple[str, str]:
    """Return (C++ type, formatted value) for a scalar."""
    if isinstance(val, bool):
        return "bool", "true" if val else "false"
    if isinstance(val, str):
        return "const char*", f'"{val}"'
    if isinstance(val, int):
        if val < 0:
            return "int32_t", str(val)
        return "uint32_t", f"{val}u"
    if isinstance(val, float):
        return "float", f"{val}f"
    return "auto", str(val)


def _py_val(val) -> str:
    """Return formatted Python value for a scalar or list."""
    if isinstance(val, bool):
        return "True" if val else "False"
    return repr(val)


def compute_derived(cfg: dict) -> dict:
    """Compute derived constants from raw hardware config values."""
    derived = {}

    g = cfg["physics"]["gravity_mps2"]
    derived["GRAVITY_MMPS2"] = g * 1000.0

    # Init leg lengths with ball joint offset added
    geom = cfg["jugglebot_geometry"]
    offset = geom["ball_joint_offset_mm"]
    derived["INIT_LEG_LENGTHS_WITH_OFFSET_MM"] = [
        ll + offset for ll in geom["init_leg_lengths_mm"]
    ]

    # Teensy linear gain: rev/m
    tt = cfg["teensy_trajectory"]
    derived["TEENSY_LINEAR_GAIN"] = tt["linear_gain_factor"] / (math.pi * tt["hand_spool_radius_m"] * 2.0)

    # Ball Butler linear gain: rev/m
    bt = cfg["ball_butler_trajectory"]
    derived["BB_LINEAR_GAIN"] = bt["linear_gain_factor"] / (math.pi * bt["hand_spool_radius_m"] * 2.0)

    # Ball Butler trajectory buffer sizing
    max_throw_samples = int(bt["max_throw_duration_s"] * bt["sample_rate_hz"]) + 1
    derived["BB_MAX_THROW_SAMPLES"] = max_throw_samples
    derived["BB_MAX_TRAJ_FRAMES"] = max_throw_samples + bt["max_smooth_samples"] + bt["max_pause_samples"]

    return derived


def generate_hw_python(cfg: dict) -> str:
    """Generate hardware_config.py from hardware_config.yaml."""
    lines = [
        '"""',
        "AUTO-GENERATED by generate_config.py — DO NOT EDIT",
        "Source: config/hardware_config.yaml",
        "",
        "Centralised hardware & geometry constants for the Jugglebot system.",
        "Consumed by: ROS2 Python nodes (motion planner, CAN node, mocap, etc.)",
        "To regenerate: python config/generate_config.py",
        '"""',
        "",
        "import math",
    ]

    for yaml_key, py_prefix, _, section_title in HW_SECTIONS:
        section = cfg.get(yaml_key, {})
        if not section:
            continue
        lines += py_section(section_title)
        for key, val in section.items():
            name = f"{py_prefix}{key.upper()}"
            if _is_2d_list(val):
                lines.append(f"{name} = [")
                for row in val:
                    lines.append(f"    {row},")
                lines.append("]")
            elif isinstance(val, list):
                lines.append(f"{name} = {val}")
            else:
                lines.append(f"{name} = {_py_val(val)}")

    # Derived constants
    derived = compute_derived(cfg)
    lines += py_section("Derived Constants (computed by generator)")
    lines.append(f"GRAVITY_MMPS2 = {derived['GRAVITY_MMPS2']}")
    lines.append(f"INIT_LEG_LENGTHS_WITH_OFFSET_MM = {derived['INIT_LEG_LENGTHS_WITH_OFFSET_MM']}")
    lines.append(f"TEENSY_LINEAR_GAIN = {derived['TEENSY_LINEAR_GAIN']}")
    lines.append(f"BB_LINEAR_GAIN = {derived['BB_LINEAR_GAIN']}")
    lines.append(f"BB_MAX_THROW_SAMPLES = {derived['BB_MAX_THROW_SAMPLES']}")
    lines.append(f"BB_MAX_TRAJ_FRAMES = {derived['BB_MAX_TRAJ_FRAMES']}")
    lines.append("")

    return "\n".join(lines)


def generate_hw_cpp(cfg: dict) -> str:
    """Generate hardware_config.h from hardware_config.yaml."""
    lines = [
        "#pragma once",
        "// AUTO-GENERATED by generate_config.py — DO NOT EDIT",
        "// Source: config/hardware_config.yaml",
        "//",
        "// Centralised hardware & geometry constants for the Jugglebot system.",
        "// Consumed by: Ball Butler firmware, Platform Teensy firmware, ROS2 (via Python).",
        "// To regenerate: python config/generate_config.py",
        "",
        "#include <cstdint>",
        "#include <cmath>",
        "",
        "#ifndef M_PI",
        "#define M_PI 3.14159265358979323846",
        "#endif",
    ]

    for yaml_key, _, cpp_ns, section_title in HW_SECTIONS:
        section = cfg.get(yaml_key, {})
        if not section:
            continue
        lines += cpp_section(section_title)
        lines.append(f"namespace {cpp_ns} {{")
        for key, val in section.items():
            cpp_name = key.upper()
            if _is_2d_list(val):
                rows = len(val)
                cols = len(val[0])
                lines.append(f"  constexpr float {cpp_name}[{rows}][{cols}] = {{")
                for row in val:
                    formatted = ", ".join(f"{v}f" for v in row)
                    lines.append(f"    {{{formatted}}},")
                lines.append("  };")
            elif isinstance(val, list):
                count = len(val)
                ctype, _ = _cpp_type_and_val(val[0])
                if ctype == "float":
                    formatted = ", ".join(f"{v}f" for v in val)
                else:
                    formatted = ", ".join(str(v) for v in val)
                lines.append(f"  constexpr {ctype} {cpp_name}[{count}] = {{{formatted}}};")
            else:
                ctype, cval = _cpp_type_and_val(val)
                lines.append(f"  constexpr {ctype} {cpp_name} = {cval};")
        lines.append("}")

    # NOTE: Derived constants (LINEAR_GAIN, MAX_THROW_SAMPLES, etc.) are intentionally
    # omitted from the C++ output. Both firmwares derive these locally from source
    # constants — see BallButlerConfig.h TrajCfg namespace and Trajectory.h.
    # Python derived constants are still generated in generate_hw_python().
    lines.append("")

    return "\n".join(lines)


# ── Main ────────────────────────────────────────────────────────────────────

def main():
    yaml_path = Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_YAML
    if not yaml_path.exists():
        print(f"Error: YAML file not found: {yaml_path}", file=sys.stderr)
        sys.exit(1)

    cfg = load_yaml(yaml_path)
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    # ── Protocol config ──
    cpp_path = OUTPUT_DIR / "protocol_config.h"
    py_path = OUTPUT_DIR / "protocol_config.py"

    cpp_content = generate_cpp(cfg)
    py_content = generate_python(cfg)

    cpp_path.write_text(cpp_content, encoding="utf-8")
    py_path.write_text(py_content, encoding="utf-8")

    print(f"Generated: {cpp_path}")
    print(f"Generated: {py_path}")

    # Copy protocol files to consumer directories
    extra_copies = [
        (cpp_content, BB_FIRMWARE_DIR / "protocol_config.h"),
        (cpp_content, PLATFORM_FIRMWARE_DIR / "protocol_config.h"),
        (py_content, ROS_PKG_DIR / "protocol_config.py"),
    ]
    for content, dest in extra_copies:
        if dest.parent.exists():
            dest.write_text(content, encoding="utf-8")
            print(f"Copied:    {dest}")
        else:
            print(f"Skipped (dir not found): {dest}")

    # ── Hardware config ──
    if HW_YAML.exists():
        hw_cfg = load_yaml(HW_YAML)

        hw_cpp_path = OUTPUT_DIR / "hardware_config.h"
        hw_py_path = OUTPUT_DIR / "hardware_config.py"

        hw_cpp_content = generate_hw_cpp(hw_cfg)
        hw_py_content = generate_hw_python(hw_cfg)

        hw_cpp_path.write_text(hw_cpp_content, encoding="utf-8")
        hw_py_path.write_text(hw_py_content, encoding="utf-8")

        print(f"Generated: {hw_cpp_path}")
        print(f"Generated: {hw_py_path}")

        # Copy hardware config to consumer directories
        hw_copies = [
            (hw_cpp_content, BB_FIRMWARE_DIR / "hardware_config.h"),
            (hw_cpp_content, PLATFORM_FIRMWARE_DIR / "hardware_config.h"),
            (hw_py_content, ROS_PKG_DIR / "hardware_config.py"),
        ]
        for content, dest in hw_copies:
            if dest.parent.exists():
                dest.write_text(content, encoding="utf-8")
                print(f"Copied:    {dest}")
            else:
                print(f"Skipped (dir not found): {dest}")
    else:
        print(f"Skipped hardware config (not found): {HW_YAML}")


if __name__ == "__main__":
    main()
