#!/usr/bin/env python3
"""
generate_config.py -- Generate C++, Python, and JS constants from YAML config files.

Usage:
    python generate_config.py                  # generate all configs
    python generate_config.py path/to/yaml     # specify protocol YAML only
    python generate_config.py --check          # drift gate: render in memory,
                                               # diff every artifact and
                                               # delivered copy, WRITE NOTHING.
                                               # exit 0 = fresh, 1 = drift.

The exit code covers IN-REPO destinations only. `../BallButler` is a separate
git checkout on its own branch; its drift prints as `EXTERNAL DRIFT:` and is
never allowed to fail this repo's gate or raise its bring-up banner. Anything
that could not be checked (absent parent dir, missing hardware YAML) prints as
`SKIPPED:` / `NOT CHECKED:` so a partial run can never masquerade as a clean one.

The --check gate is dependency-light on purpose (stdlib + PyYAML only, no
numpy/casadi): jugglebot_launch.py runs it with the system python3.8, which
is not the project venv.  Pinned by tests/firmware/test_config_drift.py.

Outputs:
    config/generated/protocol_config.h          (C++ constexpr header)
    config/generated/protocol_config.py         (Python constants module)
    config/generated/hardware_config.h         (C++ constexpr header)
    config/generated/hardware_config.py        (Python constants module)
    config/generated/geometry-config.js        (ES module for web GUI)
    ros_ws/gui/js/geometry-config.js           (delivered copy)
"""

from __future__ import annotations

import math
import sys
from pathlib import Path
import yaml

SCRIPT_DIR = Path(__file__).resolve().parent
REPO_ROOT = SCRIPT_DIR.parent
DEFAULT_YAML = SCRIPT_DIR / "protocol_config.yaml"
HW_YAML = SCRIPT_DIR / "hardware_config.yaml"
OUTPUT_DIR = SCRIPT_DIR / "generated"

# Additional output locations so consumers can import/include directly
ROS_PKG_DIR = REPO_ROOT / "ros_ws" / "src" / "jugglebot" / "jugglebot"
BB_FIRMWARE_DIR = REPO_ROOT.parent / "BallButler" / "ball_butler_main"
PLATFORM_FIRMWARE_DIR = REPO_ROOT / "ros_ws" / "src" / "jugglebot" / "Teensy_code_platform"
CATCHING_CONE_FIRMWARE_DIR = REPO_ROOT / "ros_ws" / "src" / "jugglebot" / "CatchingCone_code"
CANBRIDGE_FIRMWARE_DIR = REPO_ROOT / "ros_ws" / "src" / "jugglebot" / "Teensy_code_canbridge"
GUI_JS_DIR = REPO_ROOT / "ros_ws" / "gui" / "js"


def load_yaml(path: Path) -> dict:
    with open(path, "r") as f:
        return yaml.safe_load(f)


def fmt_hex(v) -> str:
    """Format an integer as 0x.. hex (minimal digits, no zero-padding), or float as-is."""
    if isinstance(v, int):
        return f"0x{v:02X}" if v <= 0xFF else f"0x{v:X}"
    return str(v)


# ── C++ generation ──────────────────────────────────────────────────────────

def cpp_section(title: str) -> list[str]:
    """Return a C++ section-divider comment block."""
    bar = "// " + "=" * 74
    return ["", bar, f"// {title}", bar, ""]


def generate_cpp(cfg: dict) -> str:
    lines = [
        "#pragma once",
        "// AUTO-GENERATED by generate_config.py — DO NOT EDIT",
        "// Source: config/protocol_config.yaml",
        "//",
        "// Shared protocol constants for the Jugglebot CAN bus.",
        "// Consumed by: Ball Butler firmware, Platform Teensy firmware, ROS2 Python.",
        "// To regenerate: python config/generate_config.py",
        "",
        "#include <cstdint>",
    ]

    # CAN bus
    lines += cpp_section("CAN Bus Configuration")
    lines.append("namespace CanBus {")
    can_bus = cfg['can_bus']
    lines.append(f"  constexpr uint32_t BAUD_RATE = {can_bus['baud_rate']}u;  // All nodes must agree")
    lines.append(f"  constexpr uint32_t BITS_PER_FRAME_APPROX = {can_bus['bits_per_frame_approx']}u;  // Approx bits per 8-byte CAN frame")
    lines.append("}")

    # ODrive commands
    lines += cpp_section("ODrive CAN Protocol — Command IDs (lower 5 bits of arbitration ID)")
    lines.append("namespace ODriveCmd {")
    for name, val in cfg["odrive"]["commands"].items():
        lines.append(f"  constexpr uint8_t {name} = {fmt_hex(val)};")
    lines.append("}")

    # ODrive states
    lines += cpp_section("ODrive Axis States")
    lines.append("namespace ODriveState {")
    for name, val in cfg["odrive"]["states"].items():
        lines.append(f"  constexpr uint32_t {name} = {val}u;")
    lines.append("}")

    # ODrive control modes
    lines.append("")
    lines.append("// ODrive control modes")
    lines.append("namespace ODriveControlMode {")
    for name, val in cfg["odrive"]["control_modes"].items():
        lines.append(f"  constexpr uint32_t {name} = {val}u;")
    lines.append("}")

    # ODrive input modes
    lines.append("")
    lines.append("// ODrive input modes")
    lines.append("namespace ODriveInputMode {")
    for name, val in cfg["odrive"]["input_modes"].items():
        lines.append(f"  constexpr uint32_t {name} = {val}u;")
    lines.append("}")

    # ODrive errors
    lines.append("")
    lines.append("// ODrive error bit masks")
    lines.append("namespace ODriveErrors {")
    for name, val in cfg["odrive"]["errors"].items():
        lines.append(f"  constexpr uint32_t {name} = {fmt_hex(val)}u;")
    lines.append("}")

    # Node IDs
    lines += cpp_section("CAN Node IDs — ODrive axis addresses")
    lines.append("namespace NodeId {")
    legs = cfg["node_ids"]["legs"]
    for i, nid in enumerate(legs):
        lines.append(f"  constexpr uint8_t LEG_{i} = {nid};")
    lines.append(f"  constexpr uint8_t JUGGLEBOT_HAND = {cfg['node_ids']['jugglebot_hand']};")
    lines.append(f"  constexpr uint8_t BB_PITCH = {cfg['node_ids']['bb_pitch']};")
    lines.append(f"  constexpr uint8_t BB_HAND = {cfg['node_ids']['bb_hand']};")
    lines.append("}")

    # Shared CAN IDs
    lines += cpp_section("Custom CAN Message IDs")
    lines.append("// Shared IDs — used by both Platform and Ball Butler Teensys")
    lines.append("namespace SharedCanId {")
    for name, val in cfg["can_ids"]["shared"].items():
        lines.append(f"  constexpr uint32_t {name} = {fmt_hex(val)};")
    lines.append("}")

    # Platform CAN IDs
    lines.append("")
    lines.append("// Platform Teensy <-> Host")
    lines.append("namespace PlatformCanId {")
    for name, val in cfg["can_ids"]["platform"].items():
        lines.append(f"  constexpr uint32_t {name} = {fmt_hex(val)};")
    lines.append("}")

    # Ball Butler CAN IDs
    lines.append("")
    lines.append("// Ball Butler Teensy <-> Host")
    lines.append("namespace BallButlerCanId {")
    for name, val in cfg["can_ids"]["ball_butler"].items():
        lines.append(f"  constexpr uint32_t {name} = {fmt_hex(val)};")
    lines.append("}")

    # Catching Cone CAN IDs
    lines.append("")
    lines.append("// Catching Cone Teensy <-> Host")
    lines.append("namespace CatchingConeCanId {")
    for name, val in cfg["can_ids"]["catching_cone"].items():
        lines.append(f"  constexpr uint32_t {name} = {fmt_hex(val)};")
    lines.append("}")

    # Ball Butler scalar constants
    lines += cpp_section("Ball Butler State Machine")
    lines.append("namespace BallButler {")
    for name, val in cfg["ball_butler"].items():
        if not isinstance(val, dict):
            ctype, cval = _cpp_type_and_val(val)
            lines.append(f"  constexpr {ctype} {name.upper()} = {cval};")
    lines.append("}")
    lines.append("")

    # Ball Butler states
    lines.append("// States — encoded in heartbeat byte 0 (bits 1-7)")
    lines.append("namespace BallButlerState {")
    for name, val in cfg["ball_butler"]["states"].items():
        lines.append(f"  constexpr uint8_t {name} = {val};")
    lines.append("}")

    # Ball Butler errors
    lines.append("")
    lines.append("// Error codes — encoded in heartbeat byte 1 when state == ERROR")
    lines.append("namespace BallButlerErrorCode {")
    for name, val in cfg["ball_butler"]["errors"].items():
        lines.append(f"  constexpr uint8_t {name} = {val};")
    lines.append("}")

    # Ball Butler command-outcome channel (CMD_RESULT frame)
    lines.append("")
    lines.append("// Command types — CMD_RESULT byte 0 (which operation the result is for)")
    lines.append("namespace BallButlerCommandType {")
    for name, val in cfg["ball_butler"]["command_types"].items():
        lines.append(f"  constexpr uint8_t {name} = {val};")
    lines.append("}")
    lines.append("")
    lines.append("// Command outcomes — CMD_RESULT byte 1 (shared base 0x00-0x0F + per-command ext >=0x20)")
    lines.append("namespace BallButlerCommandOutcome {")
    for name, val in cfg["ball_butler"]["command_outcomes"].items():
        lines.append(f"  constexpr uint8_t {name} = {val};")
    lines.append("}")

    # Catching Cone scalar constants + states
    lines += cpp_section("Catching Cone State Machine")
    lines.append("namespace CatchingCone {")
    for name, val in cfg["catching_cone"].items():
        if not isinstance(val, dict):
            ctype, cval = _cpp_type_and_val(val)
            lines.append(f"  constexpr {ctype} {name.upper()} = {cval};")
    lines.append("}")
    lines.append("")
    lines.append("// States — encoded in CONE_HEARTBEAT byte 0")
    lines.append("namespace CatchingConeState {")
    for name, val in cfg["catching_cone"]["states"].items():
        lines.append(f"  constexpr uint8_t {name} = {val};")
    lines.append("}")

    # Heartbeat encoding
    lines += cpp_section("Encoding / Scaling")
    lines.append("// Ball Butler heartbeat CAN frame encoding resolutions")
    lines.append("namespace HeartbeatEncoding {")
    for name, val in cfg["encoding"]["heartbeat"].items():
        lines.append(f"  constexpr float {name} = {val}f;")
    lines.append("}")

    # Input scales
    lines.append("")
    lines.append("// ODrive input scaling (vel_ff and torque_ff are sent as int16 * scale)")
    lines.append("namespace InputScale {")
    scales = cfg["encoding"]["input_scales"]
    for name, val in scales.items():
        lines.append(f"  constexpr float {name} = {float(val)}f;")
    lines.append("}")

    # SDO
    lines += cpp_section("SDO — Arbitrary Parameter Access")
    lines.append("namespace SDO {")
    for name, val in cfg["sdo"].items():
        lines.append(f"  constexpr uint8_t {name} = {fmt_hex(val)};")
    lines.append("}")

    # Endpoints
    lines += cpp_section("Endpoint IDs — ODrive internal parameter addresses")
    lines.append("namespace EndpointId {")
    for group, entries in cfg["endpoints"].items():
        lines.append(f"  namespace {group} {{")
        for name, val in entries.items():
            lines.append(f"    constexpr uint16_t {name} = {val};")
        lines.append("  }")
    lines.append("}")

    # Mocap alignment
    if "mocap_alignment" in cfg:
        lines += cpp_section("Motion Capture Alignment")
        lines.append("namespace MocapAlignment {")
        for name, val in cfg["mocap_alignment"].items():
            ctype, cval = _cpp_type_and_val(val)
            lines.append(f"  constexpr {ctype} {name.upper()} = {cval};")
        lines.append("}")
    lines.append("")

    return "\n".join(lines)


# ── Python generation ───────────────────────────────────────────────────────

def py_section(title: str) -> list[str]:
    """Return a Python section-divider comment block."""
    bar = "# " + "=" * 76
    return ["", bar, f"# {title}", bar, ""]


def generate_python(cfg: dict) -> str:
    lines = [
        '"""',
        "AUTO-GENERATED by generate_config.py — DO NOT EDIT",
        "Source: config/protocol_config.yaml",
        "",
        "Shared protocol constants for the Jugglebot CAN bus.",
        "Consumed by: ROS2 Python nodes (can_interface.py, ball_butler_node.py, etc.)",
        "To regenerate: python config/generate_config.py",
        '"""',
        "",
        "from enum import IntEnum",
    ]

    # CAN bus
    lines += py_section("CAN Bus Configuration")
    can_bus = cfg['can_bus']
    lines.append(f"CAN_BAUD_RATE = {can_bus['baud_rate']}  # All nodes must agree")
    lines.append(f"CAN_BITS_PER_FRAME_APPROX = {can_bus['bits_per_frame_approx']}  # Approx bits per 8-byte CAN frame")

    # ODrive commands
    lines += py_section("ODrive CAN Protocol — Command IDs (lower 5 bits of arbitration ID)")
    lines.append("ODRIVE_COMMANDS = {")
    for name, val in cfg["odrive"]["commands"].items():
        lines.append(f'    "{name}": {fmt_hex(val)},')
    lines.append("}")

    # ODrive states
    lines += py_section("ODrive Axis States, Control Modes, Input Modes")
    lines.append("ODRIVE_STATES = {")
    for name, val in cfg["odrive"]["states"].items():
        lines.append(f'    "{name}": {val},')
    lines.append("}")
    lines.append("")

    # ODrive control modes
    lines.append("ODRIVE_CONTROL_MODES = {")
    for name, val in cfg["odrive"]["control_modes"].items():
        lines.append(f'    "{name}": {val},')
    lines.append("}")
    lines.append("")

    # ODrive input modes
    lines.append("ODRIVE_INPUT_MODES = {")
    for name, val in cfg["odrive"]["input_modes"].items():
        lines.append(f'    "{name}": {val},')
    lines.append("}")
    lines.append("")

    # ODrive errors
    lines.append("# ODrive error bit masks")
    lines.append("ODRIVE_ERRORS = {")
    for name, val in cfg["odrive"]["errors"].items():
        lines.append(f'    "{name}": {fmt_hex(val)},')
    lines.append("}")

    # Node IDs
    lines += py_section("CAN Node IDs — ODrive axis addresses")
    lines.append(f"NODE_ID_LEGS = {cfg['node_ids']['legs']}")
    lines.append(f"NODE_ID_JUGGLEBOT_HAND = {cfg['node_ids']['jugglebot_hand']}")
    lines.append(f"NODE_ID_BB_PITCH = {cfg['node_ids']['bb_pitch']}")
    lines.append(f"NODE_ID_BB_HAND = {cfg['node_ids']['bb_hand']}")

    # Shared CAN IDs
    lines += py_section("Custom CAN Message IDs")
    lines.append("# Shared IDs — used by both Platform and Ball Butler Teensys")
    for name, val in cfg["can_ids"]["shared"].items():
        lines.append(f"CAN_ID_SHARED_{name} = {fmt_hex(val)}")
    lines.append("")

    # Platform CAN IDs
    lines.append("# Platform Teensy <-> Host")
    for name, val in cfg["can_ids"]["platform"].items():
        lines.append(f"CAN_ID_PLATFORM_{name} = {fmt_hex(val)}")
    lines.append("")

    # Ball Butler CAN IDs
    lines.append("# Ball Butler Teensy <-> Host")
    for name, val in cfg["can_ids"]["ball_butler"].items():
        lines.append(f"CAN_ID_BB_{name} = {fmt_hex(val)}")
    lines.append("")

    # Catching Cone CAN IDs
    lines.append("# Catching Cone Teensy <-> Host")
    for name, val in cfg["can_ids"]["catching_cone"].items():
        lines.append(f"CAN_ID_CC_{name} = {fmt_hex(val)}")

    # Ball Butler scalar constants (e.g. heartbeat_timeout_ms)
    lines += py_section("Ball Butler State Machine")
    for name, val in cfg["ball_butler"].items():
        if not isinstance(val, dict):
            lines.append(f"BB_{name.upper()} = {val}")
    lines.append("")

    # Ball Butler states (as IntEnum for type safety)
    lines.append("# States — encoded in heartbeat byte 0 (bits 1-7)")
    lines.append("class BallButlerStates(IntEnum):")
    for name, val in cfg["ball_butler"]["states"].items():
        lines.append(f"    {name} = {val}")
    lines.append("")

    # Ball Butler errors (as IntEnum)
    lines.append("# Error codes — encoded in heartbeat byte 1 when state == ERROR")
    lines.append("class BallButlerError(IntEnum):")
    for name, val in cfg["ball_butler"]["errors"].items():
        lines.append(f"    {name} = {val}")
    lines.append("")

    # Ball Butler command-outcome channel (CMD_RESULT frame)
    lines.append("# Command types — CMD_RESULT byte 0")
    lines.append("class BallButlerCommandType(IntEnum):")
    for name, val in cfg["ball_butler"]["command_types"].items():
        lines.append(f"    {name} = {val}")
    lines.append("")
    lines.append("# Command outcomes — CMD_RESULT byte 1 (shared base + per-command extensions)")
    lines.append("class BallButlerCommandOutcome(IntEnum):")
    for name, val in cfg["ball_butler"]["command_outcomes"].items():
        lines.append(f"    {name} = {val}")

    # Catching Cone scalar constants + states
    lines += py_section("Catching Cone State Machine")
    for name, val in cfg["catching_cone"].items():
        if not isinstance(val, dict):
            lines.append(f"CC_{name.upper()} = {val}")
    lines.append("")
    lines.append("# States — encoded in CONE_HEARTBEAT byte 0")
    lines.append("class CatchingConeStates(IntEnum):")
    for name, val in cfg["catching_cone"]["states"].items():
        lines.append(f"    {name} = {val}")

    # Heartbeat encoding
    lines += py_section("Encoding / Scaling")
    lines.append("# Ball Butler heartbeat CAN frame encoding resolutions")
    for name, val in cfg["encoding"]["heartbeat"].items():
        lines.append(f"HEARTBEAT_{name.upper()} = {val}")
    lines.append("")

    # Input scales
    lines.append("# ODrive input scaling (vel_ff and torque_ff are sent as int16 * scale)")
    for name, val in cfg["encoding"]["input_scales"].items():
        lines.append(f"INPUT_SCALE_{name.upper()} = {float(val)}")
    lines.append("")

    # SDO
    lines += py_section("SDO — Arbitrary Parameter Access")
    for name, val in cfg["sdo"].items():
        lines.append(f"{name} = {fmt_hex(val)}")

    # Endpoints
    lines += py_section("Endpoint IDs — ODrive internal parameter addresses")
    for group, entries in cfg["endpoints"].items():
        for name, val in entries.items():
            lines.append(f"ENDPOINT_{group.upper()}_{name.upper()} = {val}")

    # Mocap alignment
    if "mocap_alignment" in cfg:
        lines += py_section("Motion Capture Alignment")
        for name, val in cfg["mocap_alignment"].items():
            lines.append(f"MOCAP_ALIGNMENT_{name.upper()} = {_py_val(val)}")
    lines.append("")

    return "\n".join(lines)


# ── Hardware config generation ─────────────────────────────────────────────

# Each tuple: (yaml_key, py_prefix, cpp_namespace, section_title)
HW_SECTIONS = [
    # 1. Shared Physics
    ("physics",                  "",           "Physics",    "Shared Physics"),
    # 1b. Platform Dynamics
    ("dynamics",                 "DYNAMICS_",  "Dynamics",   "Platform Dynamics"),
    # 2–3. Jugglebot (Stewart platform geometry, homing)
    ("jugglebot_geometry",       "GEOM_",      "Geometry",   "Jugglebot Stewart Platform Geometry"),
    ("jugglebot_homing",         "HOMING_",    "Homing",     "Jugglebot Homing"),
    # 4. ODrive expected versions
    ("odrive_expected_versions", "ODRIVE_VER_","ODriveVer",  "ODrive Expected Versions"),
    # 5–7. Jugglebot (ODrive defaults, operational, SpaceMouse)
    ("jugglebot_odrive_defaults","ODRIVE_",    "ODriveDefaults", "Jugglebot ODrive Defaults"),
    ("jugglebot_operational",    "JB_OP_",     "JBOp",       "Jugglebot Operational"),
    # MVP Jetson-side trajectory generator limits (JB_TRAJ_*). Without this row a
    # regenerate silently emits no JB_TRAJ_* constants (jugglebot.motion.trajectory
    # imports them). Python-only consumer; the C++ namespace is unused but harmless.
    ("trajectory_op",            "JB_TRAJ_",   "TrajOp",     "Jugglebot Trajectory Operational"),
    ("jugglebot_spacemouse",     "SPACEMOUSE_","Spacemouse", "Jugglebot SpaceMouse"),
    ("jugglebot_gui",            "GUI_",       "GUI",        "Jugglebot GUI"),
    # 7–8. Teensy (platform microcontroller)
    ("teensy_trajectory",        "TEENSY_TRAJ_", "TeensyTraj", "Teensy Trajectory"),
    # 8b. Hand throw ADMISSION envelope (contract C-HAND-3). HOST-SIDE ONLY —
    # jugglebot/motion/trajectory/throw_envelope.py is the sole consumer; no
    # firmware reads HandEnv::, so the emitted C++ namespace is inert (kept only
    # because every section is emitted uniformly). Without this row a regenerate
    # silently emits no HAND_ENV_* constants and the toss gate fails closed at
    # import — which is loud, but at node start rather than at review.
    ("hand_throw_envelope",      "HAND_ENV_",  "HandEnv",    "Hand Throw Envelope"),
    ("teensy_operational",       "TEENSY_",    "TeensyOp",   "Teensy Operational"),
    # 9. Motion Capture
    ("mocap",                    "MOCAP_",     "Mocap",      "Motion Capture"),
    # 10. Ball Tracking & Prediction
    ("ball_tracking",            "TRACKING_",  "Tracking",   "Ball Tracking & Prediction"),
    # 11–21. Ball Butler
    ("ball_butler_geometry",     "BB_GEOM_",   "BBGeom",     "Ball Butler Geometry & Kinematics"),
    ("ball_butler_trajectory",   "BB_TRAJ_",   "BBTraj",     "Ball Butler Trajectory"),
    ("ball_butler_pins",         "BB_PIN_",    "BBPins",     "Ball Butler Hardware Pins"),
    ("ball_butler_can",          "BB_CAN_",    "BBCan",      "Ball Butler CAN Config"),
    ("ball_butler_yaw",          "BB_YAW_",    "BBYaw",      "Ball Butler Yaw Axis"),
    ("ball_butler_pitch",        "BB_PITCH_",  "BBPitch",    "Ball Butler Pitch Axis"),
    ("ball_butler_hand",         "BB_HAND_",   "BBHand",     "Ball Butler Hand Axis"),
    ("ball_butler_state_machine","BB_SM_",     "BBSM",       "Ball Butler State Machine"),
    ("ball_butler_operational",  "BB_OP_",     "BBOp",       "Ball Butler Operational"),
    ("ball_butler_heartbeat",    "BB_HB_",     "BBHb",       "Ball Butler Heartbeat Encoding"),
    ("ball_butler_ball_detect",  "BB_BD_",     "BBBallDetect","Ball Butler Ball Detection"),
    ("jugglebot_ball_detect",    "JB_BD_",     "JBBallDetect","Jugglebot Ball Detection"),
    # 24. Catching Cone
    ("catching_cone",            "CC_",        "CatchingCone","Catching Cone"),
]


def _is_2d_list(val) -> bool:
    """Check if val is a list of lists (2D array)."""
    return isinstance(val, list) and len(val) > 0 and isinstance(val[0], list)


def _cpp_type_and_val(val) -> tuple[str, str]:
    """Return (C++ type, formatted value) for a scalar."""
    if isinstance(val, bool):
        return "bool", "true" if val else "false"
    if isinstance(val, str):
        return "const char*", f'"{val}"'
    if isinstance(val, int):
        if val < 0:
            return "int32_t", str(val)
        return "uint32_t", f"{val}u"
    if isinstance(val, float):
        return "float", f"{val}f"
    return "auto", str(val)


def _py_val(val) -> str:
    """Return formatted Python value for a scalar or list."""
    if isinstance(val, bool):
        return "True" if val else "False"
    return repr(val)


def _check_catching_cone_key_collision(proto_cfg: dict, hw_cfg: dict) -> None:
    """Both YAMLs reopen the `CatchingCone` C++ namespace.

    Scalar key collisions across the two sections would cause a `constexpr`
    redefinition compile error in the firmware (which #includes both
    headers). Raise early with a clear diagnostic instead.
    """
    proto_cc = proto_cfg.get("catching_cone", {})
    hw_cc = hw_cfg.get("catching_cone", {})
    proto_scalars = {k for k, v in proto_cc.items() if not isinstance(v, dict)}
    hw_scalars = {k for k, v in hw_cc.items() if not isinstance(v, dict)}
    collisions = proto_scalars & hw_scalars
    if collisions:
        raise RuntimeError(
            "catching_cone key collision between protocol_config.yaml and "
            f"hardware_config.yaml: {sorted(collisions)} — both reopen the "
            "C++ `CatchingCone` namespace; rename one or move the key."
        )


def compute_derived(cfg: dict) -> dict:
    """Compute derived constants from raw hardware config values."""
    derived = {}

    g = cfg["physics"]["gravity_mps2"]
    derived["GRAVITY_MMPS2"] = g * 1000.0

    # Init leg lengths with ball joint offset added.
    # Legacy: ball_joint_offset_mm is now 0.0, so this equals init_leg_lengths_mm.
    # Kept as a derived alias for backward compatibility with GUI / geometry consumers.
    geom = cfg["jugglebot_geometry"]
    offset = geom["ball_joint_offset_mm"]
    derived["INIT_LEG_LENGTHS_WITH_OFFSET_MM"] = [
        ll + offset for ll in geom["init_leg_lengths_mm"]
    ]

    # Activate position per leg (rev): IK of the active pose [0, 0, default_z, 0, 0, 0].
    # This ensures the gentle-move activation target matches the control loop's
    # active pose exactly, avoiding a position discontinuity at handoff.
    op = cfg["jugglebot_operational"]
    default_z = op["default_active_z_mm"]
    init_height = geom["initial_height_mm"]
    base_nodes = geom["base_nodes_mm"]
    plat_nodes = geom["init_plat_nodes_mm"]
    init_leg_lengths = geom["init_leg_lengths_mm"]
    mm_to_rev = geom["mm_to_rev"]

    platform_centre = [0.0, 0.0, init_height + default_z]
    activate_revs = []
    for i in range(6):
        # Leg vector: platform node (in base frame, identity rotation) - base node
        dx = platform_centre[0] + plat_nodes[i][0] - base_nodes[i][0]
        dy = platform_centre[1] + plat_nodes[i][1] - base_nodes[i][1]
        dz = platform_centre[2] + plat_nodes[i][2] - base_nodes[i][2]
        abs_len = math.sqrt(dx * dx + dy * dy + dz * dz)
        ext_mm = abs_len - init_leg_lengths[i]
        activate_revs.append(ext_mm * mm_to_rev[i])
    derived["ACTIVATE_POSITION_REVS"] = activate_revs

    # Teensy linear gain: rev/m
    tt = cfg["teensy_trajectory"]
    derived["TEENSY_LINEAR_GAIN"] = tt["linear_gain_factor"] / (math.pi * tt["hand_spool_radius_m"] * 2.0)

    # Hand catch/throw positions — derived from Trajectory.h algebra.
    # These are velocity-independent (v_throw cancels out).
    total_stroke = tt["hand_stroke_m"] - 2.0 * tt["stroke_margin_m"]
    ir = tt["inertia_ratio"]
    # Throw: x2 = accelStroke / (ir + 1) + velHold
    throw_vel_hold = tt["throw_vel_hold_pct"] * total_stroke
    throw_accel_stroke = total_stroke - throw_vel_hold
    x2_m = throw_accel_stroke / (ir + 1.0) + throw_vel_hold  # hand pos at ball release
    x3_m = total_stroke  # top of throw stroke (≈ totalStroke)
    # Catch: x5 = x3 - accS * ir / (1 + ir)
    catch_vel_hold = tt["catch_vel_hold_pct"] * total_stroke
    catch_accel_stroke = total_stroke - catch_vel_hold
    x5_m = x3_m - catch_accel_stroke * ir / (1.0 + ir)  # hand pos at ball catch
    derived["HAND_THROW_POS_M"] = round(x2_m, 6)   # x2: hand position at ball release
    derived["HAND_CATCH_POS_M"] = round(x5_m, 6)   # x5: hand position at ball catch

    # x3, in REV — the reference the hand-catch prime position must equal.
    #
    # Unit deviation from its x2/x5 siblings above is deliberate: the quantity it
    # guards (jugglebot_operational.hand_catch_prime_rev) is a rev, and a drift
    # guard that has to multiply by a gain to compare is exactly where a rev/mm
    # slip hides. Emitted in the unit of the comparison, not the unit of the
    # siblings.
    #
    # x3 = accelStroke + velHold = totalStroke holds ALGEBRAICALLY, independent of
    # the commanded velocity (the decel segment contributes 0.5*INERTIA_RATIO*v*t_acc,
    # so x3 = 0.5*v*t_acc*(1 + INERTIA_RATIO) + velHold = accelSt + velHold). That is
    # why it can be written down here at all, with no velocity in scope.
    derived["HAND_STROKE_TOP_REV"] = x3_m * derived["TEENSY_LINEAR_GAIN"]

    # Hand catch offset: height of hand catch point above platform centroid (mm)
    hand_bottom = geom["hand_axis_bottom_offset_mm"]
    derived["HAND_CATCH_OFFSET_MM"] = round(hand_bottom + x5_m * 1000.0, 2)

    # Ball Butler linear gain: rev/m
    bt = cfg["ball_butler_trajectory"]
    derived["BB_LINEAR_GAIN"] = bt["linear_gain_factor"] / (math.pi * bt["hand_spool_radius_m"] * 2.0)

    # Ball Butler trajectory buffer sizing
    max_throw_samples = int(bt["max_throw_duration_s"] * bt["sample_rate_hz"]) + 1
    derived["BB_MAX_THROW_SAMPLES"] = max_throw_samples
    derived["BB_MAX_TRAJ_FRAMES"] = max_throw_samples + bt["max_smooth_samples"] + bt["max_pause_samples"]

    # ── Leg torque-feedforward wire scale (Nm_true → Nm_odrive) ──────────────
    # The leg ODrives are flashed with torque_constant = 8.27/Kv = 0.055133 (ODrive's
    # uncalibrated nameplate default), while the motor's measured Kt (see motor_kt_nm_per_a in the YAML — 0.0570 since 2026-07-15)
    # Nm/A.  The drive computes  iq = input_torque / torque_constant.  So to make it
    # deliver the current that actually produces a TRUE shaft torque T:
    #     iq_wanted   = T / Kt_measured
    #     input_torque = iq_wanted × torque_constant = T × (torque_constant / Kt_measured)
    # Hence every leg torque feedforward is multiplied by this scale on its way to the
    # wire.  Doing it here (software) instead of re-flashing torque_constant leaves the
    # bench-validated velocity loop (vel_gain / torque_constant amps per rev/s) exactly
    # as it was validated.  See the long WHY block in hardware_config.yaml:dynamics.
    #
    # Sole enforcement point: teensy_link/setpoint_pump.py (the only
    # production producer of the leg Setpoint frame).  The direct-CAN bench harnesses
    # (single_leg_test, friction_ff_demo, free/supported_platform_test) build their own
    # frames and BYPASS it — they must apply this scale themselves if they ever send a
    # torque feedforward derived from a TRUE-Nm model.
    dyn = cfg["dynamics"]
    derived["ODRIVE_LEG_TORQUE_WIRE_SCALE"] = (
        dyn["motor_kt_odrive_config_nm_per_a"] / dyn["motor_kt_nm_per_a"])

    return derived


def generate_hw_python(cfg: dict) -> str:
    """Generate hardware_config.py from hardware_config.yaml."""
    lines = [
        '"""',
        "AUTO-GENERATED by generate_config.py — DO NOT EDIT",
        "Source: config/hardware_config.yaml",
        "",
        "Centralised hardware & geometry constants for the Jugglebot system.",
        "Consumed by: ROS2 Python nodes (motion planner, CAN node, mocap, etc.)",
        "To regenerate: python config/generate_config.py",
        '"""',
        "",
        "import math",
    ]

    for yaml_key, py_prefix, _, section_title in HW_SECTIONS:
        section = cfg.get(yaml_key, {})
        if not section:
            continue
        lines += py_section(section_title)
        for key, val in section.items():
            name = f"{py_prefix}{key.upper()}"
            if isinstance(val, dict):
                # Flatten nested dict: PARENT_CHILD = val
                for sub_key, sub_val in val.items():
                    sub_name = f"{name}_{sub_key.upper()}"
                    lines.append(f"{sub_name} = {_py_val(sub_val)}")
            elif _is_2d_list(val):
                lines.append(f"{name} = [")
                for row in val:
                    lines.append(f"    {row},")
                lines.append("]")
            elif isinstance(val, list):
                lines.append(f"{name} = {val}")
            else:
                lines.append(f"{name} = {_py_val(val)}")

    # Derived constants
    derived = compute_derived(cfg)
    lines += py_section("Derived Constants (computed by generator)")
    lines.append(f"GRAVITY_MMPS2 = {derived['GRAVITY_MMPS2']}")
    lines.append(f"INIT_LEG_LENGTHS_WITH_OFFSET_MM = {derived['INIT_LEG_LENGTHS_WITH_OFFSET_MM']}")
    lines.append(f"JB_OP_ACTIVATE_POSITION_REVS = {derived['ACTIVATE_POSITION_REVS']}")
    lines.append(f"TEENSY_LINEAR_GAIN = {derived['TEENSY_LINEAR_GAIN']}")
    lines.append(f"HAND_THROW_POS_M = {derived['HAND_THROW_POS_M']}")
    lines.append(f"HAND_CATCH_POS_M = {derived['HAND_CATCH_POS_M']}")
    lines.append(f"HAND_CATCH_OFFSET_MM = {derived['HAND_CATCH_OFFSET_MM']}")
    lines.append("# x3 (rev): throw-stroke end AND catch-trajectory first sample.")
    lines.append("# JB_OP_HAND_CATCH_PRIME_REV above MUST equal this — see the YAML")
    lines.append("# comment on jugglebot_operational.hand_catch_prime_rev.")
    lines.append(f"HAND_STROKE_TOP_REV = {derived['HAND_STROKE_TOP_REV']!r}")
    lines.append(f"BB_LINEAR_GAIN = {derived['BB_LINEAR_GAIN']}")
    lines.append(f"BB_MAX_THROW_SAMPLES = {derived['BB_MAX_THROW_SAMPLES']}")
    lines.append(f"BB_MAX_TRAJ_FRAMES = {derived['BB_MAX_TRAJ_FRAMES']}")
    lines.append("# Leg torque-FF wire scale: Nm_true → Nm_odrive")
    lines.append("# = DYNAMICS_MOTOR_KT_ODRIVE_CONFIG_NM_PER_A / DYNAMICS_MOTOR_KT_NM_PER_A.")
    lines.append("# Applied ONCE, in teensy_link/setpoint_pump.py.")
    lines.append(
        f"ODRIVE_LEG_TORQUE_WIRE_SCALE = {derived['ODRIVE_LEG_TORQUE_WIRE_SCALE']!r}")
    lines.append("")

    return "\n".join(lines)


def generate_hw_cpp(cfg: dict) -> str:
    """Generate hardware_config.h from hardware_config.yaml."""
    lines = [
        "#pragma once",
        "// AUTO-GENERATED by generate_config.py — DO NOT EDIT",
        "// Source: config/hardware_config.yaml",
        "//",
        "// Centralised hardware & geometry constants for the Jugglebot system.",
        "// Consumed by: Ball Butler firmware, Platform Teensy firmware, ROS2 (via Python).",
        "// To regenerate: python config/generate_config.py",
        "",
        "#include <cstdint>",
        "#include <cmath>",
        "",
        "#ifndef M_PI",
        "#define M_PI 3.14159265358979323846",
        "#endif",
    ]

    for yaml_key, _, cpp_ns, section_title in HW_SECTIONS:
        section = cfg.get(yaml_key, {})
        if not section:
            continue
        lines += cpp_section(section_title)
        lines.append(f"namespace {cpp_ns} {{")
        for key, val in section.items():
            cpp_name = key.upper()
            if isinstance(val, dict):
                # Flatten nested dict: PARENT_CHILD = val
                for sub_key, sub_val in val.items():
                    sub_cpp_name = f"{cpp_name}_{sub_key.upper()}"
                    ctype, cval = _cpp_type_and_val(sub_val)
                    lines.append(f"  constexpr {ctype} {sub_cpp_name} = {cval};")
            elif _is_2d_list(val):
                rows = len(val)
                cols = len(val[0])
                lines.append(f"  constexpr float {cpp_name}[{rows}][{cols}] = {{")
                for row in val:
                    formatted = ", ".join(f"{v}f" for v in row)
                    lines.append(f"    {{{formatted}}},")
                lines.append("  };")
            elif isinstance(val, list):
                count = len(val)
                ctype, _ = _cpp_type_and_val(val[0])
                if ctype == "float":
                    formatted = ", ".join(f"{v}f" for v in val)
                else:
                    formatted = ", ".join(str(v) for v in val)
                lines.append(f"  constexpr {ctype} {cpp_name}[{count}] = {{{formatted}}};")
            else:
                ctype, cval = _cpp_type_and_val(val)
                lines.append(f"  constexpr {ctype} {cpp_name} = {cval};")
        lines.append("}")

    # NOTE: Derived constants (LINEAR_GAIN, MAX_THROW_SAMPLES, etc.) are intentionally
    # omitted from the C++ output. Both firmwares derive these locally from source
    # constants — see BallButlerConfig.h TrajCfg namespace and Trajectory.h.
    # Python derived constants are still generated in generate_hw_python().
    #
    # EXCEPTION: JBOp::ACTIVATE_POSITION_REVS. The can-bridge firmware's TRAP_TRAJ
    # activate op (leg_activate.cpp) moves each leg to the active pose, and that
    # target MUST match the control loop's active pose exactly (it is the IK of
    # [0,0,default_active_z,0,0,0]) — re-deriving it in firmware would risk drift.
    # So the single derived array the can-bridge needs is emitted into JBOp here.
    derived = compute_derived(cfg)
    activate_revs = derived["ACTIVATE_POSITION_REVS"]
    lines += cpp_section("Derived Constants (computed by generator)")
    lines.append("namespace JBOp {")
    formatted = ", ".join(f"{v}f" for v in activate_revs)
    lines.append(f"  constexpr float ACTIVATE_POSITION_REVS[{len(activate_revs)}] = "
                 f"{{{formatted}}};")
    lines.append("}")
    lines.append("")

    return "\n".join(lines)


# ── GUI JavaScript generation ──────────────────────────────────────────────

def _js_array(val, indent=4) -> str:
    """Format a Python list as a JS array literal."""
    pad = " " * indent
    if _is_2d_list(val):
        rows = [f"{pad}[{', '.join(str(v) for v in row)}]" for row in val]
        return "[\n" + ",\n".join(rows) + ",\n]"
    return "[" + ", ".join(str(v) for v in val) + "]"


def generate_gui_js(hw_cfg: dict, proto_cfg: dict) -> str:
    """Generate geometry-config.js for the web GUI from both YAML configs.

    Reads:
      - hardware_config.yaml  -> Stewart geometry, ODrive limits
      - protocol_config.yaml  -> ODrive states, BB states
    """
    geom = hw_cfg["jugglebot_geometry"]
    derived = compute_derived(hw_cfg)

    can_bus = proto_cfg['can_bus']

    lines = [
        "/**",
        " * geometry-config.js -- AUTO-GENERATED by generate_config.py -- DO NOT EDIT",
        " *",
        " * GUI constants from config/hardware_config.yaml and config/protocol_config.yaml.",
        " * To regenerate: python config/generate_config.py",
        " */",
        "",
        "// ---- CAN bus (protocol_config.yaml -> can_bus) ----",
        "",
        f"export const CAN_BAUD_RATE = {can_bus['baud_rate']};",
        f"export const CAN_BITS_PER_FRAME_APPROX = {can_bus['bits_per_frame_approx']};",
        "",
        "// ---- Stewart platform geometry (hardware_config.yaml -> jugglebot_geometry) ----",
        "",
        f"export const INITIAL_HEIGHT_MM = {geom['initial_height_mm']};",
        f"export const BASE_RADIUS_MM = {geom['base_radius_mm']};",
        f"export const PLAT_RADIUS_MM = {geom['plat_radius_mm']};",
        f"export const LEG_STROKE_MM = {geom['leg_stroke_mm']};",
        f"export const BALL_JOINT_OFFSET_MM = {geom['ball_joint_offset_mm']};",
        "",
        "// Arm / hand structure",
        f"export const ARM_RADIUS_MM = {geom['arm_radius_mm']};",
        f"export const ARM_HEIGHT_FROM_PLATFORM_MM = {geom['arm_height_from_platform_mm']};",
        f"export const HAND_STROKE_MM = {geom['hand_stroke_mm']};",
        f"export const HAND_RADIUS_MM = {geom['hand_radius_mm']};",
        "",
        f"// Base node positions in the base frame (mm)",
        f"export const BASE_NODES_MM = {_js_array(geom['base_nodes_mm'])};",
        "",
        f"// Initial platform node positions in the platform frame (mm)",
        f"export const INIT_PLAT_NODES_MM = {_js_array(geom['init_plat_nodes_mm'])};",
        "",
        f"// Initial leg lengths (mm) — geometry-derived joint-centre-to-joint-centre at STOW",
        f"export const INIT_LEG_LENGTHS_MM = {_js_array(geom['init_leg_lengths_mm'])};",
        "",
        f"// Init leg lengths WITH ball joint offset added (legacy: offset=0, so equals INIT_LEG_LENGTHS_MM)",
        f"export const INIT_LEG_LENGTHS_WITH_OFFSET_MM = {_js_array(derived['INIT_LEG_LENGTHS_WITH_OFFSET_MM'])};",
        "",
        f"// Per-leg mm-to-revolutions conversion factors",
        f"export const MM_TO_REV = {_js_array(geom['mm_to_rev'])};",
        "",
        f"// Motor position limits",
        f"export const LEG_MOTOR_MAX_POS_REVS = {geom['leg_motor_max_position_revs']};",
        f"export const HAND_MOTOR_HARD_STOP_REVS = {geom['hand_motor_hard_stop_revs']};",
        "",
        "// Ball Butler position relative to base centre (mm).",
        "// Placeholder -- updated dynamically via bb/calibration_result topic.",
        "export const BB_POSITION_MM = [0, -500, 0];",
        "",
        "// Hand axis: offset from platform centre along platform normal (mm)",
        "export const HAND_DEPTH_OFFSET_MM = 100.0;",
    ]

    # Operational constants for GUI
    jb_op = hw_cfg["jugglebot_operational"]
    lines += [
        "",
        "// ---- Jugglebot operational (hardware_config.yaml -> jugglebot_operational) ----",
        "",
        f"export const DEFAULT_ACTIVE_Z_MM = {jb_op['default_active_z_mm']};",
    ]

    # Ball Butler geometry constants (for 3D visualisation)
    bb_geom = hw_cfg["ball_butler_geometry"]
    bb_traj = hw_cfg["ball_butler_trajectory"]
    bb_hand_stroke_mm = round(bb_traj["hand_stroke_m"] * 1000, 1)
    lines += [
        "",
        "// ---- Ball Butler geometry (hardware_config.yaml -> ball_butler_geometry) ----",
        "",
        f"export const BB_YAW_S_OFFSET_MM = {bb_geom['yaw_s_offset_mm']};",
        f"export const BB_PITCH_D_OFFSET_MM = {bb_geom['pitch_d_offset_mm']};",
        f"export const BB_RELEASE_L_POSITION_MM = {bb_geom['release_l_position_mm']};",
        f"export const BB_PITCH_Z_OFFSET_MM = {bb_geom['pitch_z_offset_mm']};",
        "",
        "// Ball Butler trajectory",
        f"export const BB_HAND_STROKE_MM = {bb_hand_stroke_mm};",
    ]

    # Catching cone panel constants (delta thresholds + sound-bar axis)
    cc = hw_cfg.get("catching_cone", {})
    if cc:
        lines += [
            "",
            "// ---- Catching cone (hardware_config.yaml -> catching_cone) ----",
            "",
            f"export const CC_DELTA_OK_MS = {cc['delta_ok_ms']};",
            f"export const CC_DELTA_WARN_MS = {cc['delta_warn_ms']};",
            f"export const CC_OFFSET_DISPLAY_LIMIT_MS = {cc['offset_display_limit_ms']};",
            f"export const CC_OFFSET_HISTORY_LEN = {cc['offset_history_len']};",
        ]

    # ODrive states from protocol config
    lines += [
        "",
        "// ---- ODrive state enum (protocol_config.yaml -> odrive.states) ----",
        "",
        "export const ODRIVE_STATE = {",
    ]
    # Include all standard ODrive states (protocol only lists the ones we use,
    # so we keep the full enum for the GUI's visual status dots)
    odrive_known = {
        "UNDEFINED": 0,
        "IDLE": 1,
        "STARTUP_SEQUENCE": 2,
        "FULL_CALIBRATION": 3,
        "MOTOR_CALIBRATION": 4,
        "ENCODER_INDEX_SEARCH": 6,
        "ENCODER_OFFSET_CALIBRATION": 7,
        "CLOSED_LOOP": 8,
        "LOCKIN_SPIN": 9,
        "ENCODER_DIR_FIND": 10,
        "HOMING": 11,
        "ENCODER_HALL_POLARITY": 12,
        "ENCODER_HALL_PHASE": 13,
    }
    # Merge YAML values (in case they differ or new ones are added)
    if "odrive" in proto_cfg and "states" in proto_cfg["odrive"]:
        odrive_known.update(proto_cfg["odrive"]["states"])
    for name, val in odrive_known.items():
        lines.append(f"    {name}: {val},")
    lines.append("};")

    # Ball Butler states from protocol config
    lines += [
        "",
        "// ---- Ball Butler states (protocol_config.yaml -> ball_butler.states) ----",
        "",
        "export const BB_STATE = {",
    ]
    for name, val in proto_cfg["ball_butler"]["states"].items():
        lines.append(f"    {name}: {val},")
    lines.append("};")

    lines += [
        "",
        "export const BB_STATE_NAMES = {",
    ]
    for name, val in proto_cfg["ball_butler"]["states"].items():
        display_name = name.replace("_", " ")
        lines.append(f"    {val}: '{display_name}',")
    lines.append("};")

    # Mocap alignment thresholds
    if "mocap_alignment" in proto_cfg:
        lines += [
            "",
            "// ---- Mocap alignment (protocol_config.yaml -> mocap_alignment) ----",
            "",
        ]
        for name, val in proto_cfg["mocap_alignment"].items():
            lines.append(f"export const MOCAP_ALIGNMENT_{name.upper()} = {val};")
    lines.append("")

    return "\n".join(lines)


# ── Main ────────────────────────────────────────────────────────────────────

def _rel(path: Path) -> str:
    """Return a display path relative to the repo root's parent directory."""
    try:
        return str(path.relative_to(REPO_ROOT.parent))
    except ValueError:
        return str(path)


def build_artifacts(yaml_path: Path):
    """Render every artifact in memory; touch nothing on disk.

    Returns ``(plan, skipped, notes, bb_available)`` where

      * ``plan``    -- list of ``(dest_path, content, label)`` in emit order.
                      ``label`` is the verb the write path prints
                      ("Generated" / "Copied" / "Delivered").
      * ``skipped`` -- destinations whose PARENT DIRECTORY is absent. The write
                      path skips these (external repos like ../BallButler are
                      not always checked out), so ``--check`` must skip exactly
                      the same set or it would report permanent false drift.
      * ``notes``   -- informational lines the write path also prints.

    Splitting rendering out of ``main`` is what makes ``--check`` byte-exact by
    construction: check and write consume the SAME plan, so a new artifact can
    never be added to one path and forgotten in the other.
    """
    cfg = load_yaml(yaml_path)

    plan = []
    skipped = []
    notes = []
    bb_available = BB_FIRMWARE_DIR.exists()

    # ── Protocol config ──
    cpp_content = generate_cpp(cfg)
    py_content = generate_python(cfg)
    plan.append((OUTPUT_DIR / "protocol_config.h", cpp_content, "Generated"))
    plan.append((OUTPUT_DIR / "protocol_config.py", py_content, "Generated"))

    # Copy protocol files to consumer directories
    extra_copies = [
        (cpp_content, BB_FIRMWARE_DIR / "protocol_config.h"),
        (cpp_content, PLATFORM_FIRMWARE_DIR / "protocol_config.h"),
        (cpp_content, CATCHING_CONE_FIRMWARE_DIR / "protocol_config.h"),
        (cpp_content, CANBRIDGE_FIRMWARE_DIR / "protocol_config.h"),
        (py_content, ROS_PKG_DIR / "protocol_config.py"),
    ]
    for content, dest in extra_copies:
        if dest.parent.exists():
            plan.append((dest, content, "Copied"))
        else:
            skipped.append(dest)

    # ── Hardware config ──
    hw_cfg = None
    if HW_YAML.exists():
        hw_cfg = load_yaml(HW_YAML)
        _check_catching_cone_key_collision(cfg, hw_cfg)

        hw_cpp_content = generate_hw_cpp(hw_cfg)
        hw_py_content = generate_hw_python(hw_cfg)
        plan.append((OUTPUT_DIR / "hardware_config.h", hw_cpp_content, "Generated"))
        plan.append((OUTPUT_DIR / "hardware_config.py", hw_py_content, "Generated"))

        hw_copies = [
            (hw_cpp_content, BB_FIRMWARE_DIR / "hardware_config.h"),
            (hw_cpp_content, PLATFORM_FIRMWARE_DIR / "hardware_config.h"),
            (hw_cpp_content, CATCHING_CONE_FIRMWARE_DIR / "hardware_config.h"),
            (hw_cpp_content, CANBRIDGE_FIRMWARE_DIR / "hardware_config.h"),
            (hw_py_content, ROS_PKG_DIR / "hardware_config.py"),
        ]
        for content, dest in hw_copies:
            if dest.parent.exists():
                plan.append((dest, content, "Copied"))
            else:
                skipped.append(dest)
    else:
        notes.append(f"Skipped hardware config (not found): {_rel(HW_YAML)}")

    # ── GUI JavaScript config ──
    if hw_cfg is not None:
        gui_js_content = generate_gui_js(hw_cfg, cfg)
        plan.append((OUTPUT_DIR / "geometry-config.js", gui_js_content, "Generated"))

        gui_dest = GUI_JS_DIR / "geometry-config.js"
        if gui_dest.parent.exists():
            plan.append((gui_dest, gui_js_content, "Delivered"))
        else:
            skipped.append(gui_dest)

    return plan, skipped, notes, bb_available


def is_external(dest: Path) -> bool:
    """True for destinations that live OUTSIDE this repository.

    Only ``../BallButler`` qualifies today. The distinction is load-bearing for
    ``--check``: a separate git checkout, on its own branch, at its own commit,
    must NEVER be able to fail this repo's pre-commit gate or raise this repo's
    bring-up banner. Its drift is real and worth printing, but it is fixed by
    running the generator (which delivers into it), not by anything the operator
    of *this* repo did wrong — and no node in this launch reads those files.
    """
    try:
        dest.resolve().relative_to(REPO_ROOT.resolve())
        return False
    except ValueError:
        return True


def check_artifacts(plan):
    """Compare every planned artifact against what is on disk.

    Returns ``(drift, external_drift)``: lists of ``(dest_path, reason)``, split
    so only the in-repo half drives the exit code (see :func:`is_external`).

    READ-ONLY by construction: the only filesystem calls here are ``exists()``
    and ``read_text()``.

    Compares TEXT, not bytes, on purpose. The write path uses
    ``Path.write_text(..., encoding="utf-8")`` with ``newline=None``, which
    translates ``\\n`` to ``os.linesep`` — so on Windows every artifact is
    written CRLF while the rendered string holds LF. A byte compare would report
    16/16 permanent drift on a perfectly fresh Windows checkout (the repo IS run
    from a Win10 clone for sim work). ``read_text``'s universal-newline decode
    normalises both sides, which is also why the sibling
    ``test_udp_protocol_xlang.py`` gate compares text.
    """
    drift, external = [], []
    for dest, content, _label in plan:
        bucket = external if is_external(dest) else drift
        if not dest.exists():
            bucket.append((dest, "missing"))
            continue
        try:
            on_disk = dest.read_text(encoding="utf-8")
        except OSError as exc:
            bucket.append((dest, f"unreadable ({exc.strerror})"))
            continue
        except UnicodeDecodeError:
            bucket.append((dest, "not valid UTF-8"))
            continue
        if on_disk != content:
            bucket.append((dest, "differs from generator output"))
    return drift, external


def _print_bb_warning():
    print()
    print("!" * 78)
    print("!!  WARNING: BallButler directory not found!".ljust(77) + "!")
    print("!!  Ball Butler config files were NOT updated.".ljust(77) + "!")
    print(f"!!  Expected: {_rel(BB_FIRMWARE_DIR)} at same level as repo root.".ljust(77) + "!")
    print("!" * 78)


def main(argv=None):
    argv = list(sys.argv[1:] if argv is None else argv)

    check_only = False
    if "--check" in argv:
        check_only = True
        argv = [a for a in argv if a != "--check"]

    positional = [a for a in argv if not a.startswith("-")]
    unknown = [a for a in argv if a.startswith("-")]
    if unknown:
        print(f"Error: unknown option(s): {' '.join(unknown)}", file=sys.stderr)
        print("Usage: generate_config.py [--check] [path/to/protocol_config.yaml]",
              file=sys.stderr)
        return 2

    yaml_path = Path(positional[0]) if positional else DEFAULT_YAML
    if not yaml_path.exists():
        print(f"Error: YAML file not found: {yaml_path}", file=sys.stderr)
        return 1

    plan, skipped, notes, bb_available = build_artifacts(yaml_path)

    if check_only:
        # NO WRITES ON THIS PATH — deliberately no OUTPUT_DIR.mkdir() either.
        drift, external_drift = check_artifacts(plan)

        # Everything that was NOT checked is announced. A verdict that silently
        # covers half the surface is the failure this gate exists to prevent:
        # with HW_YAML absent, 9 of 16 artifacts (the entire tuning surface)
        # would otherwise vanish behind a green "CONFIG FRESH: 7".
        # jugglebot_launch.py folds these lines into PARTIAL rather than OK.
        for dest in skipped:
            prefix = "EXTERNAL SKIPPED" if is_external(dest) else "SKIPPED"
            print(f"{prefix}: {_rel(dest)} — parent directory not found",
                  file=sys.stderr)
        for note in notes:
            print(f"NOT CHECKED: {note}", file=sys.stderr)
        for dest, reason in external_drift:
            print(f"EXTERNAL DRIFT: {_rel(dest)} — {reason} "
                  f"(separate checkout; does not fail this gate)",
                  file=sys.stderr)
        for dest, reason in drift:
            print(f"DRIFT: {_rel(dest)} — {reason}", file=sys.stderr)

        n_checked = len(plan) - len(
            [d for d, _c, _l in plan if is_external(d)])
        if drift:
            print("", file=sys.stderr)
            print(f"CONFIG DRIFT: {len(drift)} file(s) out of date "
                  f"({n_checked} checked). Fix: python config/generate_config.py "
                  f"&& (cd ros_ws && colcon build --packages-select jugglebot)",
                  file=sys.stderr)
            return 1
        print(f"CONFIG FRESH: {n_checked} artifact(s) match the generator.")
        return 0

    # ── Write path ──
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    for dest, content, label in plan:
        dest.write_text(content, encoding="utf-8")
        print(f"{(label + ':').ljust(10)} {_rel(dest)}")
    for dest in skipped:
        print(f"Skipped (dir not found): {_rel(dest)}")
    for note in notes:
        print(note)

    # Print BallButler warning at the very end so it's impossible to miss
    if not bb_available:
        _print_bb_warning()
    return 0


if __name__ == "__main__":
    sys.exit(main())
