#!/usr/bin/env python3
"""
generate_config.py — Generate C++ and Python protocol constants from YAML.

Usage:
    python generate_config.py                  # uses default paths
    python generate_config.py path/to/yaml     # specify YAML location

Outputs:
    config/generated/jugglebot_protocol.h      (C++ constexpr header)
    config/generated/jugglebot_protocol.py     (Python constants module)
"""

import sys
from pathlib import Path
import yaml

SCRIPT_DIR = Path(__file__).resolve().parent
REPO_ROOT = SCRIPT_DIR.parent
DEFAULT_YAML = SCRIPT_DIR / "jugglebot_protocol.yaml"
OUTPUT_DIR = SCRIPT_DIR / "generated"

# Additional output locations so consumers can import/include directly
ROS_PKG_DIR = REPO_ROOT / "ros_ws" / "src" / "jugglebot" / "jugglebot"
BB_FIRMWARE_DIR = REPO_ROOT / "Ball Butler" / "ball_butler_main"
PLATFORM_FIRMWARE_DIR = REPO_ROOT / "ros_ws" / "src" / "jugglebot" / "Teensy_code"


def load_yaml(path: Path) -> dict:
    with open(path, "r") as f:
        return yaml.safe_load(f)


def fmt_hex(v) -> str:
    """Format an integer as 0x.. hex (minimal digits, no zero-padding), or float as-is."""
    if isinstance(v, int):
        return f"0x{v:02X}" if v <= 0xFF else f"0x{v:X}"
    return str(v)


# ── C++ generation ──────────────────────────────────────────────────────────

def cpp_section(title: str) -> list[str]:
    """Return a C++ section-divider comment block."""
    bar = "// " + "=" * 74
    return ["", bar, f"// {title}", bar, ""]


def generate_cpp(cfg: dict) -> str:
    lines = [
        "#pragma once",
        "// AUTO-GENERATED by generate_config.py — DO NOT EDIT",
        "// Source: config/jugglebot_protocol.yaml",
        "//",
        "// Shared protocol constants for the Jugglebot CAN bus.",
        "// Consumed by: Ball Butler firmware, Platform Teensy firmware, ROS2 Python.",
        "// To regenerate: python config/generate_config.py",
        "",
        "#include <cstdint>",
    ]

    # CAN bus
    lines += cpp_section("CAN Bus Configuration")
    lines.append("namespace CanBus {")
    lines.append(f"  constexpr uint32_t BAUD_RATE = {cfg['can_bus']['baud_rate']}u;  // All nodes must agree")
    lines.append("}")

    # ODrive commands
    lines += cpp_section("ODrive CAN Protocol — Command IDs (lower 5 bits of arbitration ID)")
    lines.append("namespace ODriveCmd {")
    for name, val in cfg["odrive"]["commands"].items():
        lines.append(f"  constexpr uint8_t {name} = {fmt_hex(val)};")
    lines.append("}")

    # ODrive states
    lines += cpp_section("ODrive Axis States")
    lines.append("namespace ODriveState {")
    for name, val in cfg["odrive"]["states"].items():
        lines.append(f"  constexpr uint32_t {name} = {val}u;")
    lines.append("}")

    # ODrive control modes
    lines.append("")
    lines.append("// ODrive control modes")
    lines.append("namespace ODriveControlMode {")
    for name, val in cfg["odrive"]["control_modes"].items():
        lines.append(f"  constexpr uint32_t {name} = {val}u;")
    lines.append("}")

    # ODrive input modes
    lines.append("")
    lines.append("// ODrive input modes")
    lines.append("namespace ODriveInputMode {")
    for name, val in cfg["odrive"]["input_modes"].items():
        lines.append(f"  constexpr uint32_t {name} = {val}u;")
    lines.append("}")

    # ODrive errors
    lines.append("")
    lines.append("// ODrive error bit masks")
    lines.append("namespace ODriveErrors {")
    for name, val in cfg["odrive"]["errors"].items():
        lines.append(f"  constexpr uint32_t {name} = {fmt_hex(val)}u;")
    lines.append("}")

    # Node IDs
    lines += cpp_section("CAN Node IDs — ODrive axis addresses")
    lines.append("namespace NodeId {")
    legs = cfg["node_ids"]["legs"]
    for i, nid in enumerate(legs):
        lines.append(f"  constexpr uint8_t LEG_{i} = {nid};")
    lines.append(f"  constexpr uint8_t JUGGLEBOT_HAND = {cfg['node_ids']['jugglebot_hand']};")
    lines.append(f"  constexpr uint8_t BB_PITCH = {cfg['node_ids']['bb_pitch']};")
    lines.append(f"  constexpr uint8_t BB_HAND = {cfg['node_ids']['bb_hand']};")
    lines.append("}")

    # Shared CAN IDs
    lines += cpp_section("Custom CAN Message IDs")
    lines.append("// Shared IDs — used by both Platform and Ball Butler Teensys")
    lines.append("namespace SharedCanId {")
    for name, val in cfg["can_ids"]["shared"].items():
        lines.append(f"  constexpr uint32_t {name} = {fmt_hex(val)};")
    lines.append("}")

    # Platform CAN IDs
    lines.append("")
    lines.append("// Platform Teensy <-> Host")
    lines.append("namespace PlatformCanId {")
    for name, val in cfg["can_ids"]["platform"].items():
        lines.append(f"  constexpr uint32_t {name} = {fmt_hex(val)};")
    lines.append("}")

    # Ball Butler CAN IDs
    lines.append("")
    lines.append("// Ball Butler Teensy <-> Host")
    lines.append("namespace BallButlerCanId {")
    for name, val in cfg["can_ids"]["ball_butler"].items():
        lines.append(f"  constexpr uint32_t {name} = {fmt_hex(val)};")
    lines.append("}")

    # Ball Butler states
    lines += cpp_section("Ball Butler State Machine")
    lines.append("// States — encoded in heartbeat byte 0 (bits 1-7)")
    lines.append("namespace BallButlerState {")
    for name, val in cfg["ball_butler"]["states"].items():
        lines.append(f"  constexpr uint8_t {name} = {val};")
    lines.append("}")

    # Ball Butler errors
    lines.append("")
    lines.append("// Error codes — encoded in heartbeat byte 1 when state == ERROR")
    lines.append("namespace BallButlerErrorCode {")
    for name, val in cfg["ball_butler"]["errors"].items():
        lines.append(f"  constexpr uint8_t {name} = {val};")
    lines.append("}")

    # Heartbeat encoding
    lines += cpp_section("Encoding / Scaling")
    lines.append("// Ball Butler heartbeat CAN frame encoding resolutions")
    lines.append("namespace HeartbeatEncoding {")
    for name, val in cfg["encoding"]["heartbeat"].items():
        lines.append(f"  constexpr float {name} = {val}f;")
    lines.append("}")

    # Input scales
    lines.append("")
    lines.append("// ODrive input scaling (vel_ff and torque_ff are sent as int16 * scale)")
    lines.append("namespace InputScale {")
    for name, val in cfg["encoding"]["input_scales"].items():
        lines.append(f"  constexpr float {name} = {float(val)}f;")
    lines.append("}")

    # SDO
    lines += cpp_section("SDO — Arbitrary Parameter Access")
    lines.append("namespace SDO {")
    for name, val in cfg["sdo"].items():
        lines.append(f"  constexpr uint8_t {name} = {fmt_hex(val)};")
    lines.append("}")

    # Endpoints
    lines += cpp_section("Endpoint IDs — ODrive internal parameter addresses")
    lines.append("namespace EndpointId {")
    for name, val in cfg["endpoints"].items():
        lines.append(f"  constexpr uint16_t {name} = {val};")
    lines.append("}")
    lines.append("")

    return "\n".join(lines)


# ── Python generation ───────────────────────────────────────────────────────

def py_section(title: str) -> list[str]:
    """Return a Python section-divider comment block."""
    bar = "# " + "=" * 76
    return ["", bar, f"# {title}", bar, ""]


def generate_python(cfg: dict) -> str:
    lines = [
        '"""',
        "AUTO-GENERATED by generate_config.py — DO NOT EDIT",
        "Source: config/jugglebot_protocol.yaml",
        "",
        "Shared protocol constants for the Jugglebot CAN bus.",
        "Consumed by: ROS2 Python nodes (can_interface.py, ball_butler_node.py, etc.)",
        "To regenerate: python config/generate_config.py",
        '"""',
        "",
        "from enum import IntEnum",
    ]

    # CAN bus
    lines += py_section("CAN Bus Configuration")
    lines.append(f"CAN_BAUD_RATE = {cfg['can_bus']['baud_rate']}  # All nodes must agree")

    # ODrive commands
    lines += py_section("ODrive CAN Protocol — Command IDs (lower 5 bits of arbitration ID)")
    lines.append("ODRIVE_COMMANDS = {")
    for name, val in cfg["odrive"]["commands"].items():
        lines.append(f'    "{name}": {fmt_hex(val)},')
    lines.append("}")

    # ODrive states
    lines += py_section("ODrive Axis States, Control Modes, Input Modes")
    lines.append("ODRIVE_STATES = {")
    for name, val in cfg["odrive"]["states"].items():
        lines.append(f'    "{name}": {val},')
    lines.append("}")
    lines.append("")

    # ODrive control modes
    lines.append("ODRIVE_CONTROL_MODES = {")
    for name, val in cfg["odrive"]["control_modes"].items():
        lines.append(f'    "{name}": {val},')
    lines.append("}")
    lines.append("")

    # ODrive input modes
    lines.append("ODRIVE_INPUT_MODES = {")
    for name, val in cfg["odrive"]["input_modes"].items():
        lines.append(f'    "{name}": {val},')
    lines.append("}")
    lines.append("")

    # ODrive errors
    lines.append("# ODrive error bit masks")
    lines.append("ODRIVE_ERRORS = {")
    for name, val in cfg["odrive"]["errors"].items():
        lines.append(f'    "{name}": {fmt_hex(val)},')
    lines.append("}")

    # Node IDs
    lines += py_section("CAN Node IDs — ODrive axis addresses")
    lines.append(f"NODE_ID_LEGS = {cfg['node_ids']['legs']}")
    lines.append(f"NODE_ID_JUGGLEBOT_HAND = {cfg['node_ids']['jugglebot_hand']}")
    lines.append(f"NODE_ID_BB_PITCH = {cfg['node_ids']['bb_pitch']}")
    lines.append(f"NODE_ID_BB_HAND = {cfg['node_ids']['bb_hand']}")

    # Shared CAN IDs
    lines += py_section("Custom CAN Message IDs")
    lines.append("# Shared IDs — used by both Platform and Ball Butler Teensys")
    for name, val in cfg["can_ids"]["shared"].items():
        lines.append(f"CAN_ID_SHARED_{name} = {fmt_hex(val)}")
    lines.append("")

    # Platform CAN IDs
    lines.append("# Platform Teensy <-> Host")
    for name, val in cfg["can_ids"]["platform"].items():
        lines.append(f"CAN_ID_PLATFORM_{name} = {fmt_hex(val)}")
    lines.append("")

    # Ball Butler CAN IDs
    lines.append("# Ball Butler Teensy <-> Host")
    for name, val in cfg["can_ids"]["ball_butler"].items():
        lines.append(f"CAN_ID_BB_{name} = {fmt_hex(val)}")

    # Ball Butler states (as IntEnum for type safety)
    lines += py_section("Ball Butler State Machine")
    lines.append("# States — encoded in heartbeat byte 0 (bits 1-7)")
    lines.append("class BallButlerStates(IntEnum):")
    for name, val in cfg["ball_butler"]["states"].items():
        lines.append(f"    {name} = {val}")
    lines.append("")

    # Ball Butler errors (as IntEnum)
    lines.append("# Error codes — encoded in heartbeat byte 1 when state == ERROR")
    lines.append("class BallButlerError(IntEnum):")
    for name, val in cfg["ball_butler"]["errors"].items():
        lines.append(f"    {name} = {val}")

    # Heartbeat encoding
    lines += py_section("Encoding / Scaling")
    lines.append("# Ball Butler heartbeat CAN frame encoding resolutions")
    for name, val in cfg["encoding"]["heartbeat"].items():
        lines.append(f"HEARTBEAT_{name.upper()} = {val}")
    lines.append("")

    # Input scales
    lines.append("# ODrive input scaling (vel_ff and torque_ff are sent as int16 * scale)")
    for name, val in cfg["encoding"]["input_scales"].items():
        lines.append(f"INPUT_SCALE_{name.upper()} = {float(val)}")

    # SDO
    lines += py_section("SDO — Arbitrary Parameter Access")
    for name, val in cfg["sdo"].items():
        lines.append(f"{name} = {fmt_hex(val)}")

    # Endpoints
    lines += py_section("Endpoint IDs — ODrive internal parameter addresses")
    for name, val in cfg["endpoints"].items():
        lines.append(f"ENDPOINT_{name.upper()} = {val}")
    lines.append("")

    return "\n".join(lines)


# ── Main ────────────────────────────────────────────────────────────────────

def main():
    yaml_path = Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_YAML
    if not yaml_path.exists():
        print(f"Error: YAML file not found: {yaml_path}", file=sys.stderr)
        sys.exit(1)

    cfg = load_yaml(yaml_path)
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    cpp_path = OUTPUT_DIR / "jugglebot_protocol.h"
    py_path = OUTPUT_DIR / "jugglebot_protocol.py"

    cpp_content = generate_cpp(cfg)
    py_content = generate_python(cfg)

    cpp_path.write_text(cpp_content, encoding="utf-8")
    py_path.write_text(py_content, encoding="utf-8")

    print(f"Generated: {cpp_path}")
    print(f"Generated: {py_path}")

    # Copy to consumer directories so they can include/import directly
    extra_copies = [
        (cpp_content, BB_FIRMWARE_DIR / "jugglebot_protocol.h"),
        (cpp_content, PLATFORM_FIRMWARE_DIR / "jugglebot_protocol.h"),
        (py_content, ROS_PKG_DIR / "jugglebot_protocol.py"),
    ]
    for content, dest in extra_copies:
        if dest.parent.exists():
            dest.write_text(content, encoding="utf-8")
            print(f"Copied:    {dest}")
        else:
            print(f"Skipped (dir not found): {dest}")


if __name__ == "__main__":
    main()
