"""
AUTO-GENERATED by generate_config.py — DO NOT EDIT
Source: config/hardware_config.yaml

Centralised hardware & geometry constants for the Jugglebot system.
Consumed by: ROS2 Python nodes (motion planner, CAN node, mocap, etc.)
To regenerate: python config/generate_config.py
"""

import math

# ============================================================================
# Shared Physics
# ============================================================================

GRAVITY_MPS2 = 9.806

# ============================================================================
# Jugglebot Stewart Platform Geometry
# ============================================================================

GEOM_INITIAL_HEIGHT_MM = 574.3
GEOM_BASE_RADIUS_MM = 410.0
GEOM_PLAT_RADIUS_MM = 219.075
GEOM_BASE_SMALL_ANGLE_DEG = 20.0
GEOM_PLAT_SMALL_ANGLE_DEG = 8.6024446
GEOM_PLAT_X_AXIS_OFFSET_DEG = 154.3012223
GEOM_LEG_STROKE_MM = 280.0
GEOM_ARM_RADIUS_MM = 70.0
GEOM_ARM_HEIGHT_FROM_PLATFORM_MM = 210.25
GEOM_HAND_STROKE_MM = 355.0
GEOM_HAND_RADIUS_MM = 35.0
GEOM_BALL_JOINT_OFFSET_MM = 25.5
GEOM_BASE_NODES_MM = [
    [-385.274, -140.228, 0.0],
    [-314.078, -263.543, 0.0],
    [314.078, -263.543, 0.0],
    [385.274, -140.228, 0.0],
    [71.196, 403.771, 0.0],
    [-71.196, 403.771, 0.0],
]
GEOM_INIT_PLAT_NODES_MM = [
    [-197.405, 95.0, 0.0],
    [-16.431, -218.458, 0.0],
    [16.431, -218.458, 0.0],
    [197.405, 95.0, 0.0],
    [180.975, 123.458, 0.0],
    [-180.975, 123.458, 0.0],
]
GEOM_INIT_LEG_LENGTHS_MM = [621.389, 618.16, 622.074, 620.653, 620.652, 620.091]
GEOM_MM_TO_REV = [0.01418332, 0.01419076, 0.01408956, 0.01418684, 0.01426801, 0.01424951]

# ============================================================================
# Jugglebot Catch Plane
# ============================================================================

CATCH_CATCH_HEIGHT_OFFSET_THROWN_MM = 170.0
CATCH_CATCH_HEIGHT_OFFSET_DROPPED_MM = 165.0
CATCH_XY_RANGE_OF_MOTION_MM = 400.0
CATCH_CATCH_ANGLE_LIMIT_DEG = 30.0
CATCH_MINIMUM_TIME_TO_ATTEMPT_CATCH_S = 0.5
CATCH_TIME_AFTER_CATCHING_TO_RETURN_TO_DEFAULT_S = 1.0
CATCH_DEFAULT_ACTIVE_Z_MM = 170.0

# ============================================================================
# Jugglebot Hand
# ============================================================================

HAND_BALL_Z_AT_TOP_OF_STROKE_MM = 828.2
HAND_TOP_STROKE_POSITION_REVS = 9.858
HAND_MAX_HAND_POSITION_REVS = 11.1

# ============================================================================
# Jugglebot Teensy Trajectory
# ============================================================================

TEENSY_TRAJ_HAND_SPOOL_RADIUS_M = 0.00521
TEENSY_TRAJ_LINEAR_GAIN_FACTOR = 1.035
TEENSY_TRAJ_INERTIA_HAND_ONLY_KG = 0.281
TEENSY_TRAJ_INERTIA_RATIO = 0.747
TEENSY_TRAJ_THROW_VEL_HOLD_PCT = 0.05
TEENSY_TRAJ_CATCH_VEL_RATIO = 0.6
TEENSY_TRAJ_CATCH_VEL_HOLD_PCT = 0.1
TEENSY_TRAJ_HAND_STROKE_M = 0.355
TEENSY_TRAJ_STROKE_MARGIN_M = 0.02
TEENSY_TRAJ_END_PROFILE_HOLD_S = 0.1
TEENSY_TRAJ_SAMPLE_RATE_HZ = 500
TEENSY_TRAJ_MAX_SMOOTH_MOVE_HAND_ACCEL_RPS2 = 100.0
TEENSY_TRAJ_QUINTIC_S2_MAX = 5.7735027

# ============================================================================
# Teensy Operational
# ============================================================================

TEENSY_REPORT_INTERVAL_MS = 500
TEENSY_SAFETY_GAP_US = 20000
TEENSY_TIME_SYNC_ALPHA_SHIFT = 3

# ============================================================================
# Ball Tracking & Prediction
# ============================================================================

TRACKING_MOCAP_DT_S = 0.005
TRACKING_PROCESS_NOISE = 5.0
TRACKING_MEASUREMENT_NOISE = 1.0
TRACKING_LANDING_THRESHOLD_MM = 20.0
TRACKING_IS_PROJECTILE_RESIDUAL_THRESHOLD = 10.0
TRACKING_IS_PROJECTILE_A_THRESHOLD_MMPS2 = 400.0
TRACKING_BUFFER_DURATION_S = 0.1
TRACKING_MATCH_THRESHOLD_BASE_MM = 100.0
TRACKING_PENDING_TIMEOUT_S = 5.0
TRACKING_MIN_MATCHES_TO_CONFIRM = 3
TRACKING_MIN_HEIGHT_ABOVE_LANDING_MM = 50.0
TRACKING_MAX_FRAMES_WITHOUT_MEASUREMENT = 200

# ============================================================================
# Ball Butler Geometry & Kinematics
# ============================================================================

BB_GEOM_YAW_S_OFFSET_MM = -105.65
BB_GEOM_PITCH_D_OFFSET_MM = 41.0
BB_GEOM_RELEASE_L_POSITION_MM = 150.0
BB_GEOM_PITCH_Z_OFFSET_MM = 17.5
BB_GEOM_PITCH_MAX_DEG = 85.0
BB_GEOM_PITCH_MIN_DEG = 12.0
BB_GEOM_YAW_MAX_DEG = 185.0
BB_GEOM_YAW_MIN_DEG = 0.0

# ============================================================================
# Ball Butler Trajectory
# ============================================================================

BB_TRAJ_HAND_SPOOL_RADIUS_M = 0.0052493
BB_TRAJ_LINEAR_GAIN_FACTOR = 1.0
BB_TRAJ_INERTIA_HAND_ONLY_KG = 0.281
BB_TRAJ_INERTIA_RATIO = 0.747
BB_TRAJ_HAND_STROKE_M = 0.28
BB_TRAJ_STROKE_MARGIN_M = 0.02
BB_TRAJ_THROW_VEL_HOLD_PCT = 0.05
BB_TRAJ_CATCH_VEL_RATIO = 0.8
BB_TRAJ_CATCH_VEL_HOLD_PCT = 0.1
BB_TRAJ_END_PROFILE_HOLD_S = 0.1
BB_TRAJ_SAMPLE_RATE_HZ = 500
BB_TRAJ_MAX_SMOOTH_ACCEL_RPS2 = 200.0
BB_TRAJ_QUINTIC_S2_MAX = 5.7735027
BB_TRAJ_HAND_MAX_SMOOTH_POS_REV = 8.9
BB_TRAJ_MAX_THROW_DURATION_S = 2.0
BB_TRAJ_MAX_SMOOTH_SAMPLES = 300
BB_TRAJ_MAX_PAUSE_SAMPLES = 512
BB_TRAJ_TRAJ_ARENA_BYTES = 24576

# ============================================================================
# Ball Butler Hardware Pins
# ============================================================================

BB_PIN_YAW_PWM_A = 10
BB_PIN_YAW_PWM_B = 16
BB_PIN_YAW_ENC_A = 15
BB_PIN_YAW_ENC_B = 14

# ============================================================================
# Ball Butler CAN Config
# ============================================================================

BB_CAN_HEARTBEAT_RATE_MS = 100
BB_CAN_AUTO_CLEAR_BRAKE_MS = 500
BB_CAN_MAX_NODES = 16

# ============================================================================
# Ball Butler Yaw Axis
# ============================================================================

BB_YAW_ENC_CPR = 60
BB_YAW_PWM_FREQ_HZ = 20000
BB_YAW_LOOP_HZ = 150.0
BB_YAW_ENC_DIR = -1
BB_YAW_MOTOR_DIR = 1
BB_YAW_KP = 300.0
BB_YAW_KI = 0.0
BB_YAW_KD = 0.0
BB_YAW_FF_PWM = 10.0
BB_YAW_POS_TOL_REV = 0.0014
BB_YAW_ACCEL_PPS = 500.0
BB_YAW_DECEL_PPS = 450.0
BB_YAW_LIM_MIN_DEG = 0.0
BB_YAW_LIM_MAX_DEG = 120.0
BB_YAW_HARD_LIMIT_OVERSHOOT_DEG = 3.0
BB_YAW_VEL_LPF_ALPHA = 0.3
BB_YAW_MAX_VALID_VEL_RPS = 2.0
BB_YAW_BOOT_ZERO_OFFSET_DEG = 5.0
BB_YAW_BOOT_SOFT_LIM_MIN_DEG = -5.0
BB_YAW_BOOT_SOFT_LIM_MAX_DEG = 190.0
BB_YAW_BOOT_HARD_LIMIT_OVERSHOOT_DEG = 10.0

# ============================================================================
# Ball Butler Pitch Axis
# ============================================================================

BB_PITCH_DEG_MIN = 12.0
BB_PITCH_DEG_MAX = 90.0
BB_PITCH_TRAJ_VEL_RPS = 1.0
BB_PITCH_TRAJ_ACCEL_RPS2 = 0.5
BB_PITCH_TRAJ_DECEL_RPS2 = 0.25

# ============================================================================
# Ball Butler Hand Axis
# ============================================================================

BB_HAND_HOMING_DIRECTION = -1
BB_HAND_HOMING_SPEED_RPS = 3.0
BB_HAND_HOMING_CURRENT_A = 5.0
BB_HAND_HOMING_HEADROOM_A = 3.0
BB_HAND_HOMING_ABS_POS_REV = -0.1
BB_HAND_HOMING_EMA_WEIGHT = 0.7
BB_HAND_HOMING_IQ_POLL_MS = 10
BB_HAND_HOMING_ATTEMPT_TIMEOUT_MS = 5000
BB_HAND_HOMING_MODE_SETTLE_MS = 100
BB_HAND_HOMING_STOP_SETTLE_MS = 5
BB_HAND_OP_VEL_LIMIT_RPS = 1000.0
BB_HAND_OP_CURRENT_LIMIT_A = 50.0

# ============================================================================
# Ball Butler State Machine
# ============================================================================

BB_SM_HOMING_TIMEOUT_MS = 10000
BB_SM_HOMING_RETRY_DELAY_MS = 500
BB_SM_RELOAD_TIMEOUT_MS = 10000
BB_SM_POST_THROW_DELAY_MS = 1000
BB_SM_IDLE_NO_CMD_TIMEOUT_MS = 5000
BB_SM_RELOAD_HAND_TOP_REV = 8.7
BB_SM_RELOAD_PITCH_READY_DEG = 70.0
BB_SM_RELOAD_YAW_ANGLE_DEG = 180.0
BB_SM_RELOAD_PITCH_GRAB_DEG = 90.0
BB_SM_RELOAD_HAND_BOTTOM_REV = 0.0
BB_SM_RELOAD_HAND_BOTTOM_TOL_REV = 0.1
BB_SM_RELOAD_HOLD_DELAY_MS = 500
BB_SM_RELOAD_BALL_CHECK_SAMPLES = 5
BB_SM_BALL_CHECK_SAMPLE_INTERVAL_MS = 100
BB_SM_TRACKING_HAND_CHECK_MS = 200
BB_SM_YAW_CMD_INTERVAL_MS = 10
BB_SM_PITCH_CMD_INTERVAL_MS = 50
BB_SM_CHECK_BALL_CONFIRM_SAMPLES = 5
BB_SM_CHECK_BALL_DISRUPT_PITCH_DEG = 70.0
BB_SM_HAND_REV_HOME = 0.0
BB_SM_PITCH_DEG_HOME = 90.0
BB_SM_YAW_DEG_HOME = 20.0
BB_SM_CALIB_MAX_YAW_DEG = 120.0
BB_SM_CALIB_MIN_YAW_DEG = 0.0
BB_SM_CALIB_YAW_ACCEL = 50.0
BB_SM_CALIB_YAW_DECEL = 50.0
BB_SM_CALIB_PAUSE_MS = 2500
BB_SM_MAX_RELOAD_ATTEMPTS = 3
BB_SM_MAX_HOMING_ATTEMPTS = 3
BB_SM_PITCH_SETTLE_MS = 500
BB_SM_PITCH_GRAB_SETTLE_MS = 1000
BB_SM_YAW_ANGLE_THRESHOLD_DEG = 1.0
BB_SM_PITCH_IDLE_DELAY_MS = 500
BB_SM_MIN_MOTION_DURATION_MS = 300
BB_SM_PV_FRESHNESS_US = 20000
BB_SM_PITCH_MIN_STOW_DEG = 80.0
BB_SM_YAW_MIN_ANGLE_DEG = 5.0
BB_SM_YAW_MAX_ANGLE_DEG = 190.0

# ============================================================================
# Ball Butler Operational
# ============================================================================

BB_OP_THROW_VEL_MIN_MPS = 0.05
BB_OP_THROW_VEL_MAX_MPS = 6.0
BB_OP_SCHEDULE_MARGIN_S = 0.1
BB_OP_YAW_TELEM_MS = 500
BB_OP_SERIAL_BAUD = 115200
BB_OP_SERIAL_WAIT_MS = 2000
BB_OP_ODRIVE_BOOT_MS = 1000
BB_OP_MAX_THROW_SPEED_MPS = 5.0
BB_OP_MAX_THROW_HEIGHT_M = 0.5
BB_OP_THROW_SPEED_MULTIPLIER = 1.0
BB_OP_LANDING_TIME_OFFSET_MS = -120.0

# ============================================================================
# Ball Butler Heartbeat Encoding
# ============================================================================

BB_HB_HAND_MAX_MM = 655.36
BB_HB_PITCH_CLAMP_MIN_DEG = 0.0
BB_HB_PITCH_CLAMP_MAX_DEG = 90.0

# ============================================================================
# Derived Constants (computed by generator)
# ============================================================================

GRAVITY_MMPS2 = 9806.0
CATCH_HEIGHT_THROWN_MM = 744.3
CATCH_HEIGHT_DROPPED_MM = 739.3
INIT_LEG_LENGTHS_WITH_OFFSET_MM = [646.889, 643.66, 647.574, 646.153, 646.152, 645.591]
TEENSY_LINEAR_GAIN = 31.617152802324696
BB_LINEAR_GAIN = 30.3192698249091
BB_MAX_THROW_SAMPLES = 1001
BB_MAX_TRAJ_FRAMES = 1813
