# For adjusting the geometry of the juggling pattern

float64 throw_height # How high will the ball be thrown? {m}
float64 zlim_hold    # The limit for how far (vertically) the hand will move while holding {mm}
float64 zlim_empty   # The limit for how far (vertically) the hand will move while empty {mm}
float64 z_offset     # Vertical distance between lowest hand pos and catch/throw plane {mm}
float64 x_pos        # Location of catches/throws from the y/z plane (assume mirrored for now) {mm}
