---
- name: Provision the WSL2 host
  hosts: localhost
  connection: local
  vars:
    environments_dir: "{{ playbook_dir }}/.."

  tasks:

  - name: Ensure that the ssh_keypair_name was specified
    assert:
      that: ssh_keypair_name
      quiet: yes
      fail_msg: 'This playbook requires that the keypair name be specified using `-e "ssh_keypair_name=''[keypair name]''"`'
  
  - name: Ensure that the git_name was specified
    assert:
      that: git_name
      quiet: yes
      fail_msg: 'This playbook requires that the git name be specified using `-e "git_name=''[your full name]''"`'
  
  - name: Ensure that the git_email was specified
    assert:
      that: git_email
      quiet: yes
      fail_msg: 'This playbook requires that the git name be specified using `-e "git_email=''[your email address]''"`'
  
  - name: Load variables
    include_vars: "{{ environments_dir }}/ubuntu_24.04-wsl2/main_vars.yml"

  - name: Ensure that wsl uses systemd
    # Note: Systemd is enabled by default, but this will change whitespace
    community.general.ini_file:
      path: '/etc/wsl.conf'
      section: 'boot'
      option: 'systemd'
      value: 'true'
    become: yes

  - name: Prevent wsl from changing resolv.conf
    community.general.ini_file:
      path: '/etc/wsl.conf'
      section: 'network'
      option: 'generateResolvConf'
      value: 'false'
    become: yes

  - name: Specify the Google nameserver in resolv.conf
    lineinfile:
      path: '/etc/resolv.conf'
      regexp: '^nameserver .*$'
      line: 'nameserver 8.8.8.8'
    become: yes

  - name: Create ~/.hushlogin
    file:
      path: "{{ home_dir }}/.hushlogin"
      state: touch

  - name: Provision the Ubuntu environment
    import_tasks: "{{ environments_dir }}/ubuntu-common/dev_env_tasks.yml"
    vars:
      environments_dir: "{{ playbook_dir }}/.."

  - name: Ensure that the specified ssh keypair exists
    assert:
      that: "ssh_private_key_filepath is file and (ssh_private_key_filepath + '.pub') is file"
      quiet: yes
      fail_msg: "The specified ssh keypair ('{{ ssh_private_key_filepath }}', '{{ ssh_private_key_filepath }}.pub') was not found."

  - name: Add an ssh config for GitHub
    community.general.ssh_config:
      user: "{{ username }}"
      host: 'github.com'
      hostname: 'github.com'
      remote_user: 'git'
      identity_file: "~/.ssh/{{ ssh_keypair_name }}"
      identities_only: yes
      add_keys_to_agent: yes
      strict_host_key_checking: accept-new

  - name: Set git name in ~/.gitconfig
    community.general.ini_file:
      path: "{{ gitconfig_filepath }}"
      section: 'user'
      option: 'name'
      value: "{{ git_name }}"

  - name: Set git name in ~/.gitconfig
    community.general.ini_file:
      path: "{{ gitconfig_filepath }}"
      section: 'user'
      option: 'email'
      value: "{{ git_email }}"

  - name: Ensure that the Jugglebot repo has been cloned
    git:
      repo: "{{ jugglebot_repo_ssh_url }}"
      dest: "{{ jugglebot_repo_dir }}"

  - name: Add the Docker package repository
    import_tasks: "{{ environments_dir }}/ubuntu-common/docker_repository_tasks.yml"
    vars:
      environments_dir: "{{ playbook_dir }}/.."

  - name: Provision the Docker Engine & Qemu
    import_tasks: "{{ environments_dir }}/ubuntu-common/docker_engine_tasks.yml"
    vars:
      environments_dir: "{{ playbook_dir }}/.."

  - name: Add the user to the docker group
    # Note: This enables the user to issue CLI commands (eg. `docker run [..]`)
    #   to the Docker Engine without sudo.
    user:
      name: "{{ ansible_facts['env']['USER'] }}"
      append: yes
      groups: docker
    become: yes

  - name: Create or diff the docker-native-env script
    import_tasks: "{{ environments_dir }}/ansible-common/copy_or_diff.yml"
    vars:
      src: "{{ environments_dir }}/ubuntu_24.04-wsl2/docker-native-env"
      dest: "{{ home_dir }}/bin/docker-native-env"
      readable_dest: ~/bin/docker-native-env
      mode: '0755'

