---
- name: Provision the WSL2 host
  hosts: localhost
  connection: local

  tasks:

  - name: Specify the environments directory
    set_fact:
      environments_dir: "{{ playbook_dir }}/.."

  - name: Ensure that wsl uses systemd
    # Note: Systemd is enabled by default, but this will change whitespace
    community.general.ini_file:
      path: '/etc/wsl.conf'
      section: 'boot'
      option: 'systemd'
      value: 'true'
    become: yes

  - name: Prevent wsl from changing resolv.conf
    community.general.ini_file:
      path: '/etc/wsl.conf'
      section: 'network'
      option: 'generateResolvConf'
      value: 'false'
    become: yes

  - name: Provision the Ubuntu environment
    import_tasks: "{{ environments_dir }}/ubuntu-common/dev_env_tasks.yml"
    vars:
      environments_dir: "{{ environments_dir }}"

  - name: Add the Docker package repository
    import_tasks: "{{ environments_dir }}/ubuntu-common/docker_repository_tasks.hml"

  - name: Provision the Docker Engine & Qemu
    import_tasks: "{{ environments_dir }}/ubuntu-common/docker_engine_tasks.yml"

