#pragma once
// AUTO-GENERATED by generate_config.py — DO NOT EDIT
// Source: config/protocol_config.yaml
//
// Shared protocol constants for the Jugglebot CAN bus.
// Consumed by: Ball Butler firmware, Platform Teensy firmware, ROS2 Python.
// To regenerate: python config/generate_config.py

#include <cstdint>

// ==========================================================================
// CAN Bus Configuration
// ==========================================================================

namespace CanBus {
  constexpr uint32_t BAUD_RATE = 1000000u;  // All nodes must agree
  constexpr uint32_t BITS_PER_FRAME_APPROX = 111u;  // Approx bits per 8-byte CAN frame
}

// ==========================================================================
// ODrive CAN Protocol — Command IDs (lower 5 bits of arbitration ID)
// ==========================================================================

namespace ODriveCmd {
  constexpr uint8_t get_version = 0x00;
  constexpr uint8_t heartbeat_message = 0x01;
  constexpr uint8_t get_error = 0x03;
  constexpr uint8_t RxSdo = 0x04;
  constexpr uint8_t TxSdo = 0x05;
  constexpr uint8_t set_requested_state = 0x07;
  constexpr uint8_t get_encoder_estimate = 0x09;
  constexpr uint8_t set_controller_mode = 0x0B;
  constexpr uint8_t set_input_pos = 0x0C;
  constexpr uint8_t set_input_vel = 0x0D;
  constexpr uint8_t set_input_torque = 0x0E;
  constexpr uint8_t set_vel_curr_limits = 0x0F;
  constexpr uint8_t set_traj_vel_limit = 0x11;
  constexpr uint8_t set_traj_acc_limits = 0x12;
  constexpr uint8_t get_iq = 0x14;
  constexpr uint8_t get_temps = 0x15;
  constexpr uint8_t reboot_odrives = 0x16;
  constexpr uint8_t get_bus_voltage_current = 0x17;
  constexpr uint8_t clear_errors = 0x18;
  constexpr uint8_t set_absolute_position = 0x19;
  constexpr uint8_t set_pos_gain = 0x1A;
  constexpr uint8_t set_vel_gains = 0x1B;
}

// ==========================================================================
// ODrive Axis States
// ==========================================================================

namespace ODriveState {
  constexpr uint32_t IDLE = 1u;
  constexpr uint32_t ENCODER_INDEX_SEARCH = 6u;
  constexpr uint32_t CLOSED_LOOP = 8u;
}

// ODrive control modes
namespace ODriveControlMode {
  constexpr uint32_t VOLTAGE = 0u;
  constexpr uint32_t TORQUE = 1u;
  constexpr uint32_t VELOCITY = 2u;
  constexpr uint32_t POSITION = 3u;
}

// ODrive input modes
namespace ODriveInputMode {
  constexpr uint32_t PASSTHROUGH = 1u;
  constexpr uint32_t VEL_RAMP = 2u;
  constexpr uint32_t TRAP_TRAJ = 5u;
}

// ODrive error bit masks
namespace ODriveErrors {
  constexpr uint32_t BRAKE_RESISTOR_DISARMED = 0x8000000u;
}

// ==========================================================================
// CAN Node IDs — ODrive axis addresses
// ==========================================================================

namespace NodeId {
  constexpr uint8_t LEG_0 = 0;
  constexpr uint8_t LEG_1 = 1;
  constexpr uint8_t LEG_2 = 2;
  constexpr uint8_t LEG_3 = 3;
  constexpr uint8_t LEG_4 = 4;
  constexpr uint8_t LEG_5 = 5;
  constexpr uint8_t JUGGLEBOT_HAND = 6;
  constexpr uint8_t BB_PITCH = 7;
  constexpr uint8_t BB_HAND = 8;
}

// ==========================================================================
// Custom CAN Message IDs
// ==========================================================================

// Shared IDs — used by both Platform and Ball Butler Teensys
namespace SharedCanId {
  constexpr uint32_t TIME_SYNC = 0x7DD;
}

// Platform Teensy <-> Host
namespace PlatformCanId {
  constexpr uint32_t TRAJ_CMD = 0x6D0;
  constexpr uint32_t STATE_UPDATE = 0x6E0;
  constexpr uint32_t TILT_READING = 0x7DE;
  constexpr uint32_t TRAFFIC_REPORT = 0x7DF;
}

// Ball Butler Teensy <-> Host
namespace BallButlerCanId {
  constexpr uint32_t THROW_CMD = 0x7D0;
  constexpr uint32_t HEARTBEAT = 0x7D1;
  constexpr uint32_t RELOAD_CMD = 0x7D2;
  constexpr uint32_t RESET_CMD = 0x7D3;
  constexpr uint32_t CALIBRATE_LOC_CMD = 0x7D4;
}

// ==========================================================================
// Ball Butler State Machine
// ==========================================================================

namespace BallButler {
  constexpr uint32_t HEARTBEAT_TIMEOUT_MS = 500u;
}

// States — encoded in heartbeat byte 0 (bits 1-7)
namespace BallButlerState {
  constexpr uint8_t BOOT = 0;
  constexpr uint8_t IDLE = 1;
  constexpr uint8_t TRACKING = 2;
  constexpr uint8_t THROWING = 3;
  constexpr uint8_t RELOADING = 4;
  constexpr uint8_t CALIBRATING = 5;
  constexpr uint8_t CHECKING_BALL = 6;
  constexpr uint8_t ERROR = 127;
}

// Error codes — encoded in heartbeat byte 1 when state == ERROR
namespace BallButlerErrorCode {
  constexpr uint8_t NONE = 0;
  constexpr uint8_t RELOAD_FAILED = 1;
}

// ==========================================================================
// Encoding / Scaling
// ==========================================================================

// Ball Butler heartbeat CAN frame encoding resolutions
namespace HeartbeatEncoding {
  constexpr float yaw_res_deg = 0.01f;
  constexpr float pitch_res_deg = 0.002f;
  constexpr float hand_res_mm = 0.01f;
}

// ODrive input scaling (vel_ff and torque_ff are sent as int16 * scale)
namespace InputScale {
  constexpr float hand_vel = 100.0f;
  constexpr float hand_tor = 100.0f;
  constexpr float leg_vel = 1000.0f;
  constexpr float leg_tor = 10000.0f;
}

// ==========================================================================
// SDO — Arbitrary Parameter Access
// ==========================================================================

namespace SDO {
  constexpr uint8_t OPCODE_READ = 0x00;
  constexpr uint8_t OPCODE_WRITE = 0x01;
}

// ==========================================================================
// Endpoint IDs — ODrive internal parameter addresses
// ==========================================================================

namespace EndpointId {
  constexpr uint16_t commutation_mapper_pos_abs = 488;
  constexpr uint16_t GPIO_STATES = 700;
}

// ==========================================================================
// Motion Capture Alignment
// ==========================================================================

namespace MocapAlignment {
  constexpr float POS_THRESH_MM = 2.5f;
  constexpr float ROT_THRESH_DEG = 1.0f;
}
