"""Jetson-side client for the can-bridge Teensy over the dedicated UDP link.

Pure-Python; no ROS 2 dependency. Importable from ROS nodes
(``can_node.py``'s replacement bridge) and from standalone tools alike.

Public API:

    from teensy_link import TeensyLinkClient, RpcClient
    client = TeensyLinkClient()                   # connects to 192.168.42.2 by default
    client.start()                                # spawns RX + heartbeat threads
    client.subscribe(MsgType.TELEMETRY, on_telem) # register a frame callback
    rpc = RpcClient(client)
    result = rpc.time_of_day_query()              # blocking, with timeout/retry
    client.stop()

Protocol artefacts (frame layouts, constants, enums) live in
``config/generated/udp_protocol.py`` (regenerated by ``config/generate_udp_protocol.py``)
and are re-exported here via :mod:`teensy_link.protocol` so callers
have a single stable import path.

The can-bridge Teensy is the time-sync **master** (ADR-0008); the Jetson is the
wall-clock **anchor**. The :class:`TimeOfDayServer` answers
``RpcMethod.TIME_OF_DAY_QUERY`` requests from the Teensy with the current
``CLOCK_REALTIME`` in microseconds.
"""

from __future__ import annotations

from .protocol import (
    MsgType,
    RpcMethod,
    RpcStatus,
    LinkState,
    BusHealth,
    FaultState,
    GuardMode,
    Setpoint,
    HeartbeatJ2T,
    HeartbeatT2J,
    Telemetry,
    Diagnostic,
    Profile,
    ConeFrame,
    CmdResultFrame,
    BbAxisEstimates,
    LegCmd,
    PlatformFrame,
    HandCmdEcho,
    HandSensor,
    CanErrors,
    BridgeTxDiag,
    BridgeIdentity,
    ClockDiag,
    CacheDiag,
    RingDiag,
    RpcRequest,
    RpcResponse,
    hand_axis6_permitted,
)
from .client import TeensyLinkClient, LinkStats
from .rpc import RpcClient, RpcServer, RpcError, RpcTimeout
from .tod_server import TimeOfDayServer

__all__ = [
    # Constants / enums
    "MsgType",
    "RpcMethod",
    "RpcStatus",
    "LinkState",
    "BusHealth",
    "FaultState",
    "GuardMode",
    # Frame dataclasses
    "Setpoint",
    "HeartbeatJ2T",
    "HeartbeatT2J",
    "Telemetry",
    "Diagnostic",
    "Profile",
    "ConeFrame",
    "CmdResultFrame",
    "BbAxisEstimates",
    "LegCmd",
    "PlatformFrame",
    "HandCmdEcho",
    "HandSensor",
    "CanErrors",
    "BridgeTxDiag",
    "BridgeIdentity",
    "ClockDiag",
    "CacheDiag",
    "RingDiag",
    "RpcRequest",
    "RpcResponse",
    "hand_axis6_permitted",
    # Client + RPC infrastructure
    "TeensyLinkClient",
    "LinkStats",
    "RpcClient",
    "RpcServer",
    "RpcError",
    "RpcTimeout",
    "TimeOfDayServer",
]
