"""Re-export of the generated UDP protocol module.

Why this indirection: ``config/generated/udp_protocol.py`` is auto-generated by
``config/generate_udp_protocol.py`` and lives outside the package tree. We
expose it here under a stable import path (``teensy_link.protocol``) so callers
don't have to know about ``config/generated/`` or worry about ``sys.path``
shenanigans. If the generator's output location ever moves, only this file
changes.

DO NOT add anything to this module that isn't a thin re-export — the generated
file is the single source of truth for the wire format.
"""

from __future__ import annotations

import os as _os
import sys as _sys

# Locate the generated module. This package sits AT the repo root
# (``<repo>/teensy_link/``), so one ``..`` reaches the root — it was two while
# the package lived under ``controller/`` (moved 2026-08-01, refactor Phase 4).
_REPO_ROOT = _os.path.abspath(_os.path.join(_os.path.dirname(__file__), ".."))
_GEN_DIR = _os.path.join(_REPO_ROOT, "config", "generated")

# Make ``udp_protocol`` importable even if config/generated is not yet on
# sys.path (it isn't by default in the ROS2 build, and standalone scripts
# may not have configured it). Insert at position 0 so we win against any
# stale copies that might be on a deeper path.
if _GEN_DIR not in _sys.path:
    _sys.path.insert(0, _GEN_DIR)

# Re-export everything from the generated module.
from udp_protocol import (  # noqa: E402, F401
    # Constants
    PROTOCOL_VERSION,
    MAGIC,
    HEADER_SIZE,
    CRC_SIZE,
    MAX_PAYLOAD,
    MAX_FRAME,
    PORT_STREAM,
    PORT_RPC,
    TEENSY_IP_0,
    TEENSY_IP_1,
    TEENSY_IP_2,
    TEENSY_IP_3,
    JETSON_IP_3,
    NUM_LEGS,
    NUM_AXES,
    PROFILE_NUM_TASKS,
    HEARTBEAT_HZ,
    LINK_LOST_MISSES,
    HEARTBEAT_TORQUE_CLAMP_SHIFT,  # HeartbeatT2J.flags bit offset of TORQUE_CLAMP_MASK (bits 8-13)
    # Enums
    MsgType,
    RpcMethod,
    RpcStatus,
    LinkState,
    BusHealth,
    FaultState,
    GuardMode,
    HeartbeatT2JFlags,  # T2J heartbeat flag bits (incl. the per-leg TORQUE_CLAMP_MASK)
    HandSensorFlags,  # HAND_SENSOR flag bits (raw/debounced held, valid, stale, time_synced)
    ClockDiagFlags,  # CLOCK_DIAG flag bits (stepped, first anchor, freq-sample validity)
    # Framing
    crc16_ccitt,
    encode_frame,
    decode_frame,
    CrcError,
    # Payload structs
    Setpoint,
    HeartbeatJ2T,
    HeartbeatT2J,
    Telemetry,
    Diagnostic,
    Profile,
    ConeFrame,
    CmdResultFrame,
    BbAxisEstimates,
    LegCmd,
    PlatformFrame,
    HandCmdEcho,
    HandSensor,
    CanErrors,
    BridgeTxDiag,
    BridgeIdentity,
    ClockDiag,
    RpcRequest,
    RpcResponse,
    # Sizes
    SETPOINT_SIZE,
    HEARTBEAT_J2T_SIZE,
    HEARTBEAT_T2J_SIZE,
    TELEMETRY_SIZE,
    DIAGNOSTIC_SIZE,
    PROFILE_SIZE,
    CONE_FRAME_SIZE,
    CMD_RESULT_FRAME_SIZE,
    BB_AXIS_ESTIMATES_SIZE,
    LEG_CMD_SIZE,
    PLATFORM_FRAME_SIZE,
    HAND_CMD_ECHO_SIZE,
    HAND_SENSOR_SIZE,
    CAN_ERRORS_SIZE,
    BRIDGE_TX_DIAG_SIZE,
    BRIDGE_IDENTITY_SIZE,
    CLOCK_DIAG_SIZE,
    RPC_REQUEST_SIZE,
    RPC_RESPONSE_SIZE,
    # RPC method argument layouts (hoisted into the generator)
    AXIS_ALL,
    ArgAxisState,
    ArgControllerMode,
    ArgVelCurr,
    ArgPosGain,
    ArgVelGains,
    ArgAbsPosition,
    ArgAxisOnly,
    ArgSdoRead,
    ArgSdoWrite,
    ResultTimeOfDay,
    ArgBbThrow,
    ArgRobotState,
    ArgHandTraj,  # HAND_TRAJ_CMD — 8-byte 0x6D0 payload
    ResultAxisVersions,  # GET_AXIS_VERSIONS result blob
    # Hand axis-6 allow-table
    HAND_AXIS6_PERMITTED,
    hand_axis6_permitted,
)

TEENSY_IP: str = f"{TEENSY_IP_0}.{TEENSY_IP_1}.{TEENSY_IP_2}.{TEENSY_IP_3}"
"""Static IP of the can-bridge Teensy (per ADR-0007 point-to-point link)."""
