#!/usr/bin/env python3
"""Fleet-wide leg-ODrive config reset — back up, erase, reflash, restore node IDs.

Automates, across all six leg drives in one pass, the manual ``odrivetool``
procedure this project has used one drive at a time: ``erase_configuration()``
in the shell, then ``odrivetool restore-config``, then re-set
``axis0.config.can.node_id`` and save.

Standing quirk this exists to service: this machine's ODrives occasionally need
a config reset (cause unknown — one cured the 2026-08-10 leg-0
``SPINOUT_DETECTED``). A bare reset reverts every tuned value, so the reset is
only half the job — the config JSON has to go back on afterwards.

What it does, per drive
-----------------------
1. **Records** the USB-serial -> CAN-node-ID mapping for every drive on the bus
   and writes it to ``fleet_map.json`` *before* anything is erased. That file is
   the recovery key: an erased drive reports the firmware-default node ID, so
   the association is unrecoverable from the hardware alone.
2. **Backs up** the drive's current config (byte-for-byte what ``odrivetool
   backup-config`` writes) next to the map.
3. **Erases** with ``erase_configuration()``, then reboots so RAM holds defaults
   too, not just NVM.
4. **Reflashes** the target config with that drive's own node ID already patched
   in, then ``save_configuration()``.
5. **Verifies** — after a forced reboot, so the read comes from NVM — that every
   property in the target file reads back, and that the node ID is right.
6. **Calibrates**: ``FULL_CALIBRATION_SEQUENCE``, blocking until the axis returns
   to IDLE, then checking ``procedure_result``. **This moves the motor.**
7. **Saves once more**, reboots, and reports what calibration measured for that
   drive specifically — comparing the config before and after the procedure, so
   the report is what the drive did, not what this script assumed it would do.

Steps 6-7 are why the config verify sits at step 5 rather than at the end: the
calibration is about to spin the motor using the values just flashed
(``calib_scan_vel``, ``calibration_current``, the encoder setup), so proving NVM
holds them is worth doing while the axis is still stationary. The
calibration-owned properties are then excluded from the final verify — having
calibration overwrite them is the point.

**The calibration actuates the leg, and by default commands more travel than the
leg has.** ``calib_scan_distance`` is the **encoder-offset** (commutation) scan
length, not an index-search ceiling: the scan traverses the full distance one way
and then back, with no early exit when the index pulse arrives (ODrive 0.5.6
``Encoder::run_offset_calibration`` — the forward loop breaks only on
``total_distance >= calib_scan_distance``; Pro 0.6.x firmware is closed, but the
parameter moved from ``encoder.config`` to ``axis.config`` in 0.6 keeping the same
role and the same 8 rev / 2 rev-per-s defaults). The *index search* is the
separate sub-procedure that does stop at the pulse, bounded under 1 rev.

So the snapshot's 8.0 rev is ~564 mm of leg travel against a
``GEOM_LEG_STROKE_MM`` of 280 — 2x the stroke — at 2.0 rev/s ≈ 141 mm/s, and
nothing in the ODrive stops the scan at the end of travel. The script therefore refuses to start unless the scan fits the
stroke, and offers two ways forward: ``--calib-scan-distance <rev>`` to shorten
the scan, or ``--force`` when the legs are mechanically free to run that far.
There is also one confirmation prompt before the first drive is touched
(``--yes`` skips it) and ``--no-calibration`` to flash config only, with no
motion at all.

Two design points worth knowing:

*The node ID is patched into the restore dict rather than fixed up afterwards*,
so no ``save_configuration()`` ever commits the wrong node ID to NVM. Six drives
persistently answering as node 0 on a shared bus is worth one less reboot.

*The verify pass forces a reboot first.* After the restore, the correct values
are already in RAM — so a verify that reads a live drive cannot distinguish a
successful ``save_configuration()`` from one that silently refused (an armed
axis, for instance). Only a post-reboot read proves NVM took it.

The hand drive (CAN node 6, ``NODE_ID_JUGGLEBOT_HAND``) is discovered, recorded,
and then left strictly alone — it runs a different config file
(``odrive_pro_hand_config.json``: ONBOARD_ENCODER0, not INC_ENCODER0).

Per-motor calibration values — ``commutation_mapper.config.index_offset``,
``motor.phase_resistance``/``phase_inductance`` — are flashed **verbatim from
the snapshot and are NOT preserved per drive** (owner's call, 2026-08-12: they
are regenerated by calibration). Steps 6-7 then regenerate them per drive, which
is what makes flashing one drive's snapshot onto all six correct rather than
merely tolerable. Under ``--no-calibration`` that no longer holds: each leg
carries the snapshot drive's commutation offset until its own index search runs,
so **home every leg before arming it.**

The window in between is worth knowing about. Between step 4's save and step 6's
success, NVM holds the snapshot's commutation offset *marked valid* while the
drive's own calibration has not run. A calibration failure aborts the run and
says so explicitly: that leg must not be armed until calibration succeeds.

Preconditions
-------------
* All seven drives powered and on USB.
* The ROS stack **stopped**. A live ``teensy_bridge_node`` streams setpoints to
  CAN node IDs 0-5 at 500 Hz, and freshly-erased drives all answer as one node.
  The script refuses to start if it sees one (``--force`` overrides). An open
  ``odrivetool`` shell or ODrive GUI is the same problem for a different reason:
  it holds an exclusive USB claim on the drives.
* Every axis idle — ``save_configuration()`` refuses on an armed axis.
* **Every leg free to move the calibration scan distance**, and nothing in the
  way of the platform, unless you are running ``--no-calibration``.

Usage
-----
    source ~/Desktop/PDJ_venv/venv/bin/activate

    # read-only: discover, record the map, back everything up, diff vs target
    python tools/odrive_fleet_reflash.py --dry-run

    # config only, no motion at all
    python tools/odrive_fleet_reflash.py --no-calibration

    # flash + calibrate, one leg at a time, pausing between legs
    python tools/odrive_fleet_reflash.py --calib-scan-distance 3.0 --pause-between-legs

    # one drive only; or resume a partial run off the recorded map
    python tools/odrive_fleet_reflash.py --only 3
    python tools/odrive_fleet_reflash.py --map temp/odrive_configs/<ts>/fleet_map.json

``--map`` is the fix for the one state this script can otherwise not reason
about: a run that died between erase and restore leaves a drive at the default
node ID, which collides with leg 0 and makes the live node-ID read ambiguous.
The map resolves node IDs by USB serial instead, so a rerun just works.

Recovery: every drive's pre-erase config is in the backup directory and is
restorable with ``odrivetool restore-config <backup.json>`` — though ``--map``
plus a rerun is usually faster, since the backup carries the old node ID too.
"""

from __future__ import annotations

import argparse
import copy
import json
import math
import os
import sys
import time
from datetime import datetime
from typing import Any, Dict, List, Optional, Sequence, Tuple

_SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
_PROJECT_ROOT = os.path.dirname(_SCRIPT_DIR)
_GENERATED_DIR = os.path.join(_PROJECT_ROOT, 'config', 'generated')

sys.path.insert(0, _GENERATED_DIR)
import protocol_config as proto  # noqa: E402
import hardware_config as hw     # noqa: E402

# ---------------------------------------------------------------------------
# Constants
# ---------------------------------------------------------------------------

#: Node IDs this script will erase and reflash. From the generated config so the
#: fleet definition has one home (``config/protocol_config.yaml``).
LEG_NODE_IDS: Tuple[int, ...] = tuple(proto.NODE_ID_LEGS)

#: Node IDs that are discovered and recorded but never written to.
PROTECTED_NODE_IDS: Tuple[int, ...] = (proto.NODE_ID_JUGGLEBOT_HAND,)

DEFAULT_TARGET_CONFIG = os.path.join(
    _PROJECT_ROOT, 'config', 'ODrive config Files', 'odrive_pro_leg_config.json'
)
DEFAULT_BACKUP_ROOT = os.path.join(_PROJECT_ROOT, 'temp', 'odrive_configs')

NODE_ID_PATH = 'axis0.config.can.node_id'
COMMUTATION_ENCODER_PATH = 'axis0.config.commutation_encoder'
CALIB_SCAN_DISTANCE_PATH = 'axis0.config.calib_scan_distance'
CALIB_SCAN_VEL_PATH = 'axis0.config.calib_scan_vel'

#: Leg spool geometry, for expressing the open-loop calibration scan in
#: millimetres of leg travel. Per-leg because the spools differ slightly.
MM_PER_REV: Tuple[float, ...] = tuple(1.0 / g for g in hw.GEOM_MM_TO_REV)
LEG_STROKE_MM: float = float(hw.GEOM_LEG_STROKE_MM)

#: Axis states and procedure results, as raw ints so this module stays
#: importable without the odrive package. Cross-checked against
#: odrive.enums.AxisState / ProcedureResult (0.6.10) — the runtime decodes
#: names through the installed enums, these drive the state machine.
AXIS_STATE_IDLE = 1
AXIS_STATE_FULL_CALIBRATION_SEQUENCE = 3
PROCEDURE_RESULT_SUCCESS = 0
PROCEDURE_RESULT_BUSY = 1

#: Properties FULL_CALIBRATION_SEQUENCE is expected to rewrite. Excluded from
#: the post-calibration config verify — calibration overwriting them is the
#: point, so diffing them against the snapshot would report every leg as failed.
#: Anything calibration changes OUTSIDE this set is surfaced as a warning rather
#: than assumed benign: this list is what we expect, not what we know.
CALIBRATION_OWNED_PATHS = frozenset({
    'axis0.config.motor.phase_resistance',
    'axis0.config.motor.phase_resistance_valid',
    'axis0.config.motor.phase_inductance',
    'axis0.config.motor.phase_inductance_valid',
    'axis0.config.motor.direction',
    'axis0.commutation_mapper.config.index_offset',
    'axis0.commutation_mapper.config.index_offset_valid',
    'axis0.commutation_mapper.config.offset',
    'axis0.commutation_mapper.config.offset_valid',
    'axis0.pos_vel_mapper.config.index_offset',
    'axis0.pos_vel_mapper.config.index_offset_valid',
    'axis0.pos_vel_mapper.config.offset',
    'axis0.pos_vel_mapper.config.offset_valid',
})

#: Calibration timings. 8 rev at 2 rev/s is ~4 s of scan plus motor calibration;
#: 90 s is generous enough for a slow scan without hanging the run forever.
CALIB_TIMEOUT_S = 90.0
CALIB_START_GRACE_S = 3.0
CALIB_POLL_S = 0.25

#: EncoderId.INC_ENCODER0 — what a leg commutates off. The hand config says 13
#: (ONBOARD_ENCODER0), which is how this script recognises the wrong file.
INC_ENCODER0 = 1

#: Discovery / reboot timings. A Pro takes ~2 s to drop off USB and come back.
DISCOVERY_TIMEOUT_S = 30.0
REBOOT_SETTLE_S = 2.0
REBOOT_TIMEOUT_S = 30.0

#: Processes that must not be running: the first three command the drives over
#: CAN, the last two hold an exclusive USB claim on them.
CONFLICTING_PATTERNS = (
    'teensy_bridge_node',
    'jugglebot_launch',
    'trajectory_node',
    'odrivetool',
    'odrive_gui',
)


# ---------------------------------------------------------------------------
# Pure helpers (no hardware; unit-tested in tests/motion/)
# ---------------------------------------------------------------------------

def flatten_config(nested: Dict[str, Any], prefix: str = '') -> Dict[str, Any]:
    """Flatten a nested config dict to ``{'a.b.c': value}``.

    Accepts an already-flat dict unchanged, so it works on both shapes of
    backup file: this odrivetool writes flat, older ones wrote nested.
    """
    flat: Dict[str, Any] = {}
    for key, value in nested.items():
        path = '{}.{}'.format(prefix, key) if prefix else key
        if isinstance(value, dict):
            flat.update(flatten_config(value, path))
        else:
            flat[path] = value
    return flat


def set_config_value(config: Dict[str, Any], path: str, value: Any) -> Dict[str, Any]:
    """Return a copy of ``config`` with ``path`` set to ``value``.

    Handles both file shapes: this odrivetool writes flat backups (the whole
    dotted path is one key), older ones and the repo snapshot were nested.

    Raises ``KeyError`` if the path is absent, which means the file is not the
    ODrive config backup it was taken for — cheaper to catch here than after
    six drives have been erased.
    """
    patched = copy.deepcopy(config)

    if path in patched:  # flat shape
        patched[path] = value
        return patched

    parts = path.split('.')
    node = patched
    for part in parts[:-1]:
        child = node.get(part)
        if not isinstance(child, dict):
            raise KeyError(
                'target config has no {} — is this an ODrive config backup?'.format(path))
        node = child
    if parts[-1] not in node:
        raise KeyError(
            'target config has no {} — is this an ODrive config backup?'.format(path))
    node[parts[-1]] = value
    return patched


def patch_node_id(config: Dict[str, Any], node_id: int) -> Dict[str, Any]:
    """Return a copy of ``config`` carrying ``node_id`` instead of the snapshot's."""
    return set_config_value(config, NODE_ID_PATH, int(node_id))


def calibration_travel_mm(scan_distance_rev: float, node_id: int) -> float:
    """Leg travel commanded by an open-loop calibration scan of that many revs."""
    if not 0 <= node_id < len(MM_PER_REV):
        raise IndexError('no spool geometry for node ID {}'.format(node_id))
    return scan_distance_rev * MM_PER_REV[node_id]


def check_calibration_travel(
    scan_distance_rev: float,
    node_ids: Sequence[int],
    stroke_mm: float = LEG_STROKE_MM,
) -> List[str]:
    """Problems if the calibration scan would drive a leg past its stroke.

    ``ENCODER_OFFSET_CALIBRATION`` scans open-loop for ``calib_scan_distance``
    revolutions — it has no idea the axis is a spool on a 280 mm actuator, and
    nothing in the ODrive stops it at the end of travel.

    Necessary but not sufficient: this compares against the WHOLE stroke, while
    the leg needs that much travel remaining *in the scan direction*. The scan
    runs the full distance one way and then back (ODrive 0.5.6
    ``Encoder::run_offset_calibration``: the forward loop's only exit is
    ``total_distance >= calib_scan_distance``, with no index check), so the
    excursion is one-directional from wherever the leg happens to be sitting.
    """
    problems: List[str] = []
    for node_id in sorted(set(node_ids)):
        travel = calibration_travel_mm(scan_distance_rev, node_id)
        if travel > stroke_mm:
            problems.append(
                'node {}: a {:.1f} rev scan is {:.0f} mm of leg travel against a '
                '{:.0f} mm stroke ({:.1f}x)'.format(
                    node_id, scan_distance_rev, travel, stroke_mm, travel / stroke_mm))
    return problems


def describe_calibration_motion(
    scan_distance_rev: float,
    scan_vel_rev_s: float,
    node_ids: Sequence[int],
) -> List[str]:
    """Human-readable summary of what the calibration will physically do."""
    lines = [
        'FULL_CALIBRATION_SEQUENCE will be run on node(s) {}, one at a time.'.format(
            sorted(set(node_ids))),
        'It MOVES THE MOTOR: motor calibration (a twitch), index search (bounded',
        'by the index pulse, under 1 rev — this robot has measured ~0.035 rev),',
        'then an open-loop encoder-offset scan of {:.1f} rev at {:.1f} rev/s.'.format(
            scan_distance_rev, scan_vel_rev_s),
        'The offset scan does NOT stop at the index: it runs the full distance one',
        'way and back, so the excursion below is one-directional from wherever the',
        'leg is sitting. Position each leg with that much travel free.',
    ]
    for node_id in sorted(set(node_ids)):
        lines.append('  node {}: {:.0f} mm of leg travel at {:.0f} mm/s (stroke {:.0f} mm)'.format(
            node_id,
            calibration_travel_mm(scan_distance_rev, node_id),
            scan_vel_rev_s * MM_PER_REV[node_id],
            LEG_STROKE_MM))
    return lines


def values_equal(left: Any, right: Any) -> bool:
    """Compare two config values, treating NaN as equal to NaN.

    Every value here has made a float32 round trip through the same codec, so
    an exact comparison is right — a tolerance would hide a failed write.
    """
    if isinstance(left, float) and isinstance(right, float):
        if math.isnan(left) and math.isnan(right):
            return True
    try:
        return bool(left == right)
    except Exception:
        return False


def diff_flat(actual: Dict[str, Any], expected: Dict[str, Any]) -> List[Tuple[str, Any, Any]]:
    """Rows of ``(path, actual, expected)`` where the drive disagrees.

    Iterates the *expected* keys only: the drive legitimately exposes config
    properties the snapshot does not carry, and those are not a mismatch.
    """
    rows: List[Tuple[str, Any, Any]] = []
    for path in sorted(expected):
        want = expected[path]
        if path not in actual:
            rows.append((path, '<absent on drive>', want))
        elif not values_equal(actual[path], want):
            rows.append((path, actual[path], want))
    return rows


def check_target_is_leg_config(flat_target: Dict[str, Any]) -> List[str]:
    """Refuse a target file that is plainly not a leg config.

    The hand snapshot commutates off ONBOARD_ENCODER0; flashing it to a leg
    would leave the leg with no usable commutation source.
    """
    problems: List[str] = []
    encoder = flat_target.get(COMMUTATION_ENCODER_PATH)
    if encoder is None:
        problems.append('{} missing — not an ODrive Pro axis config'.format(COMMUTATION_ENCODER_PATH))
    elif encoder != INC_ENCODER0:
        problems.append(
            '{} is {} (expected {} = INC_ENCODER0). This looks like the HAND '
            'config, not a leg config.'.format(COMMUTATION_ENCODER_PATH, encoder, INC_ENCODER0)
        )
    return problems


def validate_fleet(
    node_by_serial: Dict[str, int],
    leg_ids: Sequence[int] = LEG_NODE_IDS,
    protected_ids: Sequence[int] = PROTECTED_NODE_IDS,
) -> Tuple[List[str], List[str]]:
    """Check a discovered fleet. Returns ``(errors, warnings)``.

    Errors are conditions under which the serial -> node-ID association cannot
    be trusted, and so nothing may be erased.
    """
    errors: List[str] = []
    warnings: List[str] = []
    ids = list(node_by_serial.values())

    duplicates = sorted({i for i in ids if ids.count(i) > 1})
    if duplicates:
        errors.append(
            'node IDs {} reported by more than one drive — cannot tell which leg is '
            'which. If a previous run was interrupted mid-erase, rerun with '
            '--map <fleet_map.json> to resolve node IDs by USB serial.'.format(duplicates)
        )

    missing_legs = [i for i in leg_ids if i not in ids]
    if missing_legs:
        errors.append('leg node IDs {} not found on USB'.format(missing_legs))

    known = set(leg_ids) | set(protected_ids)
    unexpected = sorted({i for i in ids if i not in known})
    if unexpected:
        errors.append(
            'unrecognised node IDs {} on USB — not in the leg set {} or the '
            'protected set {}. Refusing to guess.'.format(
                unexpected, list(leg_ids), list(protected_ids))
        )

    missing_protected = [i for i in protected_ids if i not in ids]
    if missing_protected:
        warnings.append(
            'protected node IDs {} not found on USB (hand drive unplugged or '
            'unpowered?) — nothing to protect, continuing'.format(missing_protected))

    return errors, warnings


def find_conflicting_processes(cmdlines: Sequence[str]) -> List[Tuple[str, str]]:
    """Match running command lines against ``CONFLICTING_PATTERNS``."""
    self_name = os.path.basename(__file__)
    hits: List[Tuple[str, str]] = []
    for cmd in cmdlines:
        if self_name in cmd:
            continue  # this process, or a sibling invocation of it
        for pattern in CONFLICTING_PATTERNS:
            if pattern in cmd:
                hits.append((pattern, cmd))
                break
    return hits


def read_proc_cmdlines() -> List[str]:
    """Command lines of every visible process. Best effort — empty on failure."""
    cmdlines: List[str] = []
    try:
        pids = [entry for entry in os.listdir('/proc') if entry.isdigit()]
    except OSError:
        return cmdlines
    for pid in pids:
        try:
            with open('/proc/{}/cmdline'.format(pid), 'rb') as handle:
                raw = handle.read()
        except OSError:
            continue  # process exited, or not ours to read
        if raw:
            cmdlines.append(raw.replace(b'\0', b' ').decode('utf-8', 'replace').strip())
    return cmdlines


# ---------------------------------------------------------------------------
# Hardware layer
# ---------------------------------------------------------------------------

class OdriveApi:
    """The bits of the odrive package this script uses.

    Imported lazily so the module stays importable (and unit-testable) on a box
    without the odrive package or without hardware attached.
    """

    def __init__(self) -> None:
        try:
            import odrive
            from odrive.enums import AxisState, ODriveError, ProcedureResult
            from odrive.legacy_config import backup_config, restore_config
            from odrive.libodrive import DeviceLostException
        except ImportError as exc:
            raise SystemExit(
                'could not import the odrive package ({}).\n'
                'Activate the project venv first:\n'
                '    source ~/Desktop/PDJ_venv/venv/bin/activate'.format(exc)
            )
        self.odrive = odrive
        self.backup_config = backup_config
        self.restore_config = restore_config
        self.DeviceLostException = DeviceLostException
        self.AxisState = AxisState
        self.ProcedureResult = ProcedureResult
        self.ODriveError = ODriveError

        # The state machine below drives raw ints so the module imports without
        # this package; assert they still mean what they meant on 0.6.10.
        assert int(AxisState.IDLE) == AXIS_STATE_IDLE
        assert int(AxisState.FULL_CALIBRATION_SEQUENCE) == AXIS_STATE_FULL_CALIBRATION_SEQUENCE
        assert int(ProcedureResult.SUCCESS) == PROCEDURE_RESULT_SUCCESS
        assert int(ProcedureResult.BUSY) == PROCEDURE_RESULT_BUSY

    def procedure_name(self, value: int) -> str:
        try:
            return self.ProcedureResult(value).name
        except Exception:
            return 'UNKNOWN({})'.format(value)

    def error_name(self, bitmask: int) -> str:
        if not bitmask:
            return 'none'
        try:
            return str(self.ODriveError(bitmask))
        except Exception:
            return hex(bitmask)


def usb_serial(odrv: Any) -> str:
    """The USB serial string, which is what ``find_sync`` matches on.

    Deliberately ``_dev.serial_number`` and not ``odrv.serial_number``: the
    latter is the firmware's uint64 property, while discovery keys off the USB
    descriptor string in ``RuntimeDevice.serial_number``.
    """
    return odrv._dev.serial_number


def read_node_id(odrv: Any) -> int:
    return int(odrv.axis0.config.can.node_id)


def read_fw_version(odrv: Any) -> Optional[str]:
    try:
        return '{}.{}.{}'.format(
            odrv.fw_version_major, odrv.fw_version_minor, odrv.fw_version_revision
        )
    except Exception:
        return None


def is_alive(odrv: Any) -> bool:
    """True if the handle still answers a read."""
    try:
        read_node_id(odrv)
        return True
    except Exception:
        return False


def discover(api: OdriveApi, count: int, timeout: float) -> List[Any]:
    """Block until ``count`` drives are connected, then return them."""
    print('Waiting for {} ODrives on USB (timeout {:.0f} s)...'.format(count, timeout))
    try:
        drives = api.odrive.find_sync(count=count, timeout=timeout)
    except TimeoutError:
        raise SystemExit(
            'timed out waiting for {} ODrives. Check power and USB, or pass '
            '--expect <n> if fewer are attached.'.format(count)
        )
    return list(drives)


def call_tolerating_reboot(odrv: Any, api: OdriveApi, name: str) -> bool:
    """Call a function that is expected to reboot the drive.

    Returns True if the drive went away (the call landed and the reboot began).
    """
    if not hasattr(odrv, name):
        # Never silently skip the erase: "reflashed without erasing" is a
        # different operation from the one the caller asked for.
        raise SystemExit(
            'this firmware exposes no {}() — refusing to continue, since the '
            'erase step cannot be verified.'.format(name))
    try:
        getattr(odrv, name)()
    except api.DeviceLostException:
        return True
    except Exception as exc:
        # Not necessarily fatal: some transports surface the lost connection as
        # a generic error on the reboot ack path. Probe rather than assume.
        print('      note: {}() raised {}: {}'.format(name, type(exc).__name__, exc))
    return not is_alive(odrv)


class CalibrationOutcome:
    """What FULL_CALIBRATION_SEQUENCE did on one axis."""

    def __init__(self) -> None:
        self.started = False
        self.timed_out = False
        self.result: Optional[int] = None
        self.result_name = 'not run'
        self.active_errors = 0
        self.disarm_reason = 0
        self.elapsed_s = 0.0

    @property
    def ok(self) -> bool:
        return (
            self.started
            and not self.timed_out
            and self.result == PROCEDURE_RESULT_SUCCESS
            and self.active_errors == 0
        )

    def __str__(self) -> str:
        if self.timed_out:
            return 'TIMED OUT after {:.0f} s (last result {})'.format(
                self.elapsed_s, self.result_name)
        if not self.started:
            return 'never started ({})'.format(self.result_name)
        return '{} in {:.1f} s'.format(self.result_name, self.elapsed_s)


def run_full_calibration(api: OdriveApi, odrv: Any, timeout_s: float) -> CalibrationOutcome:
    """Run FULL_CALIBRATION_SEQUENCE on axis0 and block until it finishes.

    THIS MOVES THE MOTOR. Never returns while the axis is still calibrating: an
    early return would let the caller save the config mid-procedure.
    """
    axis = odrv.axis0
    outcome = CalibrationOutcome()

    errors = int(axis.active_errors)
    if errors:
        # A latched error makes the state request a no-op, which would otherwise
        # look like "calibration finished instantly".
        print('      clearing latched active_errors: {}'.format(api.error_name(errors)))
        try:
            odrv.clear_errors()
        except Exception as exc:
            print('      note: clear_errors() raised {}: {}'.format(type(exc).__name__, exc))

    state = int(axis.current_state)
    if state != AXIS_STATE_IDLE:
        raise SystemExit(
            'axis is in state {}, not IDLE — refusing to start a calibration on '
            'an axis that is already doing something.'.format(state))

    start = time.time()
    axis.requested_state = AXIS_STATE_FULL_CALIBRATION_SEQUENCE

    # Wait for it to actually begin. procedure_result holds the PREVIOUS
    # outcome until the new procedure starts, so polling it alone can read a
    # stale SUCCESS and declare victory before the motor has moved.
    grace_deadline = time.time() + CALIB_START_GRACE_S
    while time.time() < grace_deadline:
        if (int(axis.current_state) != AXIS_STATE_IDLE
                or int(axis.procedure_result) == PROCEDURE_RESULT_BUSY):
            outcome.started = True
            break
        time.sleep(CALIB_POLL_S)

    if not outcome.started:
        outcome.result = int(axis.procedure_result)
        outcome.result_name = api.procedure_name(outcome.result)
        outcome.active_errors = int(axis.active_errors)
        outcome.disarm_reason = int(axis.disarm_reason)
        outcome.elapsed_s = time.time() - start
        return outcome

    deadline = time.time() + timeout_s
    while True:
        idle = int(axis.current_state) == AXIS_STATE_IDLE
        settled = int(axis.procedure_result) != PROCEDURE_RESULT_BUSY
        if idle and settled:
            break
        if time.time() > deadline:
            outcome.timed_out = True
            try:
                axis.requested_state = AXIS_STATE_IDLE  # stop the motor
            except Exception:
                pass
            break
        time.sleep(CALIB_POLL_S)

    outcome.elapsed_s = time.time() - start
    outcome.result = int(axis.procedure_result)
    outcome.result_name = api.procedure_name(outcome.result)
    outcome.active_errors = int(axis.active_errors)
    outcome.disarm_reason = int(axis.disarm_reason)
    return outcome


def wait_for_drive(api: OdriveApi, serial: str, timeout: float = REBOOT_TIMEOUT_S) -> Any:
    """Wait for ``serial`` to reappear after a reboot and answer a read."""
    time.sleep(REBOOT_SETTLE_S)  # let the old handle be reaped before re-asking
    deadline = time.time() + timeout
    while True:
        remaining = deadline - time.time()
        if remaining <= 0:
            raise SystemExit(
                'ODrive {} did not come back within {:.0f} s of a reboot. Its '
                'config may be half-written — restore from the backup in the '
                'backup directory before using it.'.format(serial, timeout)
            )
        try:
            odrv = api.odrive.find_sync(serial_number=serial, timeout=remaining)
        except TimeoutError:
            continue
        if is_alive(odrv):
            return odrv
        time.sleep(0.5)


# ---------------------------------------------------------------------------
# Per-drive procedure
# ---------------------------------------------------------------------------

class DriveResult:
    def __init__(self, node_id: int, serial: str) -> None:
        self.node_id = node_id
        self.serial = serial
        self.backup_path: Optional[str] = None
        self.restore_errors: List[str] = []
        self.verify_rows: List[Tuple[str, Any, Any]] = []
        self.node_id_after: Optional[int] = None
        self.calibration: Optional[CalibrationOutcome] = None
        self.calib_changes: List[Tuple[str, Any, Any]] = []
        self.unexpected_calib_changes: List[Tuple[str, Any, Any]] = []
        self.status = 'not started'

    @property
    def ok(self) -> bool:
        calibration_ok = self.calibration is None or self.calibration.ok
        return (
            self.status == 'done'
            and not self.restore_errors
            and not self.verify_rows
            and self.node_id_after == self.node_id
            and calibration_ok
        )


def write_backup(api: OdriveApi, odrv: Any, path: str) -> Dict[str, Any]:
    """Read the drive's config and write it in ``odrivetool backup-config`` form."""
    config = api.backup_config(odrv)
    with open(path, 'w') as handle:
        json.dump(config, handle, indent=2)
    return config


def process_drive(
    api: OdriveApi,
    odrv: Any,
    node_id: int,
    target_nested: Dict[str, Any],
    backup_dir: str,
    ignore_restore_errors: bool,
    calibrate: bool = False,
    calib_timeout: float = CALIB_TIMEOUT_S,
) -> DriveResult:
    """Back up, erase, reflash, verify, then optionally calibrate one drive."""
    serial = usb_serial(odrv)
    result = DriveResult(node_id, serial)
    print('\n--- node {} (USB {}) -----------------------------------'.format(node_id, serial))

    # 1. Back up before anything is destroyed.
    result.backup_path = os.path.join(
        backup_dir, 'pre_erase_node{}_{}.json'.format(node_id, serial))
    write_backup(api, odrv, result.backup_path)
    print('  backed up  -> {}'.format(os.path.relpath(result.backup_path, _PROJECT_ROOT)))

    # 2. Erase NVM, then reboot so RAM holds defaults too.
    print('  erasing configuration...')
    if not call_tolerating_reboot(odrv, api, 'erase_configuration'):
        call_tolerating_reboot(odrv, api, 'reboot')
    odrv = wait_for_drive(api, serial)
    print('  erased; drive reports node ID {} (firmware default)'.format(read_node_id(odrv)))

    # 3. Restore the target config with this drive's own node ID patched in, so
    #    the save below never commits the wrong one.
    patched = patch_node_id(target_nested, node_id)
    print('  restoring config with node_id={}...'.format(node_id))
    result.restore_errors = list(api.restore_config(odrv, patched) or [])
    for line in result.restore_errors:
        print('    ! {}'.format(line))
    if result.restore_errors and not ignore_restore_errors:
        result.status = 'restore errors'
        raise SystemExit(
            '\n{} property write(s) failed on node {}. Stopping before the next '
            'drive — this usually means a firmware/snapshot mismatch, which '
            'would repeat on all six.\nThe drive is left with the values that '
            'did apply, UNSAVED; power-cycle it to get the erased defaults '
            'back, or restore {}.\nPass --ignore-restore-errors if these '
            'warnings are expected.'.format(
                len(result.restore_errors), node_id,
                os.path.relpath(result.backup_path, _PROJECT_ROOT))
        )

    # 4. Commit to NVM, then reboot — so step 5 reads NVM and not RAM.
    print('  saving configuration...')
    if not call_tolerating_reboot(odrv, api, 'save_configuration'):
        call_tolerating_reboot(odrv, api, 'reboot')
    odrv = wait_for_drive(api, serial)

    # 5. Verify against what we meant to write. Deliberately BEFORE calibration:
    #    the calibration is about to spin the motor using these very values
    #    (calib_scan_vel, calibration_current, the encoder setup), so proving
    #    they are what NVM holds is worth doing while the axis is still still.
    result.node_id_after = read_node_id(odrv)
    flat_patched = flatten_config(patched)
    result.verify_rows = diff_flat(api.backup_config(odrv), flat_patched)
    result.status = 'done'

    if result.node_id_after != node_id:
        print('  ! node ID reads {} after reboot, expected {}'.format(
            result.node_id_after, node_id))
    if result.verify_rows:
        print('  ! {} property(ies) do not match the target after reboot:'.format(
            len(result.verify_rows)))
        for path, actual, want in result.verify_rows[:20]:
            print('      {}: drive={!r} target={!r}'.format(path, actual, want))
        if len(result.verify_rows) > 20:
            print('      ... and {} more'.format(len(result.verify_rows) - 20))
    if not result.verify_rows and result.node_id_after == node_id:
        print('  verified: node ID {} and all {} properties match NVM'.format(
            node_id, len(flat_patched)))

    if not calibrate:
        return result

    # 6. Calibrate. Snapshot first so the report of what calibration wrote is
    #    measured rather than assumed.
    pre_calib = api.backup_config(odrv)
    print('  running FULL_CALIBRATION_SEQUENCE — THE MOTOR WILL MOVE...')
    result.calibration = run_full_calibration(api, odrv, calib_timeout)
    print('  calibration: {}'.format(result.calibration))
    if result.calibration.active_errors or result.calibration.disarm_reason:
        print('    active_errors : {}'.format(api.error_name(result.calibration.active_errors)))
        print('    disarm_reason : {}'.format(api.error_name(result.calibration.disarm_reason)))

    if not result.calibration.ok:
        raise SystemExit(
            '\ncalibration FAILED on node {} ({}). Stopping before the next '
            'drive.\nThis leg now holds the flashed config in NVM — including '
            'the snapshot\'s commutation offset, marked valid — but its own '
            'calibration did NOT run. DO NOT ARM IT until calibration '
            'succeeds.\nCheck that the leg was free to move {:.0f} mm before '
            'retrying: --only {} reruns just this drive.'.format(
                node_id, result.calibration,
                calibration_travel_mm(
                    float(flat_patched.get(CALIB_SCAN_DISTANCE_PATH, 0.0)), node_id),
                node_id))

    # 7. One last save, so the freshly measured values survive a power cycle,
    #    then reboot and re-read — same reasoning as step 4/5.
    print('  saving calibration...')
    if not call_tolerating_reboot(odrv, api, 'save_configuration'):
        call_tolerating_reboot(odrv, api, 'reboot')
    odrv = wait_for_drive(api, serial)

    post_calib = api.backup_config(odrv)
    result.node_id_after = read_node_id(odrv)
    # What calibration actually changed, measured: (path, before, after).
    result.calib_changes = diff_flat(pre_calib, post_calib)
    result.unexpected_calib_changes = [
        row for row in result.calib_changes if row[0] not in CALIBRATION_OWNED_PATHS]
    # Re-verify the config, minus what calibration is supposed to own.
    result.verify_rows = [
        row for row in diff_flat(post_calib, flat_patched)
        if row[0] not in CALIBRATION_OWNED_PATHS]

    if result.calib_changes:
        print('  calibration wrote {} property(ies):'.format(len(result.calib_changes)))
        for path, before, after in result.calib_changes:
            marker = '   ' if path in CALIBRATION_OWNED_PATHS else ' ? '
            print('    {}{}: {!r} -> {!r}'.format(marker, path, before, after))
    else:
        print('  ! calibration reported success but changed no stored property')
    if result.unexpected_calib_changes:
        print('  ! {} of those are outside the expected calibration set (marked ?)'.format(
            len(result.unexpected_calib_changes)))
    if result.verify_rows:
        print('  ! {} property(ies) still do not match the target:'.format(
            len(result.verify_rows)))
        for path, actual, want in result.verify_rows[:20]:
            print('      {}: drive={!r} target={!r}'.format(path, actual, want))
    if result.ok:
        print('  verified after calibration: node ID {}, config matches, '
              'calibration SUCCESS'.format(node_id))
    return result


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def parse_args(argv: Optional[Sequence[str]] = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description='Erase and reflash the leg ODrives, preserving CAN node IDs.',
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog='Run with --dry-run first if you want to see the diff before erasing.',
    )
    parser.add_argument('--config', default=DEFAULT_TARGET_CONFIG,
                        help='config JSON to flash (default: the leg snapshot)')
    parser.add_argument('--backup-dir', default=None,
                        help='where to write the map and backups '
                             '(default: temp/odrive_configs/<timestamp>/)')
    parser.add_argument('--dry-run', action='store_true',
                        help='discover, record the map, back up and diff — erase nothing')
    parser.add_argument('--only', default=None,
                        help='comma-separated node IDs to process (default: all legs)')
    parser.add_argument('--map', default=None,
                        help='resolve node IDs from a previously written fleet_map.json '
                             'instead of reading them off the drives')
    parser.add_argument('--expect', type=int, default=len(LEG_NODE_IDS) + len(PROTECTED_NODE_IDS),
                        help='number of drives to wait for on USB (default: %(default)s)')
    parser.add_argument('--timeout', type=float, default=DISCOVERY_TIMEOUT_S,
                        help='discovery timeout in seconds (default: %(default)s)')
    parser.add_argument('--ignore-restore-errors', action='store_true',
                        help='keep going when a property write fails (default: stop)')
    parser.add_argument('--no-calibration', action='store_true',
                        help='skip FULL_CALIBRATION_SEQUENCE — flash config only, no motion')
    parser.add_argument('--calib-scan-distance', type=float, default=None,
                        help='override axis0.config.calib_scan_distance (rev) for the '
                             'calibration scan — lower it to fit the leg stroke')
    parser.add_argument('--calib-timeout', type=float, default=CALIB_TIMEOUT_S,
                        help='seconds to wait for one calibration (default: %(default)s)')
    parser.add_argument('--pause-between-legs', action='store_true',
                        help='wait for Enter after each leg, to inspect before the next moves')
    parser.add_argument('--yes', action='store_true',
                        help='skip the confirmation prompt for the motion the calibration '
                             'commands (fully unattended)')
    parser.add_argument('--force', action='store_true',
                        help='proceed despite conflicting processes, a suspect config file, '
                             'or a calibration scan longer than the leg stroke')
    return parser.parse_args(argv)


def parse_only(only: Optional[str]) -> List[int]:
    """Node IDs named by ``--only``, or all legs. Does not consult hardware, so
    the motion guard can run before anything is discovered or claimed."""
    if only is None:
        return sorted(LEG_NODE_IDS)
    try:
        wanted = [int(token) for token in only.split(',') if token.strip()]
    except ValueError:
        raise SystemExit('--only takes comma-separated integers, e.g. --only 0,3')
    illegal = [i for i in wanted if i not in LEG_NODE_IDS]
    if illegal:
        raise SystemExit(
            '--only {} includes node IDs outside the leg set {}. Node {} is '
            'protected and is never written to.'.format(
                illegal, list(LEG_NODE_IDS), list(PROTECTED_NODE_IDS)))
    return sorted(set(wanted))


def resolve_targets(node_by_serial: Dict[str, int], only: Optional[str]) -> List[int]:
    """Node IDs to process, in ascending order, checked against what is attached."""
    wanted = parse_only(only)
    present = set(node_by_serial.values())
    missing = [i for i in wanted if i not in present]
    if missing:
        raise SystemExit('requested node IDs {} are not on USB'.format(missing))
    # Deduplicated: a drive listed twice would be processed twice, and the
    # second pass would run against the handle the first pass's reboot killed.
    return sorted(set(wanted))


def load_fleet_map(path: str) -> Dict[str, int]:
    with open(path) as handle:
        data = json.load(handle)
    return {entry['serial']: int(entry['node_id']) for entry in data['drives']}


def main(argv: Optional[Sequence[str]] = None) -> int:
    args = parse_args(argv)

    # --- preflight: the target file -------------------------------------
    if not os.path.exists(args.config):
        raise SystemExit('target config not found: {}'.format(args.config))
    with open(args.config) as handle:
        target_nested = json.load(handle)
    patch_node_id(target_nested, 0)  # fail now if the file has no node_id path
    if args.calib_scan_distance is not None:
        target_nested = set_config_value(
            target_nested, CALIB_SCAN_DISTANCE_PATH, float(args.calib_scan_distance))
    flat_target = flatten_config(target_nested)

    problems = check_target_is_leg_config(flat_target)
    if problems:
        for line in problems:
            print('CONFIG WARNING: {}'.format(line), file=sys.stderr)
        if not args.force:
            raise SystemExit('refusing to flash this file to the legs (--force overrides)')

    # --- preflight: nothing else owning the drives ----------------------
    # --- preflight: the motion the calibration would command ------------
    # Before discovery, so a scan that cannot fit the stroke is refused
    # immediately rather than after a 30 s wait on USB.
    calibrate = not (args.no_calibration or args.dry_run)
    scan_rev = float(flat_target.get(CALIB_SCAN_DISTANCE_PATH, 0.0))
    scan_vel = float(flat_target.get(CALIB_SCAN_VEL_PATH, 0.0))
    intended_nodes = parse_only(args.only)

    if not args.no_calibration:
        for line in describe_calibration_motion(scan_rev, scan_vel, intended_nodes):
            print(line)
        travel_problems = check_calibration_travel(scan_rev, intended_nodes)
        if travel_problems:
            print('\nSTROKE WARNING — the scan is longer than the leg can travel:',
                  file=sys.stderr)
            for line in travel_problems:
                print('  {}'.format(line), file=sys.stderr)
            fits_rev = LEG_STROKE_MM / max(MM_PER_REV)
            print('  The offset scan is open-loop and does not stop at the index pulse;\n'
                  '  nothing in the ODrive stops it at the end of travel either. Either\n'
                  '  free the legs mechanically and pass --force, or shorten the scan\n'
                  '  with --calib-scan-distance (up to {:.2f} rev fits the {:.0f} mm\n'
                  '  stroke). Note the excursion is one-directional from wherever each\n'
                  '  leg starts, so fitting the stroke is necessary, not sufficient —\n'
                  '  position each leg with that much travel free ahead of it.'.format(
                      fits_rev, LEG_STROKE_MM), file=sys.stderr)
            if not (args.force or args.dry_run):
                raise SystemExit('refusing to command more travel than the leg has')
        print()
    else:
        print('--no-calibration: config only, the motor will not be commanded to move.\n')

    conflicts = find_conflicting_processes(read_proc_cmdlines())
    if conflicts:
        print('CONFLICTING PROCESSES:', file=sys.stderr)
        for pattern, cmd in conflicts:
            print('  [{}] {}'.format(pattern, cmd[:160]), file=sys.stderr)
        if not args.force:
            raise SystemExit(
                'stop the ROS stack / odrivetool / ODrive GUI first: they command '
                'or claim these drives while they are being reflashed '
                '(--force overrides)')

    backup_dir = args.backup_dir or os.path.join(
        DEFAULT_BACKUP_ROOT, datetime.now().strftime('%Y%m%d_%H%M%S'))
    os.makedirs(backup_dir, exist_ok=True)

    print('target config : {}'.format(os.path.relpath(args.config, _PROJECT_ROOT)))
    print('               {} config properties'.format(len(flat_target)))
    print('backup dir    : {}'.format(os.path.relpath(backup_dir, _PROJECT_ROOT)))
    print('legs          : {}   protected: {}'.format(list(LEG_NODE_IDS), list(PROTECTED_NODE_IDS)))

    api = OdriveApi()
    drives = discover(api, args.expect, args.timeout)

    # --- step 1: record the serial -> node ID mapping -------------------
    by_serial: Dict[str, Any] = {}
    node_by_serial: Dict[str, int] = {}
    fw_by_serial: Dict[str, Optional[str]] = {}
    mapped = load_fleet_map(args.map) if args.map else None

    for odrv in drives:
        serial = usb_serial(odrv)
        by_serial[serial] = odrv
        fw_by_serial[serial] = read_fw_version(odrv)
        if mapped is not None:
            if serial not in mapped:
                print('  USB {}: not in the supplied map — ignoring'.format(serial))
                continue
            node_by_serial[serial] = mapped[serial]
        else:
            node_by_serial[serial] = read_node_id(odrv)

    print('\nUSB serial        node ID  firmware  role')
    for serial, node_id in sorted(node_by_serial.items(), key=lambda kv: kv[1]):
        role = 'PROTECTED' if node_id in PROTECTED_NODE_IDS else (
            'leg' if node_id in LEG_NODE_IDS else 'unknown')
        print('  {:<16}  {:>5}    {:<8}  {}'.format(
            serial, node_id, fw_by_serial.get(serial) or '?', role))
    if mapped is not None:
        print('(node IDs from {}, not read off the drives)'.format(args.map))

    errors, warnings = validate_fleet(node_by_serial)
    for line in warnings:
        print('WARNING: {}'.format(line), file=sys.stderr)
    if errors:
        for line in errors:
            print('FLEET ERROR: {}'.format(line), file=sys.stderr)
        raise SystemExit('refusing to touch anything while the fleet looks like this')

    map_path = os.path.join(backup_dir, 'fleet_map.json')
    with open(map_path, 'w') as handle:
        json.dump({
            'recorded': datetime.now().isoformat(timespec='seconds'),
            'target_config': os.path.relpath(args.config, _PROJECT_ROOT),
            'node_id_source': args.map if mapped is not None else 'read from drives',
            'drives': [
                {
                    'serial': serial,
                    'node_id': node_id,
                    'fw_version': fw_by_serial.get(serial),
                    'role': 'protected' if node_id in PROTECTED_NODE_IDS else 'leg',
                }
                for serial, node_id in sorted(node_by_serial.items(), key=lambda kv: kv[1])
            ],
        }, handle, indent=2)
    print('\nmapping recorded -> {}'.format(os.path.relpath(map_path, _PROJECT_ROOT)))

    targets = resolve_targets(node_by_serial, args.only)
    serial_of = {node_id: serial for serial, node_id in node_by_serial.items()}

    # --- dry run: back up and diff, touch nothing -----------------------
    if args.dry_run:
        print('\nDRY RUN — backing up and diffing, nothing will be erased.')
        for node_id in targets:
            serial = serial_of[node_id]
            odrv = by_serial[serial]
            path = os.path.join(backup_dir, 'current_node{}_{}.json'.format(node_id, serial))
            current = write_backup(api, odrv, path)
            rows = diff_flat(current, flatten_config(patch_node_id(target_nested, node_id)))
            print('\n  node {} (USB {}): {} of {} properties differ from the target'.format(
                node_id, serial, len(rows), len(flat_target)))
            for prop, actual, want in rows:
                print('      {}: drive={!r} target={!r}'.format(prop, actual, want))
        print('\nBackups and the map are in {}'.format(os.path.relpath(backup_dir, _PROJECT_ROOT)))
        if args.no_calibration:
            print('Rerun without --dry-run to erase and reflash.')
        else:
            print('Rerun without --dry-run to erase, reflash and calibrate. The '
                  'calibration motion summarised above is what would run.')
        return 0

    # --- the actuation gate, now that the fleet is known and listed ------
    if calibrate and not args.yes:
        print('\nThis will erase, reflash and then CALIBRATE (move) node(s) {},'.format(
            targets))
        print('one at a time, {:.0f} mm of travel each.'.format(
            calibration_travel_mm(scan_rev, targets[0])))
        try:
            reply = input('Type yes to proceed: ')
        except EOFError:
            raise SystemExit('no console to confirm on — pass --yes to run unattended')
        if reply.strip().lower() != 'yes':
            raise SystemExit('aborted at the confirmation prompt')

    # --- steps 2-7, one drive at a time ---------------------------------
    print('\nProcessing {} drive(s) sequentially: {}'.format(len(targets), targets))
    results: List[DriveResult] = []
    for index, node_id in enumerate(targets):
        results.append(process_drive(
            api, by_serial[serial_of[node_id]], node_id, target_nested,
            backup_dir, args.ignore_restore_errors,
            calibrate=calibrate, calib_timeout=args.calib_timeout,
        ))
        if args.pause_between_legs and index < len(targets) - 1:
            try:
                input('  press Enter for node {}, or Ctrl-C to stop: '.format(
                    targets[index + 1]))
            except EOFError:
                raise SystemExit('no console to pause on — drop --pause-between-legs')

    # --- summary --------------------------------------------------------
    print('\n=== summary ==========================================')
    print('node  USB serial        node ID  restore errs  verify diffs  calibration        result')
    for res in results:
        print('{:>4}  {:<16}  {:>7}  {:>12}  {:>12}  {:<18} {}'.format(
            res.node_id, res.serial,
            '?' if res.node_id_after is None else res.node_id_after,
            len(res.restore_errors), len(res.verify_rows),
            'skipped' if res.calibration is None else str(res.calibration)[:18],
            'OK' if res.ok else 'CHECK'))
    print('\nbackups + map: {}'.format(os.path.relpath(backup_dir, _PROJECT_ROOT)))

    if calibrate:
        print('\nper-leg calibration results (what each drive measured for itself):')
        for res in results:
            measured = [row for row in res.calib_changes
                        if 'index_offset' in row[0] or 'phase_' in row[0]]
            if not measured:
                print('  node {}: nothing recorded'.format(res.node_id))
                continue
            print('  node {}: {}'.format(res.node_id, ', '.join(
                '{}={!r}'.format(path.split('.')[-1], after)
                for path, _before, after in measured)))

    failed = [res for res in results if not res.ok]
    if failed:
        print('\n{} drive(s) need attention: {}'.format(
            len(failed), [res.node_id for res in failed]), file=sys.stderr)
        return 1

    print('\nAll {} drive(s) reflashed and verified.'.format(len(results)))
    print('Per-motor calibration (index offset, phase R/L) now carries the '
          'snapshot\'s values — HOME every leg before arming it.')
    return 0


if __name__ == '__main__':
    sys.exit(main())
